// Generated by tools/gen.zig, do not edit.

const text = @import("text.zig");

pub const TextComponent = text.TextComponent;

/// Frame type for an advancement.
pub const FrameType = enum(u8) {
    task,
    challenge,
    goal,
};

/// Display information for an advancement.
pub const AdvancementDisplay = struct {
    title: TextComponent,
    description: TextComponent,
    frame: FrameType,
    show_toast: bool,
    hidden: bool,
    announce_to_chat: bool,
    background: ?[]const u8,
    x: f32,
    y: f32,
};

/// Detailed information about an advancement.
pub const AdvancementInfo = struct {
    id: []const u8,
    parent_id: ?[]const u8,
    criteria: []const []const u8,
    display: ?AdvancementDisplay,
};

/// Represents progress of an advancement for a player.
pub const AdvancementProgress = struct {
    advancement_id: []const u8,
    done: bool,
    awarded_criteria: []const []const u8,
    remaining_criteria: []const []const u8,
};
