// Generated by tools/gen.zig, do not edit.

const uuid = @import("uuid.zig");

pub const Uuid = uuid.Uuid;

pub const ActorEventId = enum(u8) {
    none,
    jump,
    hurt,
    death,
    start_attacking,
    stop_attacking,
    taming_failed,
    taming_succeeded,
    shake_wetness,
    eat_grass,
    fishhook_bubble,
    fishhook_fish_pos,
    fishhook_hook_time,
    fishhook_tease,
    squid_fleeing,
    zombie_converting,
    play_ambient,
    spawn_alive,
    start_offer_flower,
    stop_offer_flower,
    love_hearts,
    villager_angry,
    villager_happy,
    witch_hat_magic,
    fireworks_explode,
    in_love_hearts,
    silverfish_merge_animation,
    guardian_attack_sound,
    drink_potion,
    throw_potion,
    prime_tnt_cart,
    prime_creeper,
    air_supply,
    deprecated_add_player_levels,
    guardian_mining_fatigue,
    agent_swing_arm,
    dragon_start_death_anim,
    ground_dust,
    shake,
    feed,
    baby_age,
    instant_death,
    notify_trade,
    leash_destroyed,
    caravan_updated,
    talisman_activate,
    deprecated_update_structure_feature,
    player_spawned_mob,
    puke,
    update_stack_size,
    start_swimming,
    balloon_pop,
    treasure_hunt,
    summon_agent,
    finished_charging_item,
    actor_grow_up,
    vibration_detected,
    drink_milk,
    shake_wetness_stop,
    kinetic_damage_dealt,
    hurt_without_receiving_damage,
};

pub const SActorEvent = struct {
    target_runtime_id: i64,
    event_id: ActorEventId,
    data: i32,
    fire_at_position: ?struct { f64, f64, f64 },
};

pub const AnimateAction = enum(u8) {
    no_action,
    swing_arm,
    wake_up,
    critical_hit,
    magic_critical_hit,
};

pub const ActorSwingSource = enum(u8) {
    none,
    build,
    mine,
    interact,
    attack,
    use_item,
    throw_item,
    drop_item,
    event,
};

pub const SAnimate = struct {
    action: AnimateAction,
    target_actor_runtime_id: i64,
    data: f32,
    swing_source: ?ActorSwingSource,
};

pub const SBlockPickRequest = struct {
    position: struct { i32, i32, i32 },
    with_data: bool,
    max_slots: u8,
};

pub const SClientCacheBlobStatus = struct {
    miss_hashes: []const i64,
    hit_hashes: []const i64,
};

pub const SClientCacheStatus = struct {
    is_cache_supported: bool,
};

pub const CommandOriginData = struct {
    r_type: []const u8,
    uuid: Uuid,
    request_id: []const u8,
    player_id: i64,
};

pub const SCommandRequest = struct {
    command: []const u8,
    origin: CommandOriginData,
    is_internal: bool,
    version: []const u8,
};

pub const SContainerClose = struct {
    container_id: u8,
    container_type: u8,
    server_initiated_close: bool,
};

pub const SEmote = struct {
    actor_runtime_id: i64,
    emote_id: []const u8,
    emote_length_ticks: i32,
    xuid: []const u8,
    platform_id: []const u8,
    flags: u8,
};

pub const SEmoteList = struct {
    runtime_id: i64,
    emote_piece_ids: []const Uuid,
};

pub const Action = enum(u8) {
    invalid,
    stop_riding,
    interact_update,
    npc_open,
    open_inventory,
};

pub const SInteract = struct {
    action: Action,
    target_runtime_id: i64,
    position: ?struct { f64, f64, f64 },
};

pub const InventoryActionSource = union(enum) {
    container,
    world,
    creative,
    todo,
    unknown: i32,
};

pub const LegacySetItemSlot = struct {
    container_id: u8,
    slots: []const u8,
};

pub const StackRequestItem = struct {
    identifier: ?[]const u8,
    metadata_value: i32,
    count: i32,
    block_runtime_id: i32,
    extra_data: []const u8,
};

pub const ItemStackRequestActionCreate = struct {
    result_index: u8,
};

pub const ItemStackRequestActionBeaconPayment = struct {
    primary_effect_id: i32,
    secondary_effect_id: i32,
};

pub const ItemStackRequestActionMineBlock = struct {
    hotbar_slot: i32,
    predicted_durability: i32,
    stack_id: i32,
};

pub const ItemStackRequestActionCraftRecipe = struct {
    recipe_id: i32,
    repetitions: u8,
};

pub const ItemStackRequestActionCraftRecipeAuto = struct {
    recipe_id: i32,
    repetitions: u8,
};

pub const ItemStackRequestActionCraftCreative = struct {
    creative_item_id: i32,
    repetitions: u8,
};

pub const ItemStackRequestActionOptional = struct {
    recipe_id: i32,
    filter_string_index: i32,
};

pub const ItemStackRequestActionGrindstone = struct {
    recipe_id: i32,
    repair_cost: i32,
    repetitions: u8,
};

pub const ItemStackRequestActionLoom = struct {
    pattern_id: []const u8,
    repetitions: u8,
};

pub const ItemStackRequestActionCraftResultsDeprecated = struct {
    result_items: []const StackRequestItem,
    times_crafted: u8,
};

pub const LoadingScreenPacketType = enum(u8) {
    start_loading_screen,
    end_loading_screen,
};

pub const SLoadingScreen = struct {
    loading_screen_packet_type: LoadingScreenPacketType,
    loading_screen_id: ?i32,
};

pub const SLogin = struct {
    protocol_version: i32,
    jwt: []const u8,
    raw_token: []const u8,
};

pub const SkinAnimation = struct {
    frames: f64,
    image: []const u8,
    image_height: i32,
    image_width: i32,
    animation_type: i32,
    animation_expression: i32,
};

pub const PersonaPiece = struct {
    is_default: bool,
    pack_id: []const u8,
    piece_id: []const u8,
    piece_type: []const u8,
    product_id: []const u8,
};

pub const PersonaPieceTintColour = struct {
    colours: []const []const u8,
    piece_type: []const u8,
};

pub const ClientData = struct {
    client_random_id: i64,
    device_os: i32,
    device_id: []const u8,
    game_version: []const u8,
    language_code: []const u8,
    current_input_mode: i32,
    default_input_mode: i32,
    ui_profile: i32,
    server_address: []const u8,
    device_model: []const u8,
    gui_scale: i32,
    client_is_editor_capable: bool,
    client_editor_connection_intent: i32,
    max_view_distance: i32,
    memory_tier: i32,
    platform_type: i32,
    graphics_mode: i32,
    compatible_with_client_side_chunk_gen: bool,
    platform_offline_id: []const u8,
    platform_online_id: []const u8,
    platform_user_id: []const u8,
    self_signed_id: []const u8,
    play_fab_id: []const u8,
    third_party_name: []const u8,
    third_party_name_only: bool,
    skin_id: []const u8,
    skin_data: []const u8,
    skin_image_height: i32,
    skin_image_width: i32,
    skin_colour: []const u8,
    arm_size: []const u8,
    persona_skin: bool,
    premium_skin: bool,
    trusted_skin: bool,
    override_skin: bool,
    cape_data: []const u8,
    cape_id: []const u8,
    cape_image_height: i32,
    cape_image_width: i32,
    cape_on_classic_skin: bool,
    skin_geometry: []const u8,
    skin_geometry_version: []const u8,
    skin_resource_patch: []const u8,
    animated_image_data: []const SkinAnimation,
    skin_animation_data: []const u8,
    persona_pieces: []const PersonaPiece,
    piece_tint_colours: []const PersonaPieceTintColour,
};

pub const SModalFormResponse = struct {
    form_id: i32,
    json_response: ?[]const u8,
    form_cancel_reason: ?u8,
};

pub const SPacketViolationWarning = struct {
    violation_type: i32,
    violation_severity: i32,
    violation_packet_id: i32,
    violation_context: []const u8,
};

pub const PlayerActionType = enum(u8) {
    unknown,
    start_destroy_block,
    abort_destroy_block,
    stop_destroy_block,
    get_updated_block,
    drop_item,
    start_sleeping,
    stop_sleeping,
    respawn,
    start_jump,
    start_sprinting,
    stop_sprinting,
    start_sneaking,
    stop_sneaking,
    creative_destroy_block,
    change_dimension_ack,
    start_gliding,
    stop_gliding,
    deny_destroy_block,
    crack_block,
    change_skin,
    updated_enchanting_seed,
    start_swimming,
    stop_swimming,
    start_spin_attack,
    stop_spin_attack,
    interact_with_block,
    predict_destroy_block,
    continue_destroy_block,
    start_item_use_on,
    stop_item_use_on,
    handled_teleport,
    missed_swing,
    start_crawling,
    stop_crawling,
    start_flying,
    stop_flying,
    client_ack_server_data,
    start_using_item,
    internal_update,
    count,
};

pub const SPlayerAction = struct {
    player_runtime_id: i64,
    action: PlayerActionType,
    block_position: struct { i32, i32, i32 },
    result_pos: struct { i32, i32, i32 },
    face: i32,
};

pub const PlayerBlockAction = struct {
    action: i32,
    block_pos: struct { i32, i32, i32 },
    face: i32,
};

pub const InputMode = enum(u8) {
    mouse,
    touch,
    game_pad,
    motion_controller,
};

pub const PlayMode = enum(u8) {
    normal,
    teaser,
    screen,
    exit_level,
    num_modes,
};

pub const InteractionModel = enum(u8) {
    touch,
    crosshair,
    classic,
};

pub const InputData = enum(u8) {
    ascend,
    descend,
    north_jump,
    jump_down,
    sprint_down,
    change_height,
    jumping,
    auto_jumping_in_water,
    sneaking,
    sneak_down,
    up,
    down,
    left,
    right,
    up_left,
    up_right,
    want_up,
    want_down,
    want_down_slow,
    want_up_slow,
    sprinting,
    ascend_block,
    descend_block,
    sneak_toggle_down,
    persist_sneak,
    start_sprinting,
    stop_sprinting,
    start_sneaking,
    stop_sneaking,
    start_swimming,
    stop_swimming,
    start_jumping,
    start_gliding,
    stop_gliding,
    perform_item_interaction,
    perform_block_actions,
    perform_item_stack_request,
    handled_teleport,
    emoting,
    missed_swing,
    start_crawling,
    stop_crawling,
    start_flying,
    stop_flying,
    client_ack_server_data,
    client_predicted_vehicle,
    paddling_left,
    paddling_right,
    block_breaking_delay_enabled,
    horizontal_collision,
    vertical_collision,
    down_left,
    down_right,
    start_using_item,
    camera_relative_movement_enabled,
    rot_controlled_by_move_direction,
    start_spin_attack,
    stop_spin_attack,
    is_hotbar_touch_only,
    jump_released_raw,
    jump_pressed_raw,
    jump_current_raw,
    sneak_released_raw,
    sneak_pressed_raw,
    sneak_current_raw,
    internal_update,
};

pub const SPlayerHotbar = struct {
    selected_slot: i32,
    container_id: u8,
    should_select_slot: bool,
};

pub const AbilityValue = union(enum) {
    bool: bool,
    float: f32,
};

pub const SRequestAbility = struct {
    ability: i32,
    value: AbilityValue,
};

pub const SRequestChunkRadius = struct {
    chunk_radius: i32,
    max_chunk_radius: u8,
};

pub const SRequestNetworkSettings = struct {
    client_network_version: i32,
};

pub const SResourcePackClientResponse = struct {
    response: u8,
    download_size: i32,
    pack_ids: []const []const u8,
};

pub const RespawnState = enum(u8) {
    searching_for_spawn,
    ready_to_spawn,
    client_ready_to_spawn,
};

pub const SRespawn = struct {
    position: struct { f64, f64, f64 },
    state: RespawnState,
    player_runtime_id: i64,
};

pub const SSetLocalPlayerAsInitialized = struct {
    player_id: i64,
};

pub const SSetPlayerInventoryOptions = struct {
    left_inventory_tab: i32,
    right_inventory_tab: i32,
    filtering: bool,
    layout_inv: i32,
    layout_craft: i32,
};

pub const TextPacketType = enum(u8) {
    raw,
    chat,
    translation,
    popup,
    jukebox_popup,
    tip,
    system,
    whisper,
    announcement,
    json_whisper,
    json,
    json_announcement,
};

pub const SText = struct {
    needs_translation: bool,
    r_type: TextPacketType,
    source_name: []const u8,
    message: []const u8,
    parameters: []const []const u8,
    xuid: []const u8,
    platform_chat_id: []const u8,
    filtered_message: ?[]const u8,
};

pub const SyncedAttribute = struct {
    attribute_name: []const u8,
    min_value: f32,
    current_value: f32,
    max_value: f32,
};

pub const EnumData = struct {
    name: []const u8,
    values: []const i32,
};

pub const ChainedSubcommandRelationship = struct {
    index: i32,
    value: i32,
};

pub const ChainedSubcommandData = struct {
    name: []const u8,
    subcommand_values: []const ChainedSubcommandRelationship,
};

pub const ParamData = struct {
    name: []const u8,
    parse_symbol: i32,
    is_optional: bool,
    options: u8,
};

pub const OverloadData = struct {
    is_chaining: bool,
    parameter_data: []const ParamData,
};

pub const SoftEnumData = struct {
    enum_name: []const u8,
    enum_options: []const []const u8,
};

pub const ConstrainedValueData = struct {
    enum_value_symbol: i32,
    enum_symbol: i32,
    constraint_indices: []const u8,
};

pub const CBlockActorData = struct {
    block_position: struct { i32, i32, i32 },
    actor_data_tags: []const u8,
};

pub const CBlockEvent = struct {
    block_position: struct { i32, i32, i32 },
    event_type: i32,
    event_value: i32,
};

pub const CBossEvent = struct {
    boss_entity_id: i64,
    event_type: u8,
    title: []const u8,
    filtered_title: []const u8,
    health_percentage: f32,
    color: u8,
    overlay: u8,
};

pub const CChangeDimension = struct {
    dimension_id: i32,
    position: struct { f64, f64, f64 },
    respawn: bool,
    loading_screen_id: ?i32,
};

pub const CChunkRadiusUpdated = struct {
    chunk_radius: i32,
};

pub const MissingBlobData = struct {
    blob_id: i64,
    blob_data: []const u8,
};

pub const CClientCacheMissResponse = struct {
    missing_blobs: []const MissingBlobData,
};

pub const BuildPlatform = enum(u8) {
    unknown,
    google,
    ios,
    osx,
    amazon,
    gear_vr,
    uwp,
    win32,
    dedicated,
    tv_os,
    sony,
    nx,
    xbox,
    windows_phone,
    linux,
};

pub const GameType = enum(u8) {
    unknown,
    survival,
    creative,
    adventure,
    default,
    spectator,
};

pub const PlayerPermissionLevel = enum(u8) {
    visitor,
    member,
    operator,
    custom,
};

pub const CommandPermissionLevel = enum(u8) {
    any,
    game_directors,
    admin,
    host,
    owner,
    internal,
};

pub const CommandData = struct {
    name: []const u8,
    description: []const u8,
    flags: i32,
    permission_level: CommandPermissionLevel,
    alias_enum: i32,
    command_data_chained_subcommand_indexes: []const i32,
    overloads: []const OverloadData,
};

pub const CAvailableCommands = struct {
    enum_values: []const []const u8,
    chained_subcommand_values: []const []const u8,
    post_fixes: []const []const u8,
    enum_data: []const EnumData,
    chained_subcommand_data: []const ChainedSubcommandData,
    commands: []const CommandData,
    soft_enums: []const SoftEnumData,
    constraints: []const ConstrainedValueData,
};

pub const SerializedAbilitiesDataSerializedLayer = struct {
    serialized_layer: i32,
    abilities_set: i32,
    ability_value: i32,
    fly_speed: f32,
    vertical_fly_speed: f32,
    walk_speed: f32,
};

pub const SerializedAbilitiesData = struct {
    target_player_raw_id: i64,
    player_permissions: PlayerPermissionLevel,
    command_permissions: CommandPermissionLevel,
    layers: []const SerializedAbilitiesDataSerializedLayer,
};

pub const ActorLink = struct {
    ridden_unique_id: i64,
    rider_unique_id: i64,
    link_type: u8,
    immediate: bool,
    rider_initiated: bool,
    vehicle_angular_velocity: f32,
};

pub const CContainerOpen = struct {
    container_id: u8,
    container_type: u8,
    position: struct { i32, i32, i32 },
    target_entity_id: i64,
};

pub const CCorrectPlayerMovePrediction = struct {
    prediction_type: u8,
    pos: struct { f64, f64, f64 },
    pos_delta: struct { f64, f64, f64 },
    rotation: struct { f64, f64 },
    vehicle_angular_velocity: ?f32,
    on_ground: bool,
    tick: i64,
};

pub const ItemDescriptorCount = struct {
    item_identifier: []const u8,
    metadata_value: i32,
    count: i32,
};

pub const RecipeUnlockRequirement = struct {
    context: i32,
};

pub const CreativeCategory = enum(u8) {
    all,
    construction,
    nature,
    equipment,
    items,
    item_command_only,
    undefined,
};

pub const CDisconnect = struct {
    reason: i32,
    skip_message: bool,
    message: []const u8,
    filtered_message: []const u8,
};

pub const RuleValue = enum(u8) {
    null,
};

pub const GameRule = struct {
    rule_name: []const u8,
    rule_can_be_modified: bool,
    rule_value: RuleValue,
};

pub const CGamerulesChanged = struct {
    rule_data: []const GameRule,
};

pub const ItemData = struct {
    item_name: []const u8,
    item_id: i32,
    is_component_based: bool,
    item_version: i32,
    component_data: []const u8,
};

pub const CItemRegistry = struct {
    items: []const ItemData,
};

pub const ItemStackResponseSlotInfo = struct {
    requested_slot: u8,
    slot: u8,
    amount: u8,
    item_stack_net_id: i32,
    custom_name: []const u8,
    filtered_custom_name: []const u8,
    durability_correction: i32,
};

pub const CLevelEvent = struct {
    event_id: i32,
    position: struct { f64, f64, f64 },
    data: i32,
};

pub const LevelEvent = enum(u8) {
    particles_destroy_block,
    block_start_break,
    block_stop_break,
    block_update_break,
};

pub const CLevelSoundEvent = struct {
    sound_event: []const u8,
    position: struct { f64, f64, f64 },
    data: i32,
    actor_identifier: []const u8,
    is_baby: bool,
    is_global: bool,
    actor_unique_id: i64,
    fire_at_position: ?struct { f64, f64, f64 },
};

pub const CMobEffect = struct {
    target_runtime_id: i64,
    event_id: u8,
    effect_id: i32,
    effect_amplifier: i32,
    show_particles: bool,
    effect_duration_ticks: i32,
    tick: i64,
    ambient: bool,
};

pub const CModalFormRequest = struct {
    form_id: i32,
    form_ui_json: []const u8,
};

pub const CMoveActorAbsolute = struct {
    actor_runtime_id: i64,
    header: u8,
    position: struct { f64, f64, f64 },
    rotation_x: u8,
    rotation_y: u8,
    rotation_y_head: u8,
};

pub const CMoveActorDelta = struct {
    entity_runtime_id: i64,
    flags: i32,
    x: f32,
    y: f32,
    z: f32,
    pitch: u8,
    yaw: u8,
    head_yaw: u8,
    tick: i64,
};

pub const CMovePlayer = struct {
    player_runtime_id: i64,
    position: struct { f64, f64, f64 },
    pitch: f32,
    yaw: f32,
    head_yaw: f32,
    mode: u8,
    on_ground: bool,
    riding_runtime_id: i64,
    teleport_cause: i32,
    teleport_source_entity_type: i32,
    tick: i64,
};

pub const CNetworkChunkPublisherUpdate = struct {
    pos_for_view: struct { i32, i32, i32 },
    new_radius: i32,
    server_build_chunk_list: []const struct { f64, f64 },
};

pub const CNetworkSettings = struct {
    compression_threshold: i32,
    compression_algorithm: i32,
    client_throttle_enabled: bool,
    client_throttle_threshold: u8,
    client_throttle_scalar: f32,
};

pub const CPlayStatus = enum(u8) {
    login_success,
    outdated_client,
    outdated_server,
    player_spawn,
    invalid_tenant,
    edition_mismatch_edu_to_vanilla,
    edition_mismatch_vanilla_to_edu,
    server_full_sub_client,
    editor_mismatch_editor_to_vanilla,
    editor_mismatch_vanilla_to_editor,
};

pub const CPlayerHotbar = struct {
    selected_slot: i32,
    container_id: u8,
    should_select_slot: bool,
};

pub const PieceTintColor = struct {
    piece_type: []const u8,
    colors: []const i32,
};

pub const Skin = struct {
    skin_id: []const u8,
    play_fab_id: []const u8,
    resource_patch: []const u8,
    image_width: i32,
    image_height: i32,
    skin_data: []const u8,
    animations: []const SkinAnimation,
    cape_width: i32,
    cape_height: i32,
    cape_data: []const u8,
    geometry_data: []const u8,
    animation_data: []const u8,
    geometry_data_engine_version: []const u8,
    cape_id: []const u8,
    full_id: []const u8,
    arm_size: []const u8,
    skin_color: []const u8,
    persona_pieces: []const PersonaPiece,
    piece_tint_colors: []const PieceTintColor,
    is_premium: bool,
    is_persona: bool,
    persona_cape_on_classic: bool,
    is_primary_user: bool,
    override_appearance: bool,
    is_trusted: bool,
    profile_hash: []const u8,
};

pub const PlayerListEntry = struct {
    uuid: Uuid,
    entity_unique_id: i64,
    username: []const u8,
    xuid: []const u8,
    platform_chat_id: []const u8,
    build_platform: BuildPlatform,
    skin: Skin,
    is_teacher: bool,
    is_host: bool,
    is_sub_client: bool,
    player_color: []const u8,
};

pub const CPlayerList = struct {
    action: u8,
    entries: []const PlayerListEntry,
};

pub const CRemoveActor = struct {
    target_actor_id: i64,
};

pub const CRemoveObjective = struct {
    objective_name: []const u8,
};

pub const PackInstanceId = struct {
    pack_id: []const u8,
    version: []const u8,
    sub_pack_name: []const u8,
};

pub const PackIdVersion = struct {
    pack_uuid: Uuid,
    pack_version: []const u8,
};

pub const PackInfoData = struct {
    pack_id_version: PackIdVersion,
    pack_size: i64,
    content_key: []const u8,
    subpack_name: []const u8,
    content_identity: []const u8,
    has_scripts: bool,
    is_addon_pack: bool,
    is_ray_tracing_capable: bool,
    cdn_url: []const u8,
};

pub const CResourcePacksInfo = struct {
    resource_pack_required: bool,
    has_addon_packs: bool,
    has_scripts: bool,
    force_disable_vibrant_visuals: bool,
    world_template_id_and_version: PackIdVersion,
    resource_packs: []const PackInfoData,
};

pub const MetadataValue = union(enum) {
    byte: u8,
    short: i32,
    int: i32,
    float: f32,
    string: []const u8,
    compound_tag,
    item_pos: struct { i32, i32, i32 },
    int64: i64,
    vec3: struct { f64, f64, f64 },
};

pub const PropertySyncData = struct {
    int_entries_list: []const struct { i32, i32 },
    float_entries_list: []const struct { i32, f32 },
};

pub const CAddActor = struct {
    target_actor_id: i64,
    target_runtime_id: i64,
    actor_type: []const u8,
    position: struct { f64, f64, f64 },
    velocity: struct { f64, f64, f64 },
    rotation: struct { f64, f64 },
    y_head_rotation: f32,
    y_body_rotation: f32,
    attributes_list: []const SyncedAttribute,
    actor_data: []const u8,
    synced_properties: PropertySyncData,
    actor_links: []const ActorLink,
};

pub const CSetActorData = struct {
    target_runtime_id: i64,
    actor_data: []const u8,
    synced_properties: PropertySyncData,
    tick: i64,
};

pub const CSetActorLink = struct {
    link: ActorLink,
};

pub const CSetActorMotion = struct {
    target_runtime_id: i64,
    motion: struct { f64, f64, f64 },
    tick: i64,
};

pub const CSetDifficulty = struct {
    difficulty: i32,
};

pub const CSetDisplayObjective = struct {
    display_slot_name: []const u8,
    objective_name: []const u8,
    objective_display_name: []const u8,
    criteria_name: []const u8,
    sort_order: i32,
};

pub const CSetHealth = struct {
    health: i32,
};

pub const CSetPlayerGameType = struct {
    player_game_type: GameType,
};

pub const ScoreEntry = struct {
    scoreboard_id: i64,
    objective_name: []const u8,
    score: i32,
    entry_type: i32,
    entity_unique_id: i64,
    custom_name: []const u8,
};

pub const CSetScore = struct {
    action: i32,
    entries: []const ScoreEntry,
};

pub const SpawnPositionType = enum(u8) {
    player_respawn,
    world_respawn,
};

pub const CSetSpawnPosition = struct {
    spawn_position_type: SpawnPositionType,
    block_position: struct { i32, i32, i32 },
    dimension_type: i32,
    spawn_block_pos: struct { i32, i32, i32 },
};

pub const CSetTime = struct {
    time: i32,
};

pub const TitleType = enum(u8) {
    clear,
    reset,
    title,
    subtitle,
    actionbar,
    times,
    title_text_object,
    subtitle_text_object,
    actionbar_text_object,
};

pub const CSetTitle = struct {
    title_type: TitleType,
    title_text: []const u8,
    fade_in_time: i32,
    stay_time: i32,
    fade_out_time: i32,
    xuid: []const u8,
    platform_online_id: []const u8,
    filtered_title_message: []const u8,
};

pub const CShowCredits = struct {
    player_runtime_id: i64,
    credits_state: i32,
};

pub const GatheringJoinInfo = struct {
    experience_id: Uuid,
    experience_name: []const u8,
    experience_world_id: Uuid,
    experience_world_name: []const u8,
    creator_id: []const u8,
    unknown_uuid_1: Uuid,
    unknown_uuid_2: Uuid,
    server_id: []const u8,
};

pub const StoreEntryPointInfo = struct {
    store_id: []const u8,
    store_name: []const u8,
};

pub const PresenceInfo = struct {
    experience_name: []const u8,
    world_name: []const u8,
};

pub const ServerJoinInformation = struct {
    gathering: ?GatheringJoinInfo,
    store_entry_point: ?StoreEntryPointInfo,
    presence: ?PresenceInfo,
};

pub const ServerTelemetryData = struct {
    server_id: []const u8,
    scenario_id: []const u8,
    world_id: []const u8,
    owner_id: []const u8,
};

pub const ExperimentToggle = struct {
    name: []const u8,
    enabled: bool,
};

pub const Experiments = struct {
    toggles: []const ExperimentToggle,
    experiments_ever_toggled: bool,
};

pub const CResourcePackStackPacket = struct {
    texture_pack_required: bool,
    texture_pack_list: []const PackInstanceId,
    base_game_version: []const u8,
    experiments: Experiments,
    include_editor_packs: bool,
};

pub const GamePublishSetting = enum(u8) {
    no_multi_play,
    invite_only,
    friends_only,
    friends_of_friends,
    public,
};

pub const LevelSettings = struct {
    seed: i64,
    spawn_biome_type: i32,
    custom_biome_name: []const u8,
    dimension: i32,
    generator_type: i32,
    world_gamemode: GameType,
    hardcore: bool,
    difficulty: i32,
    spawn_position: struct { i32, i32, i32 },
    has_achievements_disabled: bool,
    editor_world_type: i32,
    is_created_in_editor: bool,
    is_exported_from_editor: bool,
    day_cycle_stop_time: i32,
    education_edition_offer: i32,
    has_education_features_enabled: bool,
    education_product_id: []const u8,
    rain_level: f32,
    lightning_level: f32,
    has_confirmed_platform_locked_content: bool,
    was_multiplayer_intended: bool,
    was_lan_broadcasting_intended: bool,
    xbox_live_broadcast_setting: GamePublishSetting,
    platform_broadcast_setting: GamePublishSetting,
    commands_enabled: bool,
    is_texture_packs_required: bool,
    rule_data: []const GameRule,
    experiments: Experiments,
    bonus_chest: bool,
    has_start_with_map_enabled: bool,
    permission_level: u8,
    server_simulation_distance: i32,
    has_locked_behavior_pack: bool,
    has_locked_resource_pack: bool,
    is_from_locked_world_template: bool,
    is_using_msa_gamertags_only: bool,
    is_from_world_template: bool,
    is_world_template_option_locked: bool,
    is_only_spawning_v1_villagers: bool,
    is_disabling_personas: bool,
    is_disabling_custom_skins: bool,
    emote_chat_muted: bool,
    game_version: []const u8,
    limited_world_width: i32,
    limited_world_height: i32,
    new_nether: bool,
    edu_shared_uri_button_name: []const u8,
    edu_shared_uri_link_uri: []const u8,
    override_force_experimental_gameplay_has_value: bool,
    chat_restriction_level: u8,
    disable_player_interactions: bool,
    server_editor_connection_policy: i32,
    allow_anonymous_block_drops_in_editor_worlds: bool,
};

pub const CStartGame = struct {
    entity_id: i64,
    runtime_entity_id: i64,
    player_gamemode: GameType,
    position: struct { f64, f64, f64 },
    pitch: f32,
    yaw: f32,
    level_settings: LevelSettings,
    level_id: []const u8,
    level_name: []const u8,
    premium_world_template_id: []const u8,
    is_trial: bool,
    rewind_history_size: i32,
    server_authoritative_block_breaking: bool,
    current_level_time: i64,
    enchantment_seed: i32,
    block_properties_size: i32,
    multiplayer_correlation_id: []const u8,
    enable_itemstack_net_manager: bool,
    server_version: []const u8,
    compound_id: u8,
    compound_len: i32,
    compound_end: u8,
    block_registry_checksum: i64,
    world_template_id: Uuid,
    enable_clientside_generation: bool,
    blocknetwork_ids_are_hashed: bool,
    server_auth_sounds: bool,
    server_join_information: ?ServerJoinInformation,
    telemetry: ServerTelemetryData,
};

pub const Gg = struct {
    name: []const u8,
    id: u8,
    len: i32,
    end: u8,
};

pub const CTakeItemActor = struct {
    item_runtime_id: i64,
    actor_runtime_id: i64,
};

pub const CTransfer = struct {
    server_address: []const u8,
    server_port: i32,
    reload_world: bool,
};

pub const CUpdateAbilities = struct {
    data: SerializedAbilitiesData,
};

pub const Ability = enum(u8) {
    build,
    mine,
    doors_and_switches,
    open_containers,
    attack_players,
    attack_mobs,
    operator_commands,
    teleport,
    invulnerable,
    flying,
    may_fly,
    instabuild,
    lightning,
    fly_speed,
    walk_speed,
    muted,
    world_builder,
    no_clip,
    privileged_builder,
    vertical_fly_speed,
    ability_count,
};

pub const AttributeModifier = struct {
    id: []const u8,
    name: []const u8,
    amount: f32,
    operation: i32,
    operand: i32,
    is_serializable: bool,
};

pub const AttributeData = struct {
    min_value: f32,
    max_value: f32,
    current_value: f32,
    default_min_value: f32,
    default_max_value: f32,
    default_value: f32,
    name: []const u8,
    modifiers: []const AttributeModifier,
};

pub const CUpdateAttributes = struct {
    target_runtime_id: i64,
    attribute_list: []const AttributeData,
    tick: i64,
};

pub const CUpdateBlock = struct {
    block_position: struct { i32, i32, i32 },
    block_runtime_id: i32,
    flags: i32,
    layer: i32,
};

pub const CUpdateTrade = struct {
    container_id: u8,
    r_type: u8,
    size: i32,
    trader_tier: i32,
    entity_unique_id: i64,
    last_trading_player: i64,
    display_name: []const u8,
    use_new_trade_screen: bool,
    using_economy_trade: bool,
    data: []const u8,
};

pub const NetworkItemDescriptor = struct {
    id: i32,
    stack_size: i32,
    aux_value: i32,
    block_runtime_id: i32,
    nbt_data: []const u8,
    place_on_blocks: []const []const u8,
    destroy_blocks: []const []const u8,
    shield_blocking_tick: i64,
};

pub const InventoryAction = struct {
    source_type: i32,
    window_id: ?i32,
    source_flags: ?i32,
    inventory_slot: i32,
    old_item: NetworkItemDescriptor,
    new_item: NetworkItemDescriptor,
};

pub const UseItemTransactionData = struct {
    action_type: i32,
    trigger_type: u8,
    block_position: struct { i32, i32, i32 },
    block_face: u8,
    hot_bar_slot: i32,
    hand: u8,
    item_in_hand: NetworkItemDescriptor,
    player_position: struct { f64, f64, f64 },
    click_position: struct { f64, f64, f64 },
    block_runtime_id: i32,
    client_prediction: u8,
    client_cooldown_state: u8,
};

pub const UseItemOnEntityTransactionData = struct {
    target_entity_runtime_id: i64,
    action_type: i32,
    hot_bar_slot: i32,
    item_in_hand: NetworkItemDescriptor,
    player_position: struct { f64, f64, f64 },
    click_position: struct { f64, f64, f64 },
};

pub const ReleaseItemTransactionData = struct {
    action_type: i32,
    hot_bar_slot: i32,
    item_in_hand: NetworkItemDescriptor,
    head_position: struct { f64, f64, f64 },
};

pub const TransactionData = union(enum) {
    normal: []const u8,
    mismatch: []const u8,
    use_item: UseItemTransactionData,
    use_item_on_entity: UseItemOnEntityTransactionData,
    release_item: ReleaseItemTransactionData,
};

pub const SInventoryTransaction = struct {
    legacy_request_id: i32,
    legacy_set_item_slots: []const LegacySetItemSlot,
    has_value: bool,
    actions: []const InventoryAction,
    transaction_type: i32,
    transaction_data: TransactionData,
};

pub const PlayerUseItemTransactionData = struct {
    action_type: i32,
    trigger_type: u8,
    block_position: struct { i32, i32, i32 },
    block_face: u8,
    hot_bar_slot: i32,
    item_in_hand: NetworkItemDescriptor,
    player_position: struct { f64, f64, f64 },
    click_position: struct { f64, f64, f64 },
    block_runtime_id: i32,
    client_prediction: u8,
    client_cooldown_state: u8,
};

pub const PlayerInventoryAction = struct {
    legacy_request_id: i32,
    legacy_slots: []const LegacySetItemSlot,
    actions: []const InventoryAction,
    transaction: PlayerUseItemTransactionData,
};

pub const BedrockShapelessRecipe = struct {
    recipe_id: []const u8,
    input: []const ItemDescriptorCount,
    output: []const NetworkItemDescriptor,
    uuid: Uuid,
    block: []const u8,
    priority: i32,
    unlock_requirement: RecipeUnlockRequirement,
    recipe_network_id: i32,
};

pub const BedrockShapedRecipe = struct {
    recipe_id: []const u8,
    width: i32,
    height: i32,
    input: []const ItemDescriptorCount,
    output: []const NetworkItemDescriptor,
    uuid: Uuid,
    block: []const u8,
    priority: i32,
    assume_symmetry: bool,
    unlock_requirement: RecipeUnlockRequirement,
    recipe_network_id: i32,
};

pub const BedrockRecipe = union(enum) {
    shapeless: BedrockShapelessRecipe,
    shaped: BedrockShapedRecipe,
};

pub const CCraftingData = struct {
    recipes: []const BedrockRecipe,
    clean_recipes: bool,
};

pub const CreativeGroupInfoPayload = struct {
    creative_category: CreativeCategory,
    name: []const u8,
    group_icon_item: NetworkItemDescriptor,
};

pub const CreativeItemEntryPayload = struct {
    id: i32,
    item: NetworkItemDescriptor,
    group_index: i32,
};

pub const CCreativeContent = struct {
    groups: []const CreativeGroupInfoPayload,
    entries: []const CreativeItemEntryPayload,
};

pub const ItemStackWrapper = struct {
    id: i32,
    stack_size: i32,
    aux_value: i32,
    block_runtime_id: i32,
    nbt_data: []const u8,
    place_on_blocks: []const []const u8,
    destroy_blocks: []const []const u8,
    shield_blocking_tick: i64,
    net_id: ?i32,
};

pub const CAddItemActor = struct {
    target_actor_id: i64,
    target_runtime_id: i64,
    item: ItemStackWrapper,
    position: struct { f64, f64, f64 },
    velocity: struct { f64, f64, f64 },
    entity_data: []const u8,
    is_from_fishing: bool,
};

pub const NetworkItemStackDescriptor = struct {
    id: i32,
    stack_size: i32,
    aux_value: i32,
    block_runtime_id: i32,
    extra_data: []const u8,
    net_id: ?i32,
};

pub const SMobEquipment = struct {
    entity_runtime_id: i64,
    item: NetworkItemStackDescriptor,
    slot: u8,
    selected_slot: u8,
    container_id: u8,
};

pub const CAddPlayer = struct {
    uuid: Uuid,
    player_name: []const u8,
    target_runtime_id: i64,
    platform_chat_id: []const u8,
    position: struct { f64, f64, f64 },
    velocity: struct { f64, f64, f64 },
    rotation: struct { f64, f64 },
    y_head_rotation: f32,
    carried_item: NetworkItemStackDescriptor,
    player_game_type: GameType,
    entity_data: []const u8,
    synced_properties: PropertySyncData,
    abilities_data: SerializedAbilitiesData,
    actor_links: []const ActorLink,
    device_id: []const u8,
    build_platform: BuildPlatform,
};

pub const CMobEquipment = struct {
    target_runtime_id: i64,
    item: NetworkItemStackDescriptor,
    slot: u8,
    selected_slot: u8,
    container_id: u8,
};

pub const ContainerName = enum(u8) {
    anvil_input,
    anvil_material,
    anvil_result_preview,
    smithing_table_input,
    smithing_table_material,
    smithing_table_result_preview,
    armor,
    level_entity,
    beacon_payment,
    brewing_stand_input,
    brewing_stand_result,
    brewing_stand_fuel,
    combined_hot_bar_and_inventory,
    crafting_input,
    crafting_output_preview,
    recipe_construction,
    recipe_nature,
    recipe_items,
    recipe_search,
    recipe_search_bar,
    recipe_equipment,
    recipe_book,
    enchanting_input,
    enchanting_material,
    furnace_fuel,
    furnace_ingredient,
    furnace_result,
    horse_equip,
    hot_bar,
    inventory,
    shulker_box,
    trade_ingredient1,
    trade_ingredient2,
    trade_result_preview,
    offhand,
    compound_creator_input,
    compound_creator_output_preview,
    element_constructor_output_preview,
    material_reducer_input,
    material_reducer_output,
    lab_table_input,
    loom_input,
    loom_dye,
    loom_material,
    loom_result_preview,
    blast_furnace_ingredient,
    smoker_ingredient,
    trade2_ingredient1,
    trade2_ingredient2,
    trade2_result_preview,
    grindstone_input,
    grindstone_additional,
    grindstone_result_preview,
    stonecutter_input,
    stonecutter_result_preview,
    cartography_input,
    cartography_additional,
    cartography_result_preview,
    barrel,
    cursor,
    created_output,
    smithing_table_template,
    crafter_level_entity,
    dynamic,
    recipe_food,
    recipe_blocks,
    recipe_furnace_items,
};

pub const FullContainerName = struct {
    container_name: ContainerName,
    dynamic_id: ?i32,
};

pub const ItemStackRequestSlotInfo = struct {
    container_name: FullContainerName,
    slot_id: u8,
    stack_id: i32,
};

pub const ItemStackRequestActionTake = struct {
    count: u8,
    source: ItemStackRequestSlotInfo,
    destination: ItemStackRequestSlotInfo,
};

pub const ItemStackRequestActionPlace = struct {
    count: u8,
    source: ItemStackRequestSlotInfo,
    destination: ItemStackRequestSlotInfo,
};

pub const ItemStackRequestActionSwap = struct {
    slot1: ItemStackRequestSlotInfo,
    slot2: ItemStackRequestSlotInfo,
};

pub const ItemStackRequestActionDrop = struct {
    count: u8,
    source: ItemStackRequestSlotInfo,
    randomly: bool,
};

pub const ItemStackRequestActionDestroy = struct {
    count: u8,
    source: ItemStackRequestSlotInfo,
};

pub const ItemStackRequestActionConsume = struct {
    count: u8,
    source: ItemStackRequestSlotInfo,
};

pub const ItemStackRequestAction = union(enum) {
    take: ItemStackRequestActionTake,
    place: ItemStackRequestActionPlace,
    swap: ItemStackRequestActionSwap,
    drop: ItemStackRequestActionDrop,
    destroy: ItemStackRequestActionDestroy,
    consume: ItemStackRequestActionConsume,
    create: ItemStackRequestActionCreate,
    lab_table_combine,
    beacon_payment: ItemStackRequestActionBeaconPayment,
    mine_block: ItemStackRequestActionMineBlock,
    craft_recipe: ItemStackRequestActionCraftRecipe,
    craft_recipe_auto: ItemStackRequestActionCraftRecipeAuto,
    craft_creative: ItemStackRequestActionCraftCreative,
    optional: ItemStackRequestActionOptional,
    grindstone: ItemStackRequestActionGrindstone,
    loom: ItemStackRequestActionLoom,
    craft_non_implemented,
    craft_results_deprecated: ItemStackRequestActionCraftResultsDeprecated,
};

pub const ItemStackRequest = struct {
    request_id: i32,
    actions: []const ItemStackRequestAction,
    filter_strings: []const []const u8,
    filter_cause: i32,
};

pub const SItemStackRequest = struct {
    requests: []const ItemStackRequest,
};

pub const SPlayerAuthInput = struct {
    pitch: f32,
    yaw: f32,
    position: struct { f64, f64, f64 },
    move_vec: struct { f64, f64 },
    head_yaw: f32,
    input_data: []const i64,
    input_mode: i32,
    play_mode: i32,
    interaction_model: i32,
    interact_pitch: f32,
    interact_yaw: f32,
    tick: i64,
    delta: struct { f64, f64, f64 },
    block_actions: ?[]const PlayerBlockAction,
    item_interaction: ?PlayerInventoryAction,
    item_stack_request: ?ItemStackRequest,
    vehicle_rotation: ?struct { f64, f64 },
    vehicle_unique_id: ?i64,
    analog_move: struct { f64, f64 },
    camera_orientation: struct { f64, f64, f64 },
    raw_move: struct { f64, f64 },
};

pub const CInventoryContent = struct {
    container_id: i32,
    slots: []const NetworkItemStackDescriptor,
    full_container_name: FullContainerName,
    storage_item: NetworkItemStackDescriptor,
};

pub const CInventorySlot = struct {
    container_id: i32,
    slot: i32,
    full_container_name: ?FullContainerName,
    storage_item: ?NetworkItemStackDescriptor,
    item: NetworkItemStackDescriptor,
};

pub const ItemStackResponseContainerInfo = struct {
    full_container_name: FullContainerName,
    slots: []const ItemStackResponseSlotInfo,
};

pub const ItemStackResponseInfo = struct {
    result: u8,
    client_request_id: i32,
    containers: []const ItemStackResponseContainerInfo,
};

pub const CItemStackResponse = struct {
    responses: []const ItemStackResponseInfo,
};

pub const NetworkItemStack = struct {
    id: i32,
    count: i32,
    aux_value: i32,
    block_runtime_id: i32,
    extra_data: []const u8,
};

pub const ServerboundPacket = union(enum) {
    s_actor_event: SActorEvent,
    s_animate: SAnimate,
    s_block_pick_request: SBlockPickRequest,
    s_client_cache_blob_status: SClientCacheBlobStatus,
    s_client_cache_status: SClientCacheStatus,
    s_command_request: SCommandRequest,
    s_container_close: SContainerClose,
    s_emote: SEmote,
    s_emote_list: SEmoteList,
    s_interact: SInteract,
    s_inventory_transaction: SInventoryTransaction,
    s_item_stack_request: SItemStackRequest,
    s_loading_screen: SLoadingScreen,
    s_login: SLogin,
    s_mob_equipment: SMobEquipment,
    s_modal_form_response: SModalFormResponse,
    s_packet_violation_warning: SPacketViolationWarning,
    s_player_action: SPlayerAction,
    s_player_auth_input: SPlayerAuthInput,
    s_player_hotbar: SPlayerHotbar,
    s_request_ability: SRequestAbility,
    s_request_chunk_radius: SRequestChunkRadius,
    s_request_network_settings: SRequestNetworkSettings,
    s_resource_pack_client_response: SResourcePackClientResponse,
    s_respawn: SRespawn,
    s_set_local_player_as_initialized: SSetLocalPlayerAsInitialized,
    s_set_player_inventory_options: SSetPlayerInventoryOptions,
    s_text: SText,
    unknown,
};

pub const ClientboundPacket = union(enum) {
    c_add_actor: CAddActor,
    c_add_item_actor: CAddItemActor,
    c_add_player: CAddPlayer,
    c_available_commands: CAvailableCommands,
    c_biome_definition_list,
    c_block_actor_data: CBlockActorData,
    c_block_event: CBlockEvent,
    c_boss_event: CBossEvent,
    c_change_dimension: CChangeDimension,
    c_chunk_radius_updated: CChunkRadiusUpdated,
    c_client_cache_miss_response: CClientCacheMissResponse,
    c_container_open: CContainerOpen,
    c_correct_player_move_prediction: CCorrectPlayerMovePrediction,
    c_crafting_data: CCraftingData,
    c_creative_content: CCreativeContent,
    c_disconnect: CDisconnect,
    c_gamerules_changed: CGamerulesChanged,
    c_inventory_content: CInventoryContent,
    c_inventory_slot: CInventorySlot,
    c_item_registry: CItemRegistry,
    c_item_stack_response: CItemStackResponse,
    c_jigsaw_structure_data,
    c_level_event: CLevelEvent,
    c_level_sound_event: CLevelSoundEvent,
    c_mob_effect: CMobEffect,
    c_mob_equipment: CMobEquipment,
    c_modal_form_request: CModalFormRequest,
    c_move_actor_absolute: CMoveActorAbsolute,
    c_move_actor_delta: CMoveActorDelta,
    c_move_player: CMovePlayer,
    c_network_chunk_publisher_update: CNetworkChunkPublisherUpdate,
    c_network_settings: CNetworkSettings,
    c_play_status: CPlayStatus,
    c_player_hotbar: CPlayerHotbar,
    c_player_list: CPlayerList,
    c_remove_actor: CRemoveActor,
    c_remove_objective: CRemoveObjective,
    c_resource_pack_stack_packet: CResourcePackStackPacket,
    c_resource_packs_info: CResourcePacksInfo,
    c_set_actor_data: CSetActorData,
    c_set_actor_link: CSetActorLink,
    c_set_actor_motion: CSetActorMotion,
    c_set_difficulty: CSetDifficulty,
    c_set_display_objective: CSetDisplayObjective,
    c_set_health: CSetHealth,
    c_set_player_game_type: CSetPlayerGameType,
    c_set_score: CSetScore,
    c_set_spawn_position: CSetSpawnPosition,
    c_set_time: CSetTime,
    c_set_title: CSetTitle,
    c_show_credits: CShowCredits,
    c_start_game: CStartGame,
    c_take_item_actor: CTakeItemActor,
    c_transfer: CTransfer,
    c_update_abilities: CUpdateAbilities,
    c_update_attributes: CUpdateAttributes,
    c_update_block: CUpdateBlock,
    c_update_trade: CUpdateTrade,
    c_voxel_shapes,
    unknown,
};
