// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const server = @import("server.zig");
const event = @import("event.zig");
const command = @import("command.zig");
const permission = @import("permission.zig");

pub const Server = server.Server;
pub const EventType = event.EventType;
pub const EventPriority = event.EventPriority;
pub const Command = command.Command;
pub const Permission = permission.Permission;

/// Verified marketplace metadata for signed plugins.
pub const MarketplaceMetadata = struct {
    /// The marketplace base URL where this plugin is registered.
    marketplace_url: []const u8,
    /// The unique plugin ID on the marketplace.
    plugin_id: i64,
    /// The canonical plugin name.
    plugin_name: []const u8,
    /// The semver version string of the plugin.
    version: []const u8,
    /// Developer ID.
    dev_id: i64,
    /// Developer display name or username.
    dev_name: []const u8,
    /// Whether this is a paid marketplace plugin.
    is_paid: bool,
    /// The buyer / licensee user ID (0 for free/open-source).
    user_id: i64,
    /// Unique license key issued to the buyer, if paid.
    license_key: ?[]const u8,
    /// ISO-8601 timestamp of when this binary/license was issued.
    issued_at: []const u8,
};

/// A contextual handle for plugin-related operations.
pub const Context = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]context";

    /// Registers a handler for a specific event.
    ///
    /// * `handler-id`: Unique ID for the event handler.
    /// * `event-type`: The type of event to listen for.
    /// * `event-priority`: When this handler should be called relative to others.
    /// * `blocking`: Whether the event should wait for this handler to finish.
    pub fn registerEvent(self: Context, handler_id: u32, event_type: EventType, event_priority: EventPriority, blocking: bool) void {
        return abi.call(raw.@"[method]context.register-event", void, .{ abi.borrow(self), handler_id, event_type, event_priority, blocking });
    }

    /// Registers a new command.
    ///
    /// * `command`: The command definition.
    /// * `permission`: The required permission node to execute this command.
    ///
    /// Consumes `command_`.
    pub fn registerCommand(self: Context, command_: Command, permission_: []const u8) void {
        return abi.call(raw.@"[method]context.register-command", void, .{ abi.borrow(self), command_, permission_ });
    }

    /// Registers a permission node with the server.
    pub fn registerPermission(self: Context, permission_: Permission) abi.Result(void, []const u8) {
        return abi.call(raw.@"[method]context.register-permission", abi.Result(void, []const u8), .{ abi.borrow(self), permission_ });
    }

    /// Returns the path to the plugin's private data folder.
    pub fn getDataFolder(self: Context) []const u8 {
        return abi.call(raw.@"[method]context.get-data-folder", []const u8, .{abi.borrow(self)});
    }

    /// Returns the global server instance.
    pub fn getServer(self: Context) Server {
        return abi.call(raw.@"[method]context.get-server", Server, .{abi.borrow(self)});
    }

    /// Returns verified marketplace metadata if this plugin binary is signed, or none if unsigned.
    pub fn getMarketplaceMetadata(self: Context) ?MarketplaceMetadata {
        return abi.call(raw.@"[method]context.get-marketplace-metadata", ?MarketplaceMetadata, .{abi.borrow(self)});
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: Context) void {
        abi.keep(Context, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: Context) void {
        abi.drop(Context, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/context@0.1.0" fn @"[method]context.register-event"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/context@0.1.0" fn @"[method]context.register-command"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/context@0.1.0" fn @"[method]context.register-permission"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/context@0.1.0" fn @"[method]context.get-data-folder"(i32, i32) void;
    extern "pumpkin:plugin/context@0.1.0" fn @"[method]context.get-server"(i32) i32;
    extern "pumpkin:plugin/context@0.1.0" fn @"[method]context.get-marketplace-metadata"(i32, i32) void;
    extern "pumpkin:plugin/context@0.1.0" fn @"[resource-drop]context"(i32) void;
};
