// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");

/// Information about a discovered or loaded datapack.
pub const DatapackInfo = struct {
    id: []const u8,
    name: []const u8,
    description: []const u8,
    pack_format: u32,
    is_enabled: bool,
    recipe_count: u32,
    function_count: u32,
};

/// Position options for enabling a datapack relative to other packs.
pub const EnablePosition = union(enum) {
    first,
    last,
    before: []const u8,
    after: []const u8,
};

/// Global manager for inspecting and controlling server datapacks.
pub const DatapackManager = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]datapack-manager";

    /// Returns all known datapacks (both enabled and available/disabled).
    pub fn listAllPacks(self: DatapackManager) []const DatapackInfo {
        return abi.call(raw.@"[method]datapack-manager.list-all-packs", []const DatapackInfo, .{abi.borrow(self)});
    }

    /// Returns only currently enabled datapacks.
    pub fn listEnabledPacks(self: DatapackManager) []const DatapackInfo {
        return abi.call(raw.@"[method]datapack-manager.list-enabled-packs", []const DatapackInfo, .{abi.borrow(self)});
    }

    /// Returns available (disabled) datapacks.
    pub fn listAvailablePacks(self: DatapackManager) []const DatapackInfo {
        return abi.call(raw.@"[method]datapack-manager.list-available-packs", []const DatapackInfo, .{abi.borrow(self)});
    }

    /// Retrieves details about a specific datapack by name or ID.
    pub fn getPack(self: DatapackManager, name: []const u8) ?DatapackInfo {
        return abi.call(raw.@"[method]datapack-manager.get-pack", ?DatapackInfo, .{ abi.borrow(self), name });
    }

    /// Checks if a datapack is currently enabled.
    pub fn isEnabled(self: DatapackManager, name: []const u8) bool {
        return abi.call(raw.@"[method]datapack-manager.is-enabled", bool, .{ abi.borrow(self), name });
    }

    /// Enables a datapack with a specific priority position.
    pub fn enablePack(self: DatapackManager, name: []const u8, position: EnablePosition) abi.Result(void, []const u8) {
        return abi.call(raw.@"[method]datapack-manager.enable-pack", abi.Result(void, []const u8), .{ abi.borrow(self), name, position });
    }

    /// Disables an enabled datapack.
    pub fn disablePack(self: DatapackManager, name: []const u8) abi.Result(void, []const u8) {
        return abi.call(raw.@"[method]datapack-manager.disable-pack", abi.Result(void, []const u8), .{ abi.borrow(self), name });
    }

    /// Reloads all enabled datapacks, recipes, and function tags,
    /// synchronizes recipes with online players, and triggers `#minecraft:load`.
    pub fn reload(self: DatapackManager) abi.Result(void, []const u8) {
        return abi.call(raw.@"[method]datapack-manager.reload", abi.Result(void, []const u8), .{abi.borrow(self)});
    }

    /// Executes a datapack function or function tag (e.g. "namespace:fn" or "#namespace:tag").
    /// Returns the number of commands executed.
    pub fn executeFunction(self: DatapackManager, name: []const u8) abi.Result(u32, []const u8) {
        return abi.call(raw.@"[method]datapack-manager.execute-function", abi.Result(u32, []const u8), .{ abi.borrow(self), name });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: DatapackManager) void {
        abi.keep(DatapackManager, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: DatapackManager) void {
        abi.drop(DatapackManager, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.list-all-packs"(i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.list-enabled-packs"(i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.list-available-packs"(i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.get-pack"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.is-enabled"(i32, i32, i32) i32;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.enable-pack"(i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.disable-pack"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.reload"(i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[method]datapack-manager.execute-function"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/datapack@0.1.0" fn @"[resource-drop]datapack-manager"(i32) void;
};
