// Generated by tools/gen.zig, do not edit.

const common = @import("common.zig");
const item_stack = @import("item_stack.zig");
const enchantments = @import("enchantments.zig");
const damage_types = @import("damage_types.zig");
const screens = @import("screens.zig");
const player = @import("player.zig");
const text = @import("text.zig");
const world = @import("world.zig");
const java_packets = @import("java_packets.zig");
const bedrock_packets = @import("bedrock_packets.zig");
const uuid = @import("uuid.zig");
const java_dialogs = @import("java_dialogs.zig");

pub const BlockPos = common.BlockPos;
pub const GameMode = common.GameMode;
pub const Hand = common.Hand;
pub const Position = common.Position;
pub const ClickType = common.ClickType;
pub const ItemStack = item_stack.ItemStack;
pub const Enchantment = enchantments.Enchantment;
pub const DamageType = damage_types.DamageType;
pub const Screen = screens.Screen;
pub const Player = player.Player;
pub const TextComponent = text.TextComponent;
pub const World = world.World;
pub const JavaServerboundPacket = java_packets.ServerboundPacket;
pub const JavaClientboundPacket = java_packets.ClientboundPacket;
pub const BedrockServerboundPacket = bedrock_packets.ServerboundPacket;
pub const BedrockClientboundPacket = bedrock_packets.ClientboundPacket;
pub const Uuid = uuid.Uuid;
pub const Dialog = java_dialogs.Dialog;

pub const ServerboundPacket = union(enum) {
    java: JavaServerboundPacket,
    bedrock: BedrockServerboundPacket,
    unknown,
};

pub const ClientboundPacket = union(enum) {
    java: JavaClientboundPacket,
    bedrock: BedrockClientboundPacket,
    unknown,
};

pub const EventPriority = enum(u8) {
    highest,
    high,
    normal,
    low,
    lowest,
};

pub const PlayerJoinEventData = struct {
    player: Player,
    join_message: TextComponent,
    cancelled: bool,
};

pub const PlayerLeaveEventData = struct {
    player: Player,
    leave_message: TextComponent,
    cancelled: bool,
};

pub const PlayerLoginEventData = struct {
    player: Player,
    kick_message: TextComponent,
    cancelled: bool,
};

pub const PlayerChatEventData = struct {
    player: Player,
    message: []const u8,
    recipients: []const Player,
    signature: ?[]const u8,
    cancelled: bool,
};

pub const PlayerCommandSendEventData = struct {
    player: Player,
    command: []const u8,
    cancelled: bool,
};

pub const PlayerPermissionCheckEventData = struct {
    player: Player,
    permission: []const u8,
    permission_result: bool,
};

pub const PlayerMoveEventData = struct {
    player: Player,
    from_position: Position,
    to_position: Position,
    cancelled: bool,
};

pub const PlayerTeleportEventData = struct {
    player: Player,
    from_position: Position,
    to_position: Position,
    cancelled: bool,
};

pub const PlayerChangeWorldEventData = struct {
    player: Player,
    previous_world: World,
    new_world: World,
    position: Position,
    yaw: f32,
    pitch: f32,
    cancelled: bool,
};

pub const PlayerRespawnEventData = struct {
    player: Player,
    previous_world: World,
    respawned_world: World,
    position: Position,
    yaw: f32,
    pitch: f32,
    alive: bool,
};

pub const PlayerExpChangeEventData = struct {
    player: Player,
    amount: i32,
};

pub const PlayerItemHeldEventData = struct {
    player: Player,
    previous_slot: u8,
    new_slot: u8,
    cancelled: bool,
};

pub const PlayerChangedMainHandEventData = struct {
    player: Player,
    main_hand: Hand,
};

pub const PlayerGamemodeChangeEventData = struct {
    player: Player,
    previous_gamemode: GameMode,
    new_gamemode: GameMode,
    cancelled: bool,
};

pub const PlayerCustomPayloadEventData = struct {
    player: Player,
    channel: []const u8,
    data: []const u8,
};

pub const PlayerFishState = enum(u8) {
    fishing,
    caught_fish,
    caught_entity,
    in_ground,
    failed_attempt,
    reel_in,
    bite,
};

pub const PlayerFishEventData = struct {
    player: Player,
    caught_uuid: ?Uuid,
    caught_type: []const u8,
    hook_uuid: Uuid,
    state: PlayerFishState,
    hand: Hand,
    exp_to_drop: i32,
    cancelled: bool,
};

pub const PlayerEggThrowEventData = struct {
    player: Player,
    egg_uuid: Uuid,
    hatching: bool,
    num_hatches: u8,
    hatching_type: []const u8,
    cancelled: bool,
};

pub const EntityInteractionAction = enum(u8) {
    interact,
    attack,
    interact_at,
};

pub const InteractAction = enum(u8) {
    left_click_block,
    left_click_air,
    right_click_air,
    right_click_block,
};

pub const PlayerInteractEventData = struct {
    player: Player,
    action: InteractAction,
    clicked_pos: ?BlockPos,
    block: []const u8,
    cancelled: bool,
};

pub const PlayerToggleSneakEventData = struct {
    player: Player,
    is_sneaking: bool,
    cancelled: bool,
};

pub const PlayerToggleFlightEventData = struct {
    player: Player,
    is_flying: bool,
    cancelled: bool,
};

pub const PlayerToggleSprintEventData = struct {
    player: Player,
    is_sprinting: bool,
    cancelled: bool,
};

pub const PlayerInteractUnknownEntityEventData = struct {
    player: Player,
    entity_id: i32,
    action: EntityInteractionAction,
    cancelled: bool,
};

pub const InventoryClickEventData = struct {
    player: Player,
    window_type: ?Screen,
    click_type: ClickType,
    slot: i16,
    raw_slot: i16,
    clicked_item: ?ItemStack,
    cursor: ?ItemStack,
    hotbar_button: i32,
    cancelled: bool,
};

pub const InventoryCloseEventData = struct {
    player: Player,
    window_type: ?Screen,
};

pub const BlockRedstoneEventData = struct {
    target_world: World,
    state_id: u16,
    block_pos: BlockPos,
    old_current: i32,
    new_current: i32,
    cancelled: bool,
};

pub const BlockBreakEventData = struct {
    player: ?Player,
    block: []const u8,
    block_pos: BlockPos,
    exp: u32,
    should_drop: bool,
    cancelled: bool,
};

pub const BlockBurnEventData = struct {
    igniting_block: []const u8,
    block: []const u8,
    cancelled: bool,
};

pub const BlockCanBuildEventData = struct {
    block_to_build: []const u8,
    buildable: bool,
    player: Player,
    block: []const u8,
    cancelled: bool,
};

pub const BlockGrowEventData = struct {
    target_world: World,
    old_block: []const u8,
    old_state_id: u16,
    new_block: []const u8,
    new_state_id: u16,
    block_pos: BlockPos,
    cancelled: bool,
};

pub const BlockPlaceEventData = struct {
    player: Player,
    block_placed: []const u8,
    block_placed_against: []const u8,
    block_pos: BlockPos,
    can_build: bool,
    cancelled: bool,
};

pub const BedrockFormResponseEventData = struct {
    player: Player,
    form_id: u32,
    response_data: ?[]const u8,
};

pub const DialogClickActionEventData = struct {
    player: Player,
    id: []const u8,
    payload: ?[]const u8,
    cancelled: bool,
};

pub const DialogShowEventData = struct {
    player: Player,
    dialog: Dialog,
    cancelled: bool,
};

pub const DialogClearEventData = struct {
    player: Player,
    cancelled: bool,
};

pub const ServerCommandEventData = struct {
    command: []const u8,
    cancelled: bool,
};

pub const ServerListPingAddress = struct {
    host: []const u8,
    port: u16,
};

pub const ServerListPingEventData = struct {
    hostname: []const u8,
    address: ServerListPingAddress,
    motd: TextComponent,
    max_players: u32,
    num_players: u32,
    favicon: ?[]const u8,
};

pub const ServerLoadType = enum(u8) {
    startup,
    reload,
};

pub const ServerLoadEventData = struct {
    load_type: ServerLoadType,
};

pub const SpawnChangeEventData = struct {
    target_world: World,
    previous_position: BlockPos,
    previous_yaw: f32,
    previous_pitch: f32,
    new_position: BlockPos,
    new_yaw: f32,
    new_pitch: f32,
};

pub const ServerBroadcastEventData = struct {
    message: TextComponent,
    sender: TextComponent,
    cancelled: bool,
};

pub const ServerTickStartEventData = struct {
    tick: i32,
};

pub const ServerTickEndEventData = struct {
    tick: i32,
    duration_nanos: i64,
};

pub const PacketReceivedEventData = struct {
    player: Player,
    packet: ServerboundPacket,
    packet_id: i32,
    raw_payload: []const u8,
    cancelled: bool,
};

pub const PacketSentEventData = struct {
    player: Player,
    packet: ClientboundPacket,
    packet_id: i32,
    raw_payload: []const u8,
    cancelled: bool,
};

pub const PlayerInteractEntityEventData = struct {
    player: Player,
    entity_id: i32,
    action: EntityInteractionAction,
    sneaking: bool,
    cancelled: bool,
};

pub const ChunkLoadEventData = struct {
    target_world: World,
    chunk_x: i32,
    chunk_z: i32,
    cancelled: bool,
};

pub const ChunkSaveEventData = struct {
    target_world: World,
    chunk_x: i32,
    chunk_z: i32,
    cancelled: bool,
};

pub const ChunkSendEventData = struct {
    target_world: World,
    chunk_x: i32,
    chunk_z: i32,
    cancelled: bool,
};

pub const EntityDamageEventData = struct {
    entity_id: i32,
    damage: f32,
    damage_type: DamageType,
    cancelled: bool,
};

pub const EntityDeathEventData = struct {
    entity_id: i32,
    dropped_exp: i32,
};

pub const PlayerDeathEventData = struct {
    player: Player,
    death_message: TextComponent,
    dropped_exp: i32,
    keep_inventory: bool,
    cancelled: bool,
};

pub const EntitySpawnEventData = struct {
    entity_id: i32,
    entity_type: []const u8,
    position: Position,
    target_world: World,
    cancelled: bool,
};

pub const EntityCombustEventData = struct {
    entity_id: i32,
    duration_secs: f32,
    cancelled: bool,
};

pub const EntityRegainHealthEventData = struct {
    entity_id: i32,
    amount: f32,
    cancelled: bool,
};

pub const EntityAirChangeEventData = struct {
    entity_id: i32,
    amount: i32,
    cancelled: bool,
};

pub const EntityBreedEventData = struct {
    father_id: i32,
    mother_id: i32,
    child_id: i32,
    cancelled: bool,
};

pub const EntityDismountEventData = struct {
    entity_id: i32,
    dismounted_id: i32,
    cancelled: bool,
};

pub const EntityDyeEventData = struct {
    entity_id: i32,
    color: []const u8,
    player: ?Player,
    cancelled: bool,
};

pub const EntityEnterLoveModeEventData = struct {
    entity_id: i32,
    human_entity_id: ?i32,
    ticks_in_love: i32,
    cancelled: bool,
};

pub const EntityExplodeEventData = struct {
    entity_id: i32,
    position: Position,
    yield_rate: f32,
    cancelled: bool,
};

pub const EntityMountEventData = struct {
    entity_id: i32,
    mounted_id: i32,
    cancelled: bool,
};

pub const EntityPickupItemEventData = struct {
    entity_id: i32,
    item_name: []const u8,
    count: u8,
    cancelled: bool,
};

pub const EntityPortalEventData = struct {
    entity_id: i32,
    portal_pos: BlockPos,
    cancelled: bool,
};

pub const EntityResurrectEventData = struct {
    entity_id: i32,
    cancelled: bool,
};

pub const EntityShootBowEventData = struct {
    entity_id: i32,
    weapon_name: []const u8,
    force: f32,
    cancelled: bool,
};

pub const EntityTameEventData = struct {
    entity_id: i32,
    owner: Player,
    cancelled: bool,
};

pub const EntityTargetEventData = struct {
    entity_id: i32,
    target_id: ?i32,
    cancelled: bool,
};

pub const EntityTeleportEventData = struct {
    entity_id: i32,
    from_position: Position,
    to_position: Position,
    cancelled: bool,
};

pub const EntityToggleGlideEventData = struct {
    entity_id: i32,
    is_gliding: bool,
    cancelled: bool,
};

pub const EntityTransformEventData = struct {
    entity_id: i32,
    new_entity_id: i32,
    transform_reason: []const u8,
    cancelled: bool,
};

pub const CreatureSpawnEventData = struct {
    entity_id: i32,
    entity_type: []const u8,
    position: Position,
    target_world: World,
    spawn_reason: []const u8,
    cancelled: bool,
};

pub const EnderDragonChangePhaseEventData = struct {
    entity_id: i32,
    current_phase: []const u8,
    new_phase: []const u8,
    cancelled: bool,
};

pub const EntityBreakDoorEventData = struct {
    entity_id: i32,
    block_pos: BlockPos,
    cancelled: bool,
};

pub const EntityChangeBlockEventData = struct {
    entity_id: i32,
    block_pos: BlockPos,
    new_block: []const u8,
    cancelled: bool,
};

pub const EntityDamageByBlockEventData = struct {
    entity_id: i32,
    damager_pos: ?BlockPos,
    damage: f32,
    cause: []const u8,
    cancelled: bool,
};

pub const EntityDamageByEntityEventData = struct {
    entity_id: i32,
    damager_id: i32,
    damage: f32,
    cause: []const u8,
    cancelled: bool,
};

pub const EntityDropItemEventData = struct {
    entity_id: i32,
    item_name: []const u8,
    count: u8,
    cancelled: bool,
};

pub const EntityEnterBlockEventData = struct {
    entity_id: i32,
    block_pos: BlockPos,
    cancelled: bool,
};

pub const EntityExhaustionEventData = struct {
    entity_id: i32,
    exhaustion: f32,
    cancelled: bool,
};

pub const EntityInteractEventData = struct {
    entity_id: i32,
    block_pos: BlockPos,
    cancelled: bool,
};

pub const EntityKnockbackEventData = struct {
    entity_id: i32,
    hit_by_id: ?i32,
    knockback: Position,
    cancelled: bool,
};

pub const EntityPlaceEventData = struct {
    entity_id: i32,
    block_pos: BlockPos,
    block_name: []const u8,
    cancelled: bool,
};

pub const EntityPoseChangeEventData = struct {
    entity_id: i32,
    pose: []const u8,
    cancelled: bool,
};

pub const EntityPotionEffectEventData = struct {
    entity_id: i32,
    effect_name: []const u8,
    duration: i32,
    amplifier: u8,
    cancelled: bool,
};

pub const EntitySpellCastEventData = struct {
    entity_id: i32,
    spell: []const u8,
    cancelled: bool,
};

pub const EntityTargetLivingEntityEventData = struct {
    entity_id: i32,
    target_id: ?i32,
    reason: []const u8,
    cancelled: bool,
};

pub const EntityToggleSwimEventData = struct {
    entity_id: i32,
    is_swimming: bool,
    cancelled: bool,
};

pub const ExplosionPrimeEventData = struct {
    entity_id: i32,
    radius: f32,
    fire: bool,
    cancelled: bool,
};

pub const FireworkExplodeEventData = struct {
    entity_id: i32,
    cancelled: bool,
};

pub const FoodLevelChangeEventData = struct {
    entity_id: i32,
    food_level: u8,
    cancelled: bool,
};

pub const ItemDespawnEventData = struct {
    entity_id: i32,
    cancelled: bool,
};

pub const ItemMergeEventData = struct {
    entity_id: i32,
    target_id: i32,
    cancelled: bool,
};

pub const ItemSpawnEventData = struct {
    entity_id: i32,
    position: Position,
    item_name: []const u8,
    cancelled: bool,
};

pub const PiglinBarterEventData = struct {
    entity_id: i32,
    input_item: ItemStack,
    outcome: []const ItemStack,
    cancelled: bool,
};

pub const ProjectileHitEventData = struct {
    entity_id: i32,
    hit_position: Position,
    hit_entity_id: ?i32,
    cancelled: bool,
};

pub const ProjectileLaunchEventData = struct {
    entity_id: i32,
    shooter_id: ?i32,
    cancelled: bool,
};

pub const SheepDyeWoolEventData = struct {
    entity_id: i32,
    dye_color: u8,
    player_id: ?i32,
    cancelled: bool,
};

pub const SheepRegrowWoolEventData = struct {
    entity_id: i32,
    cancelled: bool,
};

pub const SlimeSplitEventData = struct {
    entity_id: i32,
    count: i32,
    cancelled: bool,
};

pub const StriderTemperatureChangeEventData = struct {
    entity_id: i32,
    is_shivering: bool,
    cancelled: bool,
};

pub const VillagerAcquireTradeEventData = struct {
    entity_id: i32,
    recipe_index: i32,
    cancelled: bool,
};

pub const VillagerCareerChangeEventData = struct {
    entity_id: i32,
    profession: []const u8,
    reason: []const u8,
    cancelled: bool,
};

pub const VillagerReplenishTradeEventData = struct {
    entity_id: i32,
    restock_quantity: i32,
    cancelled: bool,
};

pub const WardenAngerChangeEventData = struct {
    entity_id: i32,
    target_id: i32,
    old_anger: i32,
    new_anger: i32,
    cancelled: bool,
};

pub const AreaEffectCloudApplyEventData = struct {
    entity_id: i32,
    affected_entities: []const i32,
    cancelled: bool,
};

pub const ArrowBodyCountChangeEventData = struct {
    entity_id: i32,
    old_amount: u32,
    new_amount: u32,
    cancelled: bool,
};

pub const BatToggleSleepEventData = struct {
    entity_id: i32,
    is_awake: bool,
    cancelled: bool,
};

pub const CreeperPowerEventData = struct {
    entity_id: i32,
    lightning_id: ?i32,
    cause: []const u8,
    cancelled: bool,
};

pub const EntityCombustByBlockEventData = struct {
    entity_id: i32,
    combuster: BlockPos,
    duration: f32,
    cancelled: bool,
};

pub const EntityCombustByEntityEventData = struct {
    entity_id: i32,
    combuster_id: i32,
    duration: f32,
    cancelled: bool,
};

pub const EntityKnockbackByEntityEventData = struct {
    entity_id: i32,
    hit_by_id: i32,
    force: f64,
    x: f64,
    z: f64,
    cancelled: bool,
};

pub const EntityPortalEnterEventData = struct {
    entity_id: i32,
    location: BlockPos,
    cancelled: bool,
};

pub const EntityPortalExitEventData = struct {
    entity_id: i32,
    from_pos: BlockPos,
    to_pos: ?BlockPos,
    cancelled: bool,
};

pub const EntityRemoveEventData = struct {
    entity_id: i32,
    cause: []const u8,
    cancelled: bool,
};

pub const EntityTargetBlockEventData = struct {
    entity_id: i32,
    block_pos: BlockPos,
    cancelled: bool,
};

pub const EntityUnleashEventData = struct {
    entity_id: i32,
    reason: []const u8,
    cancelled: bool,
};

pub const ExpBottleEventData = struct {
    entity_id: i32,
    experience: i32,
    location: BlockPos,
    show_effect: bool,
    cancelled: bool,
};

pub const HorseJumpEventData = struct {
    entity_id: i32,
    power: f32,
    cancelled: bool,
};

pub const LingeringPotionSplashEventData = struct {
    entity_id: i32,
    location: BlockPos,
    potion_item: []const u8,
    cancelled: bool,
};

pub const PigZapEventData = struct {
    entity_id: i32,
    lightning_id: i32,
    pig_zombie_id: i32,
    cancelled: bool,
};

pub const PigZombieAngerEventData = struct {
    entity_id: i32,
    target_id: ?i32,
    new_anger: i32,
    cancelled: bool,
};

pub const PotionSplashEventData = struct {
    entity_id: i32,
    location: BlockPos,
    potion_item: []const u8,
    affected_entities: []const i32,
    cancelled: bool,
};

pub const SpawnerSpawnEventData = struct {
    entity_id: i32,
    spawner_pos: BlockPos,
    cancelled: bool,
};

pub const TrialSpawnerSpawnEventData = struct {
    entity_id: i32,
    spawner_pos: BlockPos,
    cancelled: bool,
};

pub const VillagerReputationChangeEventData = struct {
    entity_id: i32,
    target_id: i32,
    reputation_change: i32,
    cancelled: bool,
};

pub const PlayerItemConsumeEventData = struct {
    player: Player,
    item_name: []const u8,
    cancelled: bool,
};

pub const PlayerItemDamageEventData = struct {
    player: Player,
    item_name: []const u8,
    damage: i32,
    cancelled: bool,
};

pub const PlayerDropItemEventData = struct {
    player: Player,
    item_name: []const u8,
    count: u8,
    cancelled: bool,
};

pub const PlayerBedEnterEventData = struct {
    player: Player,
    bed_pos: BlockPos,
    cancelled: bool,
};

pub const PlayerBedLeaveEventData = struct {
    player: Player,
    bed_pos: BlockPos,
};

pub const PlayerBucketEmptyEventData = struct {
    player: Player,
    block_pos: BlockPos,
    bucket: []const u8,
    cancelled: bool,
};

pub const PlayerBucketFillEventData = struct {
    player: Player,
    block_pos: BlockPos,
    bucket: []const u8,
    cancelled: bool,
};

pub const AsyncPlayerChatEventData = struct {
    player: Player,
    message: []const u8,
    format: TextComponent,
    cancelled: bool,
};

pub const AsyncPlayerPreLoginEventData = struct {
    player_name: []const u8,
    player_uuid: []const u8,
    ip_address: []const u8,
    kick_message: TextComponent,
    cancelled: bool,
};

pub const PlayerAdvancementDoneEventData = struct {
    player: Player,
    advancement_id: []const u8,
    cancelled: bool,
};

pub const PlayerAnimationEventData = struct {
    player: Player,
    animation_type: []const u8,
    cancelled: bool,
};

pub const PlayerArmorStandManipulateEventData = struct {
    player: Player,
    armor_stand_id: i32,
    slot: u8,
    cancelled: bool,
};

pub const PlayerBucketEntityEventData = struct {
    player: Player,
    entity_id: i32,
    bucket_item: []const u8,
    cancelled: bool,
};

pub const PlayerChangedWorldEventData = struct {
    player: Player,
    from_world: World,
    to_world: World,
    cancelled: bool,
};

pub const PlayerChannelEventData = struct {
    player: Player,
    channel: []const u8,
    cancelled: bool,
};

pub const PlayerCommandPreprocessEventData = struct {
    player: Player,
    command: []const u8,
    cancelled: bool,
};

pub const PlayerEditBookEventData = struct {
    player: Player,
    slot: u32,
    pages: []const []const u8,
    title: ?[]const u8,
    signing: bool,
    cancelled: bool,
};

pub const PlayerElytraBoostEventData = struct {
    player: Player,
    firework_id: i32,
    cancelled: bool,
};

pub const PlayerExpCooldownChangeEventData = struct {
    player: Player,
    new_cooldown: i32,
    cancelled: bool,
};

pub const PlayerHarvestBlockEventData = struct {
    player: Player,
    block_pos: BlockPos,
    harvested_items: []const ItemStack,
    cancelled: bool,
};

pub const PlayerHideEntityEventData = struct {
    player: Player,
    entity_id: i32,
    cancelled: bool,
};

pub const PlayerItemBreakEventData = struct {
    player: Player,
    item_name: []const u8,
};

pub const PlayerItemMendEventData = struct {
    player: Player,
    item_name: []const u8,
    repair_amount: i32,
    exp_consumed: i32,
    cancelled: bool,
};

pub const PlayerKickEventData = struct {
    player: Player,
    reason: []const u8,
    cancelled: bool,
};

pub const PlayerLeashEntityEventData = struct {
    player: Player,
    entity_id: i32,
    holder_id: i32,
    cancelled: bool,
};

pub const PlayerLevelChangeEventData = struct {
    player: Player,
    old_level: i32,
    new_level: i32,
};

pub const PlayerLocaleChangeEventData = struct {
    player: Player,
    new_locale: []const u8,
    cancelled: bool,
};

pub const PlayerNameEntityEventData = struct {
    player: Player,
    entity_id: i32,
    name: TextComponent,
    cancelled: bool,
};

pub const PlayerOpenSignEventData = struct {
    player: Player,
    block_pos: BlockPos,
    is_front: bool,
    cancelled: bool,
};

pub const PlayerPortalEventData = struct {
    player: Player,
    from_pos: BlockPos,
    to_pos: ?BlockPos,
    cancelled: bool,
};

pub const PlayerPreLoginEventData = struct {
    player_name: []const u8,
    player_uuid: []const u8,
    ip_address: []const u8,
    kick_message: TextComponent,
    cancelled: bool,
};

pub const PlayerRiptideEventData = struct {
    player: Player,
    item_name: []const u8,
    cancelled: bool,
};

pub const PlayerShearEntityEventData = struct {
    player: Player,
    entity_id: i32,
    hand: u8,
    cancelled: bool,
};

pub const PlayerShowEntityEventData = struct {
    player: Player,
    entity_id: i32,
    cancelled: bool,
};

pub const PlayerSpawnChangeEventData = struct {
    player: Player,
    new_spawn: ?BlockPos,
    forced: bool,
    cancelled: bool,
};

pub const PlayerStatisticIncrementEventData = struct {
    player: Player,
    statistic_id: []const u8,
    amount: i32,
    cancelled: bool,
};

pub const PlayerSwapHandsEventData = struct {
    player: Player,
    cancelled: bool,
};

pub const PlayerTakeLecternBookEventData = struct {
    player: Player,
    block_pos: BlockPos,
    book: ItemStack,
    cancelled: bool,
};

pub const PlayerUnleashEntityEventData = struct {
    player: Player,
    entity_id: i32,
    cancelled: bool,
};

pub const PlayerVelocityEventData = struct {
    player: Player,
    velocity: Position,
    cancelled: bool,
};

pub const PlayerInputEventData = struct {
    player: Player,
    input: []const u8,
    cancelled: bool,
};

pub const PlayerInteractAtEntityEventData = struct {
    player: Player,
    entity_id: i32,
    clicked_x: f64,
    clicked_y: f64,
    clicked_z: f64,
    hand: u8,
    cancelled: bool,
};

pub const PlayerLinksSendEventData = struct {
    player: Player,
    links: []const []const u8,
    cancelled: bool,
};

pub const PlayerPickupArrowEventData = struct {
    player: Player,
    arrow_id: i32,
    cancelled: bool,
};

pub const PlayerRecipeBookClickEventData = struct {
    player: Player,
    recipe_id: []const u8,
    make_all: bool,
    cancelled: bool,
};

pub const PlayerRecipeBookSettingsChangeEventData = struct {
    player: Player,
    book_type: []const u8,
    is_open: bool,
    is_filtering: bool,
    cancelled: bool,
};

pub const PlayerRecipeDiscoverEventData = struct {
    player: Player,
    recipe_id: []const u8,
    cancelled: bool,
};

pub const PlayerRegisterChannelEventData = struct {
    player: Player,
    channel: []const u8,
    cancelled: bool,
};

pub const PlayerResourcePackStatusEventData = struct {
    player: Player,
    pack_id: []const u8,
    status: []const u8,
    cancelled: bool,
};

pub const PlayerSpawnLocationEventData = struct {
    player: Player,
    spawn_pos: Position,
    cancelled: bool,
};

pub const PlayerUnregisterChannelEventData = struct {
    player: Player,
    channel: []const u8,
    cancelled: bool,
};

pub const RaidFinishEventData = struct {
    victory: bool,
    cancelled: bool,
};

pub const RaidSpawnWaveEventData = struct {
    wave: u32,
    pos: BlockPos,
    cancelled: bool,
};

pub const RaidStopEventData = struct {
    reason: []const u8,
    cancelled: bool,
};

pub const RaidTriggerEventData = struct {
    pos: BlockPos,
    cancelled: bool,
};

pub const BlockDamageEventData = struct {
    player: Player,
    block_pos: BlockPos,
    insta_break: bool,
    cancelled: bool,
};

pub const BlockIgniteEventData = struct {
    block_pos: BlockPos,
    cancelled: bool,
};

pub const BlockFromToEventData = struct {
    from_pos: BlockPos,
    to_pos: BlockPos,
    cancelled: bool,
};

pub const BlockFormEventData = struct {
    block_pos: BlockPos,
    cancelled: bool,
};

pub const BlockFadeEventData = struct {
    block_pos: BlockPos,
    cancelled: bool,
};

pub const BlockDispenseEventData = struct {
    block_pos: BlockPos,
    item_name: []const u8,
    cancelled: bool,
};

pub const BlockExplodeEventData = struct {
    block_pos: BlockPos,
    yield_rate: f32,
    cancelled: bool,
};

pub const BlockPhysicsEventData = struct {
    block_pos: BlockPos,
    changed_pos: BlockPos,
    cancelled: bool,
};

pub const BlockPistonExtendEventData = struct {
    block_pos: BlockPos,
    direction: []const u8,
    cancelled: bool,
};

pub const BlockPistonRetractEventData = struct {
    block_pos: BlockPos,
    direction: []const u8,
    cancelled: bool,
};

pub const NotePlayEventData = struct {
    block_pos: BlockPos,
    instrument: []const u8,
    note: u8,
    cancelled: bool,
};

pub const SignChangeEventData = struct {
    player: Player,
    block_pos: BlockPos,
    lines: []const []const u8,
    cancelled: bool,
};

pub const SpongeAbsorbEventData = struct {
    block_pos: BlockPos,
    cancelled: bool,
};

pub const TntPrimeEventData = struct {
    block_pos: BlockPos,
    prime_reason: []const u8,
    cancelled: bool,
};

pub const MapInitializeEventData = struct {
    map_id: i32,
};

pub const HangingBreakEventData = struct {
    entity_id: i32,
    remover_entity_id: ?i32,
    cancelled: bool,
};

pub const HangingBreakByEntityEventData = struct {
    entity_id: i32,
    remover_entity_id: i32,
    cancelled: bool,
};

pub const HangingPlaceEventData = struct {
    entity_id: i32,
    player: ?Player,
    block_pos: BlockPos,
    block_face: []const u8,
    cancelled: bool,
};

pub const BellResonateEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    cancelled: bool,
};

pub const BellRingEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    entity_id: ?i32,
    direction: ?[]const u8,
    cancelled: bool,
};

pub const BlockBrushEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    player: Player,
    item: ItemStack,
    cancelled: bool,
};

pub const BlockCookEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    source: ItemStack,
    result: ItemStack,
    cancelled: bool,
};

pub const BlockDamageAbortEventData = struct {
    player: Player,
    block_pos: BlockPos,
    target_world: World,
    item_in_hand: ItemStack,
};

pub const BlockDispenseArmorEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    target_entity_id: i32,
    item: ItemStack,
    cancelled: bool,
};

pub const BlockDispenseLootEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    items: []const ItemStack,
    cancelled: bool,
};

pub const BlockDropItemEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    player: ?Player,
    items: []const ItemStack,
    cancelled: bool,
};

pub const BlockExpEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    exp: i32,
};

pub const BlockFertilizeEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    player: ?Player,
    changed_blocks: []const struct { BlockPos, u16 },
    cancelled: bool,
};

pub const BlockMultiPlaceEventData = struct {
    player: Player,
    target_world: World,
    placed_blocks: []const struct { BlockPos, u16 },
    cancelled: bool,
};

pub const BlockReceiveGameEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    game_event: []const u8,
    source_entity_id: ?i32,
    cancelled: bool,
};

pub const BlockShearEntityEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    target_entity_id: i32,
    item: ItemStack,
    cancelled: bool,
};

pub const BlockSpreadEventData = struct {
    source_pos: BlockPos,
    target_pos: BlockPos,
    target_world: World,
    new_state_id: u16,
    cancelled: bool,
};

pub const BrewingStartEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    brewing_time: i32,
    cancelled: bool,
};

pub const CampfireStartEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    item: ItemStack,
    slot: u8,
    cooking_time: i32,
    cancelled: bool,
};

pub const CauldronLevelChangeEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    old_level: i32,
    new_level: i32,
    reason: []const u8,
    entity_id: ?i32,
    cancelled: bool,
};

pub const CrafterCraftEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    result: ItemStack,
    cancelled: bool,
};

pub const EntityBlockFormEventData = struct {
    entity_id: i32,
    block_pos: BlockPos,
    target_world: World,
    new_state_id: u16,
    cancelled: bool,
};

pub const FluidLevelChangeEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    new_state_id: u16,
    cancelled: bool,
};

pub const InventoryBlockStartEventData = struct {
    block_pos: BlockPos,
    target_world: World,
};

pub const LeavesDecayEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    cancelled: bool,
};

pub const MoistureChangeEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    new_moisture: i32,
    cancelled: bool,
};

pub const SculkBloomEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    charge: i32,
    cancelled: bool,
};

pub const VaultDisplayItemEventData = struct {
    block_pos: BlockPos,
    target_world: World,
    item: ItemStack,
    cancelled: bool,
};

pub const WeatherChangeEventData = struct {
    target_world: World,
    to_weather_state: bool,
    cancelled: bool,
};

pub const ThunderChangeEventData = struct {
    target_world: World,
    to_thunder_state: bool,
    cancelled: bool,
};

pub const WorldLoadEventData = struct {
    target_world: World,
};

pub const WorldUnloadEventData = struct {
    target_world: World,
    cancelled: bool,
};

pub const AsyncStructureGenerateEventData = struct {
    world_name: []const u8,
    structure_name: []const u8,
    pos: BlockPos,
    cancelled: bool,
};

pub const AsyncStructureSpawnEventData = struct {
    world_name: []const u8,
    structure_name: []const u8,
    pos: BlockPos,
    cancelled: bool,
};

pub const ChunkPopulateEventData = struct {
    chunk_x: i32,
    chunk_z: i32,
    cancelled: bool,
};

pub const ChunkUnloadEventData = struct {
    chunk_x: i32,
    chunk_z: i32,
    cancelled: bool,
};

pub const EntitiesLoadEventData = struct {
    chunk_x: i32,
    chunk_z: i32,
    entity_count: u32,
    cancelled: bool,
};

pub const EntitiesUnloadEventData = struct {
    chunk_x: i32,
    chunk_z: i32,
    entity_count: u32,
    cancelled: bool,
};

pub const GenericGameEventData = struct {
    event_id: []const u8,
    pos: Position,
    cancelled: bool,
};

pub const LootGenerateEventData = struct {
    loot_table: []const u8,
    cancelled: bool,
};

pub const PortalCreateEventData = struct {
    pos: BlockPos,
    portal_type: []const u8,
    cancelled: bool,
};

pub const StructureGrowEventData = struct {
    pos: BlockPos,
    species: []const u8,
    bone_meal: bool,
    cancelled: bool,
};

pub const TimeSkipEventData = struct {
    skip_amount: i64,
    cancelled: bool,
};

pub const WorldInitEventData = struct {
    target_world: World,
};

pub const WorldSaveEventData = struct {
    world_name: []const u8,
    cancelled: bool,
};

pub const InventoryOpenEventData = struct {
    player: Player,
    cancelled: bool,
};

pub const InventoryDragEventData = struct {
    player: Player,
    cancelled: bool,
};

pub const CraftItemEventData = struct {
    player: Player,
    recipe_id: []const u8,
    cancelled: bool,
};

pub const FurnaceSmeltEventData = struct {
    block_pos: BlockPos,
    source_item: []const u8,
    result_item: []const u8,
    cancelled: bool,
};

pub const BrewEventData = struct {
    block_pos: BlockPos,
    fuel_level: u8,
    cancelled: bool,
};

pub const BrewingStandFuelEventData = struct {
    block_pos: BlockPos,
    fuel_power: u16,
    cancelled: bool,
};

pub const FurnaceBurnEventData = struct {
    block_pos: BlockPos,
    fuel_item: []const u8,
    burn_time: u32,
    cancelled: bool,
};

pub const FurnaceExtractEventData = struct {
    player: Player,
    block_pos: BlockPos,
    item_id: []const u8,
    item_amount: u32,
    exp_gained: f32,
};

pub const FurnaceStartSmeltEventData = struct {
    block_pos: BlockPos,
    source_item: []const u8,
    cooking_time: u32,
    cancelled: bool,
};

pub const HopperInventorySearchEventData = struct {
    block_pos: BlockPos,
    search_pos: BlockPos,
    cancelled: bool,
};

pub const InventoryCreativeEventData = struct {
    player: Player,
    slot: i16,
    item_id: []const u8,
    item_count: u8,
    cancelled: bool,
};

pub const InventoryInteractEventData = struct {
    player: Player,
    cancelled: bool,
};

pub const InventoryMoveItemEventData = struct {
    source_pos: BlockPos,
    target_pos: BlockPos,
    item_id: []const u8,
    item_amount: u32,
    cancelled: bool,
};

pub const InventoryPickupItemEventData = struct {
    block_pos: BlockPos,
    item_entity_id: i32,
    item_id: []const u8,
    cancelled: bool,
};

pub const PrepareAnvilEventData = struct {
    player: Player,
    rename_text: []const u8,
    repair_cost: u32,
};

pub const PrepareGrindstoneEventData = struct {
    player: Player,
    result_item: ?[]const u8,
};

pub const PrepareInventoryResultEventData = struct {
    player: Player,
    result_item: ?[]const u8,
};

pub const PrepareItemCraftEventData = struct {
    player: Player,
    recipe_id: []const u8,
    cancelled: bool,
};

pub const PrepareSmithingEventData = struct {
    player: Player,
    result_item: ?[]const u8,
};

pub const SmithItemEventData = struct {
    player: Player,
    recipe_id: []const u8,
    cancelled: bool,
};

pub const TradeSelectEventData = struct {
    player: Player,
    slot_index: u8,
    cancelled: bool,
};

pub const VehicleBlockCollisionEventData = struct {
    vehicle_id: i32,
    block_pos: BlockPos,
    cancelled: bool,
};

pub const VehicleCollisionEventData = struct {
    vehicle_id: i32,
    cancelled: bool,
};

pub const VehicleCreateEventData = struct {
    vehicle_id: i32,
    cancelled: bool,
};

pub const VehicleDamageEventData = struct {
    vehicle_id: i32,
    damage: f32,
    attacker_id: ?i32,
    cancelled: bool,
};

pub const VehicleDestroyEventData = struct {
    vehicle_id: i32,
    attacker_id: ?i32,
    cancelled: bool,
};

pub const VehicleEnterEventData = struct {
    vehicle_id: i32,
    entered_id: i32,
    cancelled: bool,
};

pub const VehicleEntityCollisionEventData = struct {
    vehicle_id: i32,
    collided_entity_id: i32,
    cancelled: bool,
};

pub const VehicleExitEventData = struct {
    vehicle_id: i32,
    exited_id: i32,
    cancelled: bool,
};

pub const VehicleMoveEventData = struct {
    vehicle_id: i32,
    from_position: Position,
    to_position: Position,
    cancelled: bool,
};

pub const VehicleUpdateEventData = struct {
    vehicle_id: i32,
    cancelled: bool,
};

pub const EnchantmentOffer = struct {
    cost: i32,
    enchantment_id: i32,
    enchantment_level: i32,
};

pub const PrepareItemEnchantEventData = struct {
    player: Player,
    item: ItemStack,
    offers: []const EnchantmentOffer,
    bookshelf_count: i32,
    cancelled: bool,
};

pub const EnchantmentValue = struct {
    enchantment: Enchantment,
    level: u32,
};

pub const EnchantItemEventData = struct {
    player: Player,
    item: ItemStack,
    option: i32,
    cost: i32,
    enchantments_to_add: []const EnchantmentValue,
    cancelled: bool,
};

pub const LightningStrikeEventData = struct {
    position: Position,
    is_effect: bool,
    cancelled: bool,
};

pub const EventType = enum(u16) {
    player_join_event,
    player_leave_event,
    player_login_event,
    player_chat_event,
    player_command_send_event,
    player_permission_check_event,
    player_move_event,
    player_teleport_event,
    player_change_world_event,
    player_respawn_event,
    player_exp_change_event,
    player_item_held_event,
    player_changed_main_hand_event,
    player_gamemode_change_event,
    player_custom_payload_event,
    player_fish_event,
    player_egg_throw_event,
    player_interact_unknown_entity_event,
    player_interact_entity_event,
    player_interact_event,
    player_toggle_sneak_event,
    player_toggle_flight_event,
    player_toggle_sprint_event,
    inventory_click_event,
    inventory_close_event,
    block_redstone_event,
    block_break_event,
    block_burn_event,
    block_can_build_event,
    block_grow_event,
    block_place_event,
    bedrock_form_response_event,
    dialog_click_action_event,
    dialog_show_event,
    dialog_clear_event,
    server_command_event,
    server_list_ping_event,
    server_load_event,
    spawn_change_event,
    server_broadcast_event,
    server_tick_start_event,
    server_tick_end_event,
    packet_received_event,
    packet_sent_event,
    chunk_load_event,
    chunk_save_event,
    chunk_send_event,
    entity_damage_event,
    entity_death_event,
    player_death_event,
    entity_spawn_event,
    entity_combust_event,
    entity_regain_health_event,
    entity_air_change_event,
    entity_breed_event,
    entity_dismount_event,
    entity_dye_event,
    entity_enter_love_mode_event,
    entity_explode_event,
    entity_mount_event,
    entity_pickup_item_event,
    entity_portal_event,
    entity_resurrect_event,
    entity_shoot_bow_event,
    entity_tame_event,
    entity_target_event,
    entity_teleport_event,
    entity_toggle_glide_event,
    entity_transform_event,
    player_item_consume_event,
    player_item_damage_event,
    player_drop_item_event,
    player_bed_enter_event,
    player_bed_leave_event,
    player_bucket_empty_event,
    player_bucket_fill_event,
    block_damage_event,
    block_ignite_event,
    block_from_to_event,
    block_form_event,
    block_fade_event,
    block_dispense_event,
    block_explode_event,
    block_physics_event,
    block_piston_extend_event,
    block_piston_retract_event,
    note_play_event,
    sign_change_event,
    sponge_absorb_event,
    tnt_prime_event,
    weather_change_event,
    thunder_change_event,
    world_load_event,
    world_unload_event,
    async_structure_generate_event,
    async_structure_spawn_event,
    chunk_populate_event,
    chunk_unload_event,
    entities_load_event,
    entities_unload_event,
    generic_game_event,
    loot_generate_event,
    portal_create_event,
    structure_grow_event,
    time_skip_event,
    world_init_event,
    world_save_event,
    inventory_open_event,
    inventory_drag_event,
    craft_item_event,
    furnace_smelt_event,
    brew_event,
    brewing_stand_fuel_event,
    furnace_burn_event,
    furnace_extract_event,
    furnace_start_smelt_event,
    hopper_inventory_search_event,
    inventory_creative_event,
    inventory_interact_event,
    inventory_move_item_event,
    inventory_pickup_item_event,
    prepare_anvil_event,
    prepare_grindstone_event,
    prepare_inventory_result_event,
    prepare_item_craft_event,
    prepare_smithing_event,
    smith_item_event,
    trade_select_event,
    vehicle_block_collision_event,
    vehicle_collision_event,
    vehicle_create_event,
    vehicle_damage_event,
    vehicle_destroy_event,
    vehicle_enter_event,
    vehicle_entity_collision_event,
    vehicle_exit_event,
    vehicle_move_event,
    vehicle_update_event,
    prepare_item_enchant_event,
    enchant_item_event,
    map_initialize_event,
    hanging_break_event,
    hanging_break_by_entity_event,
    hanging_place_event,
    bell_resonate_event,
    bell_ring_event,
    block_brush_event,
    block_cook_event,
    block_damage_abort_event,
    block_dispense_armor_event,
    block_dispense_loot_event,
    block_drop_item_event,
    block_exp_event,
    block_fertilize_event,
    block_multi_place_event,
    block_receive_game_event,
    block_shear_entity_event,
    block_spread_event,
    brewing_start_event,
    campfire_start_event,
    cauldron_level_change_event,
    crafter_craft_event,
    entity_block_form_event,
    fluid_level_change_event,
    inventory_block_start_event,
    leaves_decay_event,
    moisture_change_event,
    sculk_bloom_event,
    vault_display_item_event,
    creature_spawn_event,
    ender_dragon_change_phase_event,
    entity_break_door_event,
    entity_change_block_event,
    entity_damage_by_block_event,
    entity_damage_by_entity_event,
    entity_drop_item_event,
    entity_enter_block_event,
    entity_exhaustion_event,
    entity_interact_event,
    entity_knockback_event,
    entity_place_event,
    entity_pose_change_event,
    entity_potion_effect_event,
    entity_spell_cast_event,
    entity_target_living_entity_event,
    entity_toggle_swim_event,
    explosion_prime_event,
    firework_explode_event,
    food_level_change_event,
    item_despawn_event,
    item_merge_event,
    item_spawn_event,
    piglin_barter_event,
    projectile_hit_event,
    projectile_launch_event,
    sheep_dye_wool_event,
    sheep_regrow_wool_event,
    slime_split_event,
    strider_temperature_change_event,
    villager_acquire_trade_event,
    villager_career_change_event,
    villager_replenish_trade_event,
    warden_anger_change_event,
    area_effect_cloud_apply_event,
    arrow_body_count_change_event,
    bat_toggle_sleep_event,
    creeper_power_event,
    entity_combust_by_block_event,
    entity_combust_by_entity_event,
    entity_knockback_by_entity_event,
    entity_portal_enter_event,
    entity_portal_exit_event,
    entity_remove_event,
    entity_target_block_event,
    entity_unleash_event,
    exp_bottle_event,
    horse_jump_event,
    lingering_potion_splash_event,
    pig_zap_event,
    pig_zombie_anger_event,
    potion_splash_event,
    spawner_spawn_event,
    trial_spawner_spawn_event,
    villager_reputation_change_event,
    async_player_chat_event,
    async_player_pre_login_event,
    player_advancement_done_event,
    player_animation_event,
    player_armor_stand_manipulate_event,
    player_bucket_entity_event,
    player_changed_world_event,
    player_channel_event,
    player_command_preprocess_event,
    player_edit_book_event,
    player_elytra_boost_event,
    player_exp_cooldown_change_event,
    player_harvest_block_event,
    player_hide_entity_event,
    player_item_break_event,
    player_item_mend_event,
    player_kick_event,
    player_leash_entity_event,
    player_level_change_event,
    player_locale_change_event,
    player_name_entity_event,
    player_open_sign_event,
    player_portal_event,
    player_pre_login_event,
    player_riptide_event,
    player_shear_entity_event,
    player_show_entity_event,
    player_spawn_change_event,
    player_statistic_increment_event,
    player_swap_hands_event,
    player_take_lectern_book_event,
    player_unleash_entity_event,
    player_velocity_event,
    player_input_event,
    player_interact_at_entity_event,
    player_links_send_event,
    player_pickup_arrow_event,
    player_recipe_book_click_event,
    player_recipe_book_settings_change_event,
    player_recipe_discover_event,
    player_register_channel_event,
    player_resource_pack_status_event,
    player_spawn_location_event,
    player_unregister_channel_event,
    raid_finish_event,
    raid_spawn_wave_event,
    raid_stop_event,
    raid_trigger_event,
    lightning_strike_event,
};

pub const Event = union(enum) {
    player_join_event: PlayerJoinEventData,
    player_leave_event: PlayerLeaveEventData,
    player_login_event: PlayerLoginEventData,
    player_chat_event: PlayerChatEventData,
    player_command_send_event: PlayerCommandSendEventData,
    player_permission_check_event: PlayerPermissionCheckEventData,
    player_move_event: PlayerMoveEventData,
    player_teleport_event: PlayerTeleportEventData,
    player_change_world_event: PlayerChangeWorldEventData,
    player_respawn_event: PlayerRespawnEventData,
    player_exp_change_event: PlayerExpChangeEventData,
    player_item_held_event: PlayerItemHeldEventData,
    player_changed_main_hand_event: PlayerChangedMainHandEventData,
    player_gamemode_change_event: PlayerGamemodeChangeEventData,
    player_custom_payload_event: PlayerCustomPayloadEventData,
    player_fish_event: PlayerFishEventData,
    player_egg_throw_event: PlayerEggThrowEventData,
    player_interact_unknown_entity_event: PlayerInteractUnknownEntityEventData,
    player_interact_entity_event: PlayerInteractEntityEventData,
    player_interact_event: PlayerInteractEventData,
    player_toggle_sneak_event: PlayerToggleSneakEventData,
    player_toggle_flight_event: PlayerToggleFlightEventData,
    player_toggle_sprint_event: PlayerToggleSprintEventData,
    inventory_click_event: InventoryClickEventData,
    inventory_close_event: InventoryCloseEventData,
    block_redstone_event: BlockRedstoneEventData,
    block_break_event: BlockBreakEventData,
    block_burn_event: BlockBurnEventData,
    block_can_build_event: BlockCanBuildEventData,
    block_grow_event: BlockGrowEventData,
    block_place_event: BlockPlaceEventData,
    dialog_click_action_event: DialogClickActionEventData,
    dialog_show_event: DialogShowEventData,
    dialog_clear_event: DialogClearEventData,
    bedrock_form_response_event: BedrockFormResponseEventData,
    server_command_event: ServerCommandEventData,
    server_list_ping_event: ServerListPingEventData,
    server_load_event: ServerLoadEventData,
    spawn_change_event: SpawnChangeEventData,
    server_broadcast_event: ServerBroadcastEventData,
    server_tick_start_event: ServerTickStartEventData,
    server_tick_end_event: ServerTickEndEventData,
    packet_received_event: PacketReceivedEventData,
    packet_sent_event: PacketSentEventData,
    chunk_load_event: ChunkLoadEventData,
    chunk_save_event: ChunkSaveEventData,
    chunk_send_event: ChunkSendEventData,
    entity_damage_event: EntityDamageEventData,
    entity_death_event: EntityDeathEventData,
    player_death_event: PlayerDeathEventData,
    entity_spawn_event: EntitySpawnEventData,
    entity_combust_event: EntityCombustEventData,
    entity_regain_health_event: EntityRegainHealthEventData,
    entity_air_change_event: EntityAirChangeEventData,
    entity_breed_event: EntityBreedEventData,
    entity_dismount_event: EntityDismountEventData,
    entity_dye_event: EntityDyeEventData,
    entity_enter_love_mode_event: EntityEnterLoveModeEventData,
    entity_explode_event: EntityExplodeEventData,
    entity_mount_event: EntityMountEventData,
    entity_pickup_item_event: EntityPickupItemEventData,
    entity_portal_event: EntityPortalEventData,
    entity_resurrect_event: EntityResurrectEventData,
    entity_shoot_bow_event: EntityShootBowEventData,
    entity_tame_event: EntityTameEventData,
    entity_target_event: EntityTargetEventData,
    entity_teleport_event: EntityTeleportEventData,
    entity_toggle_glide_event: EntityToggleGlideEventData,
    entity_transform_event: EntityTransformEventData,
    player_item_consume_event: PlayerItemConsumeEventData,
    player_item_damage_event: PlayerItemDamageEventData,
    player_drop_item_event: PlayerDropItemEventData,
    player_bed_enter_event: PlayerBedEnterEventData,
    player_bed_leave_event: PlayerBedLeaveEventData,
    player_bucket_empty_event: PlayerBucketEmptyEventData,
    player_bucket_fill_event: PlayerBucketFillEventData,
    block_damage_event: BlockDamageEventData,
    block_ignite_event: BlockIgniteEventData,
    block_from_to_event: BlockFromToEventData,
    block_form_event: BlockFormEventData,
    block_fade_event: BlockFadeEventData,
    block_dispense_event: BlockDispenseEventData,
    block_explode_event: BlockExplodeEventData,
    block_physics_event: BlockPhysicsEventData,
    block_piston_extend_event: BlockPistonExtendEventData,
    block_piston_retract_event: BlockPistonRetractEventData,
    note_play_event: NotePlayEventData,
    sign_change_event: SignChangeEventData,
    sponge_absorb_event: SpongeAbsorbEventData,
    tnt_prime_event: TntPrimeEventData,
    weather_change_event: WeatherChangeEventData,
    thunder_change_event: ThunderChangeEventData,
    world_load_event: WorldLoadEventData,
    world_unload_event: WorldUnloadEventData,
    async_structure_generate_event: AsyncStructureGenerateEventData,
    async_structure_spawn_event: AsyncStructureSpawnEventData,
    chunk_populate_event: ChunkPopulateEventData,
    chunk_unload_event: ChunkUnloadEventData,
    entities_load_event: EntitiesLoadEventData,
    entities_unload_event: EntitiesUnloadEventData,
    generic_game_event: GenericGameEventData,
    loot_generate_event: LootGenerateEventData,
    portal_create_event: PortalCreateEventData,
    structure_grow_event: StructureGrowEventData,
    time_skip_event: TimeSkipEventData,
    world_init_event: WorldInitEventData,
    world_save_event: WorldSaveEventData,
    inventory_open_event: InventoryOpenEventData,
    inventory_drag_event: InventoryDragEventData,
    craft_item_event: CraftItemEventData,
    furnace_smelt_event: FurnaceSmeltEventData,
    brew_event: BrewEventData,
    brewing_stand_fuel_event: BrewingStandFuelEventData,
    furnace_burn_event: FurnaceBurnEventData,
    furnace_extract_event: FurnaceExtractEventData,
    furnace_start_smelt_event: FurnaceStartSmeltEventData,
    hopper_inventory_search_event: HopperInventorySearchEventData,
    inventory_creative_event: InventoryCreativeEventData,
    inventory_interact_event: InventoryInteractEventData,
    inventory_move_item_event: InventoryMoveItemEventData,
    inventory_pickup_item_event: InventoryPickupItemEventData,
    prepare_anvil_event: PrepareAnvilEventData,
    prepare_grindstone_event: PrepareGrindstoneEventData,
    prepare_inventory_result_event: PrepareInventoryResultEventData,
    prepare_item_craft_event: PrepareItemCraftEventData,
    prepare_smithing_event: PrepareSmithingEventData,
    smith_item_event: SmithItemEventData,
    trade_select_event: TradeSelectEventData,
    vehicle_block_collision_event: VehicleBlockCollisionEventData,
    vehicle_collision_event: VehicleCollisionEventData,
    vehicle_create_event: VehicleCreateEventData,
    vehicle_damage_event: VehicleDamageEventData,
    vehicle_destroy_event: VehicleDestroyEventData,
    vehicle_enter_event: VehicleEnterEventData,
    vehicle_entity_collision_event: VehicleEntityCollisionEventData,
    vehicle_exit_event: VehicleExitEventData,
    vehicle_move_event: VehicleMoveEventData,
    vehicle_update_event: VehicleUpdateEventData,
    prepare_item_enchant_event: PrepareItemEnchantEventData,
    enchant_item_event: EnchantItemEventData,
    map_initialize_event: MapInitializeEventData,
    hanging_break_event: HangingBreakEventData,
    hanging_break_by_entity_event: HangingBreakByEntityEventData,
    hanging_place_event: HangingPlaceEventData,
    bell_resonate_event: BellResonateEventData,
    bell_ring_event: BellRingEventData,
    block_brush_event: BlockBrushEventData,
    block_cook_event: BlockCookEventData,
    block_damage_abort_event: BlockDamageAbortEventData,
    block_dispense_armor_event: BlockDispenseArmorEventData,
    block_dispense_loot_event: BlockDispenseLootEventData,
    block_drop_item_event: BlockDropItemEventData,
    block_exp_event: BlockExpEventData,
    block_fertilize_event: BlockFertilizeEventData,
    block_multi_place_event: BlockMultiPlaceEventData,
    block_receive_game_event: BlockReceiveGameEventData,
    block_shear_entity_event: BlockShearEntityEventData,
    block_spread_event: BlockSpreadEventData,
    brewing_start_event: BrewingStartEventData,
    campfire_start_event: CampfireStartEventData,
    cauldron_level_change_event: CauldronLevelChangeEventData,
    crafter_craft_event: CrafterCraftEventData,
    entity_block_form_event: EntityBlockFormEventData,
    fluid_level_change_event: FluidLevelChangeEventData,
    inventory_block_start_event: InventoryBlockStartEventData,
    leaves_decay_event: LeavesDecayEventData,
    moisture_change_event: MoistureChangeEventData,
    sculk_bloom_event: SculkBloomEventData,
    vault_display_item_event: VaultDisplayItemEventData,
    creature_spawn_event: CreatureSpawnEventData,
    ender_dragon_change_phase_event: EnderDragonChangePhaseEventData,
    entity_break_door_event: EntityBreakDoorEventData,
    entity_change_block_event: EntityChangeBlockEventData,
    entity_damage_by_block_event: EntityDamageByBlockEventData,
    entity_damage_by_entity_event: EntityDamageByEntityEventData,
    entity_drop_item_event: EntityDropItemEventData,
    entity_enter_block_event: EntityEnterBlockEventData,
    entity_exhaustion_event: EntityExhaustionEventData,
    entity_interact_event: EntityInteractEventData,
    entity_knockback_event: EntityKnockbackEventData,
    entity_place_event: EntityPlaceEventData,
    entity_pose_change_event: EntityPoseChangeEventData,
    entity_potion_effect_event: EntityPotionEffectEventData,
    entity_spell_cast_event: EntitySpellCastEventData,
    entity_target_living_entity_event: EntityTargetLivingEntityEventData,
    entity_toggle_swim_event: EntityToggleSwimEventData,
    explosion_prime_event: ExplosionPrimeEventData,
    firework_explode_event: FireworkExplodeEventData,
    food_level_change_event: FoodLevelChangeEventData,
    item_despawn_event: ItemDespawnEventData,
    item_merge_event: ItemMergeEventData,
    item_spawn_event: ItemSpawnEventData,
    piglin_barter_event: PiglinBarterEventData,
    projectile_hit_event: ProjectileHitEventData,
    projectile_launch_event: ProjectileLaunchEventData,
    sheep_dye_wool_event: SheepDyeWoolEventData,
    sheep_regrow_wool_event: SheepRegrowWoolEventData,
    slime_split_event: SlimeSplitEventData,
    strider_temperature_change_event: StriderTemperatureChangeEventData,
    villager_acquire_trade_event: VillagerAcquireTradeEventData,
    villager_career_change_event: VillagerCareerChangeEventData,
    villager_replenish_trade_event: VillagerReplenishTradeEventData,
    warden_anger_change_event: WardenAngerChangeEventData,
    area_effect_cloud_apply_event: AreaEffectCloudApplyEventData,
    arrow_body_count_change_event: ArrowBodyCountChangeEventData,
    bat_toggle_sleep_event: BatToggleSleepEventData,
    creeper_power_event: CreeperPowerEventData,
    entity_combust_by_block_event: EntityCombustByBlockEventData,
    entity_combust_by_entity_event: EntityCombustByEntityEventData,
    entity_knockback_by_entity_event: EntityKnockbackByEntityEventData,
    entity_portal_enter_event: EntityPortalEnterEventData,
    entity_portal_exit_event: EntityPortalExitEventData,
    entity_remove_event: EntityRemoveEventData,
    entity_target_block_event: EntityTargetBlockEventData,
    entity_unleash_event: EntityUnleashEventData,
    exp_bottle_event: ExpBottleEventData,
    horse_jump_event: HorseJumpEventData,
    lingering_potion_splash_event: LingeringPotionSplashEventData,
    pig_zap_event: PigZapEventData,
    pig_zombie_anger_event: PigZombieAngerEventData,
    potion_splash_event: PotionSplashEventData,
    spawner_spawn_event: SpawnerSpawnEventData,
    trial_spawner_spawn_event: TrialSpawnerSpawnEventData,
    villager_reputation_change_event: VillagerReputationChangeEventData,
    async_player_chat_event: AsyncPlayerChatEventData,
    async_player_pre_login_event: AsyncPlayerPreLoginEventData,
    player_advancement_done_event: PlayerAdvancementDoneEventData,
    player_animation_event: PlayerAnimationEventData,
    player_armor_stand_manipulate_event: PlayerArmorStandManipulateEventData,
    player_bucket_entity_event: PlayerBucketEntityEventData,
    player_changed_world_event: PlayerChangedWorldEventData,
    player_channel_event: PlayerChannelEventData,
    player_command_preprocess_event: PlayerCommandPreprocessEventData,
    player_edit_book_event: PlayerEditBookEventData,
    player_elytra_boost_event: PlayerElytraBoostEventData,
    player_exp_cooldown_change_event: PlayerExpCooldownChangeEventData,
    player_harvest_block_event: PlayerHarvestBlockEventData,
    player_hide_entity_event: PlayerHideEntityEventData,
    player_item_break_event: PlayerItemBreakEventData,
    player_item_mend_event: PlayerItemMendEventData,
    player_kick_event: PlayerKickEventData,
    player_leash_entity_event: PlayerLeashEntityEventData,
    player_level_change_event: PlayerLevelChangeEventData,
    player_locale_change_event: PlayerLocaleChangeEventData,
    player_name_entity_event: PlayerNameEntityEventData,
    player_open_sign_event: PlayerOpenSignEventData,
    player_portal_event: PlayerPortalEventData,
    player_pre_login_event: PlayerPreLoginEventData,
    player_riptide_event: PlayerRiptideEventData,
    player_shear_entity_event: PlayerShearEntityEventData,
    player_show_entity_event: PlayerShowEntityEventData,
    player_spawn_change_event: PlayerSpawnChangeEventData,
    player_statistic_increment_event: PlayerStatisticIncrementEventData,
    player_swap_hands_event: PlayerSwapHandsEventData,
    player_take_lectern_book_event: PlayerTakeLecternBookEventData,
    player_unleash_entity_event: PlayerUnleashEntityEventData,
    player_velocity_event: PlayerVelocityEventData,
    player_input_event: PlayerInputEventData,
    player_interact_at_entity_event: PlayerInteractAtEntityEventData,
    player_links_send_event: PlayerLinksSendEventData,
    player_pickup_arrow_event: PlayerPickupArrowEventData,
    player_recipe_book_click_event: PlayerRecipeBookClickEventData,
    player_recipe_book_settings_change_event: PlayerRecipeBookSettingsChangeEventData,
    player_recipe_discover_event: PlayerRecipeDiscoverEventData,
    player_register_channel_event: PlayerRegisterChannelEventData,
    player_resource_pack_status_event: PlayerResourcePackStatusEventData,
    player_spawn_location_event: PlayerSpawnLocationEventData,
    player_unregister_channel_event: PlayerUnregisterChannelEventData,
    raid_finish_event: RaidFinishEventData,
    raid_spawn_wave_event: RaidSpawnWaveEventData,
    raid_stop_event: RaidStopEventData,
    raid_trigger_event: RaidTriggerEventData,
    lightning_strike_event: LightningStrikeEventData,
};
