// Generated by tools/gen.zig, do not edit.

const std = @import("std");
const abi = @import("../abi.zig");
const context = @import("context.zig");
const server = @import("server.zig");
const event = @import("event.zig");
const command = @import("command.zig");
const ipc = @import("ipc.zig");
const world = @import("world.zig");
const metadata = @import("metadata.zig");

/// --- Plugin-provided exports ---
/// Called by the host once to initialize the plugin.
/// Internal use only; plugins should use the `register_plugin!` macro.
pub fn initPlugin(comptime impl: fn () void) void {
    const glue = struct {
        fn call() callconv(.c) void {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{});
            defer abi.endCall();
            return abi.lowerReturn(void, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "init-plugin" });
}

/// Called when the plugin is being loaded.
/// Use this to register commands, events, and perform initial setup.
pub fn onLoad(comptime impl: fn (context.Context) abi.Result(void, []const u8)) void {
    const glue = struct {
        fn call(p0: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{p0});
            return abi.lowerReturn(abi.Result(void, []const u8), @call(.auto, impl, args));
        }

        fn post(_: i32) callconv(.c) void {
            abi.endCall();
        }
    };
    @export(&glue.call, .{ .name = "on-load" });
    @export(&glue.post, .{ .name = "cabi_post_on-load" });
}

/// Called when the plugin is being unloaded.
/// Use this to save data and clean up resources.
pub fn onUnload(comptime impl: fn (context.Context) abi.Result(void, []const u8)) void {
    const glue = struct {
        fn call(p0: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{p0});
            return abi.lowerReturn(abi.Result(void, []const u8), @call(.auto, impl, args));
        }

        fn post(_: i32) callconv(.c) void {
            abi.endCall();
        }
    };
    @export(&glue.call, .{ .name = "on-unload" });
    @export(&glue.post, .{ .name = "cabi_post_on-unload" });
}

/// Dispatches an event to the plugin for handling.
pub fn handleEvent(comptime impl: fn (u32, server.Server, event.Event) event.Event) void {
    const glue = struct {
        fn call(p0: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{p0});
            return abi.lowerReturn(event.Event, @call(.auto, impl, args));
        }

        fn post(_: i32) callconv(.c) void {
            abi.endCall();
        }
    };
    @export(&glue.call, .{ .name = "handle-event" });
    @export(&glue.post, .{ .name = "cabi_post_handle-event" });
}

/// Dispatches a command execution to the plugin.
pub fn handleCommand(comptime impl: fn (u32, command.CommandSender, server.Server, command.ConsumedArgs) abi.Result(i32, command.CommandError)) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32, p3: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2, p3 });
            return abi.lowerReturn(abi.Result(i32, command.CommandError), @call(.auto, impl, args));
        }

        fn post(_: i32) callconv(.c) void {
            abi.endCall();
        }
    };
    @export(&glue.call, .{ .name = "handle-command" });
    @export(&glue.post, .{ .name = "cabi_post_handle-command" });
}

/// Dispatches a command suggestion request to the plugin.
pub fn handleCommandSuggestion(comptime impl: fn (u32, command.CommandSender, server.Server, command.SuggestionRequest) command.CommandSuggestions) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32, p3: i32, p4: i32, p5: i32, p6: i32, p7: i32, p8: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2, p3, p4, p5, p6, p7, p8 });
            return abi.lowerReturn(command.CommandSuggestions, @call(.auto, impl, args));
        }

        fn post(_: i32) callconv(.c) void {
            abi.endCall();
        }
    };
    @export(&glue.call, .{ .name = "handle-command-suggestion" });
    @export(&glue.post, .{ .name = "cabi_post_handle-command-suggestion" });
}

/// Dispatches a scheduled task execution to the plugin.
pub fn handleTask(comptime impl: fn (u32, server.Server) void) void {
    const glue = struct {
        fn call(p0: i32, p1: i32) callconv(.c) void {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1 });
            defer abi.endCall();
            return abi.lowerReturn(void, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "handle-task" });
}

/// Processes an incoming message from another plugin if possible, and returns (a possibly empty) response.
pub fn handleIpcMessage(comptime impl: fn (ipc.PluginId, ipc.IpcMessage) abi.Result(ipc.IpcMessage, []const u8)) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32, p3: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2, p3 });
            return abi.lowerReturn(abi.Result(ipc.IpcMessage, []const u8), @call(.auto, impl, args));
        }

        fn post(_: i32) callconv(.c) void {
            abi.endCall();
        }
    };
    @export(&glue.call, .{ .name = "handle-ipc-message" });
    @export(&glue.post, .{ .name = "cabi_post_handle-ipc-message" });
}

pub fn handleAiGoalCanStart(comptime impl: fn (u32, server.Server, world.Entity) bool) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2 });
            defer abi.endCall();
            return abi.lowerReturn(bool, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "handle-ai-goal-can-start" });
}

pub fn handleAiGoalShouldContinue(comptime impl: fn (u32, server.Server, world.Entity) bool) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32) callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2 });
            defer abi.endCall();
            return abi.lowerReturn(bool, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "handle-ai-goal-should-continue" });
}

pub fn handleAiGoalStart(comptime impl: fn (u32, server.Server, world.Entity) void) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32) callconv(.c) void {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2 });
            defer abi.endCall();
            return abi.lowerReturn(void, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "handle-ai-goal-start" });
}

pub fn handleAiGoalTick(comptime impl: fn (u32, server.Server, world.Entity) void) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32) callconv(.c) void {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2 });
            defer abi.endCall();
            return abi.lowerReturn(void, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "handle-ai-goal-tick" });
}

pub fn handleAiGoalStop(comptime impl: fn (u32, server.Server, world.Entity) void) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32) callconv(.c) void {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2 });
            defer abi.endCall();
            return abi.lowerReturn(void, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "handle-ai-goal-stop" });
}

/// Dispatches a chunk generation phase to the plugin.
pub fn handleGeneratePhase(comptime impl: fn (u32, world.GenerationPhase, world.ChunkBuffer) void) void {
    const glue = struct {
        fn call(p0: i32, p1: i32, p2: i32) callconv(.c) void {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{ p0, p1, p2 });
            defer abi.endCall();
            return abi.lowerReturn(void, @call(.auto, impl, args));
        }
    };
    @export(&glue.call, .{ .name = "handle-generate-phase" });
}

pub fn getMetadata(comptime impl: fn () metadata.PluginMetadata) void {
    const glue = struct {
        fn call() callconv(.c) i32 {
            const args = abi.liftArgs(std.meta.ArgsTuple(@TypeOf(impl)), .{});
            return abi.lowerReturn(metadata.PluginMetadata, @call(.auto, impl, args));
        }

        fn post(_: i32) callconv(.c) void {
            abi.endCall();
        }
    };
    @export(&glue.call, .{ .name = "pumpkin:plugin/metadata@0.1.0#get-metadata" });
    @export(&glue.post, .{ .name = "cabi_post_pumpkin:plugin/metadata@0.1.0#get-metadata" });
}
