// Generated by tools/gen.zig, do not edit.

const text = @import("text.zig");

pub const TextComponent = text.TextComponent;

pub const ImageType = enum(u8) {
    url,
    path,
};

pub const FormImage = struct {
    type: ImageType,
    data: []const u8,
};

pub const SimpleFormButton = struct {
    text: TextComponent,
    image: ?FormImage,
};

pub const SimpleForm = struct {
    title: TextComponent,
    content: TextComponent,
    buttons: []const SimpleFormButton,
};

pub const ModalForm = struct {
    title: TextComponent,
    content: TextComponent,
    button1: TextComponent,
    button2: TextComponent,
};

pub const CustomFormElement = union(enum) {
    label: TextComponent,
    toggle: struct { TextComponent, bool },
    slider: struct { TextComponent, f32, f32, f32, f32 },
    /// text, min, max, step, default
    step_slider: struct { TextComponent, []const []const u8, u32 },
    /// text, steps, default
    dropdown: struct { TextComponent, []const []const u8, u32 },
    /// text, options, default
    input: struct { TextComponent, []const u8, []const u8 },
};

pub const CustomForm = struct {
    title: TextComponent,
    elements: []const CustomFormElement,
};

pub const Form = union(enum) {
    simple: SimpleForm,
    modal: ModalForm,
    custom: CustomForm,
};
