// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const text = @import("text.zig");
const common = @import("common.zig");
const item_stack = @import("item_stack.zig");
const screens = @import("screens.zig");
const inventory = @import("inventory.zig");

pub const TextComponent = text.TextComponent;
pub const ClickType = common.ClickType;
pub const ItemStack = item_stack.ItemStack;
pub const Screen = screens.Screen;
pub const Inventory = inventory.Inventory;

pub const Gui = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]gui";

    /// Consumes `title`.
    pub fn init(@"type": Screen, title: TextComponent) Gui {
        return abi.call(raw.@"[constructor]gui", Gui, .{ @"type", title });
    }

    /// Returns the underlying inventory handle for this GUI.
    pub fn getInventory(self: Gui) Inventory {
        return abi.call(raw.@"[method]gui.get-inventory", Inventory, .{abi.borrow(self)});
    }

    /// Consumes `item`.
    pub fn setItem(self: Gui, slot: u32, item: ItemStack) void {
        return abi.call(raw.@"[method]gui.set-item", void, .{ abi.borrow(self), slot, item });
    }

    pub fn getItem(self: Gui, slot: u32) ?ItemStack {
        return abi.call(raw.@"[method]gui.get-item", ?ItemStack, .{ abi.borrow(self), slot });
    }

    /// Returns the type of this GUI.
    pub fn getType(self: Gui) Screen {
        return abi.call(raw.@"[method]gui.get-type", Screen, .{abi.borrow(self)});
    }

    /// Returns the title of this GUI.
    pub fn getTitle(self: Gui) TextComponent {
        return abi.call(raw.@"[method]gui.get-title", TextComponent, .{abi.borrow(self)});
    }

    /// Returns the number of slots in this GUI.
    pub fn getSize(self: Gui) u32 {
        return abi.call(raw.@"[method]gui.get-size", u32, .{abi.borrow(self)});
    }

    /// Clears all items from the GUI.
    pub fn clearItems(self: Gui) void {
        return abi.call(raw.@"[method]gui.clear-items", void, .{abi.borrow(self)});
    }

    /// Sets whether players can grab items out of the inventory.
    pub fn setAllowGrabItems(self: Gui, allow: bool) void {
        return abi.call(raw.@"[method]gui.set-allow-grab-items", void, .{ abi.borrow(self), allow });
    }

    /// Returns whether players can grab items out of the inventory.
    pub fn getAllowGrabItems(self: Gui) bool {
        return abi.call(raw.@"[method]gui.get-allow-grab-items", bool, .{abi.borrow(self)});
    }

    /// Sets whether players can put items into the inventory from their own.
    pub fn setAllowPutItems(self: Gui, allow: bool) void {
        return abi.call(raw.@"[method]gui.set-allow-put-items", void, .{ abi.borrow(self), allow });
    }

    /// Returns whether players can put items into the inventory from their own.
    pub fn getAllowPutItems(self: Gui) bool {
        return abi.call(raw.@"[method]gui.get-allow-put-items", bool, .{abi.borrow(self)});
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: Gui) void {
        abi.keep(Gui, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: Gui) void {
        abi.drop(Gui, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/gui@0.1.0" fn @"[constructor]gui"(i32, i32) i32;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.get-inventory"(i32) i32;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.set-item"(i32, i32, i32) void;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.get-item"(i32, i32, i32) void;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.get-type"(i32) i32;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.get-title"(i32) i32;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.get-size"(i32) i32;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.clear-items"(i32) void;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.set-allow-grab-items"(i32, i32) void;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.get-allow-grab-items"(i32) i32;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.set-allow-put-items"(i32, i32) void;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[method]gui.get-allow-put-items"(i32) i32;
    extern "pumpkin:plugin/gui@0.1.0" fn @"[resource-drop]gui"(i32) void;
};
