// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const common = @import("common.zig");

pub const Locale = common.Locale;

/// Retrieves a translated string from the host.
///
/// # Arguments
/// * `key`: The namespaced translation key (e.g. `pumpkin:my_key`).
/// * `locale`: The target locale.
///
/// # Returns
/// The localized string, falling back to English or the key itself.
pub fn translate(key: []const u8, locale: Locale) []const u8 {
    return abi.call(raw.translate, []const u8, .{ key, locale });
}

/// Loads custom translations from a JSON string.
///
/// # Arguments
/// * `namespace`: The namespace to associate these keys with.
/// * `json`: A JSON string containing a flat map of translations.
/// * `locale`: The target locale for these translations.
pub fn loadTranslations(namespace: []const u8, json: []const u8, locale: Locale) void {
    return abi.call(raw.@"load-translations", void, .{ namespace, json, locale });
}

const raw = struct {
    extern "pumpkin:plugin/i18n@0.1.0" fn translate(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/i18n@0.1.0" fn @"load-translations"(i32, i32, i32, i32, i32) void;
};
