// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const item_stack = @import("item_stack.zig");
const common = @import("common.zig");

pub const ItemStack = item_stack.ItemStack;
pub const Hand = common.Hand;

/// Common inventory resource used across GUIs, player inventories, and containers.
pub const Inventory = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]inventory";

    /// Returns the number of slots in this inventory.
    pub fn getSize(self: Inventory) u32 {
        return abi.call(raw.@"[method]inventory.get-size", u32, .{abi.borrow(self)});
    }

    /// Returns true if all slots in this inventory are empty.
    pub fn isEmpty(self: Inventory) bool {
        return abi.call(raw.@"[method]inventory.is-empty", bool, .{abi.borrow(self)});
    }

    /// Returns the item in the specified slot index, or none if empty.
    pub fn getItem(self: Inventory, slot: u32) ?ItemStack {
        return abi.call(raw.@"[method]inventory.get-item", ?ItemStack, .{ abi.borrow(self), slot });
    }

    /// Sets the item in the specified slot index.
    pub fn setItem(self: Inventory, slot: u32, item: ?ItemStack) void {
        return abi.call(raw.@"[method]inventory.set-item", void, .{ abi.borrow(self), slot, item });
    }

    /// Removes and returns the item in the specified slot index.
    pub fn removeItem(self: Inventory, slot: u32) ?ItemStack {
        return abi.call(raw.@"[method]inventory.remove-item", ?ItemStack, .{ abi.borrow(self), slot });
    }

    /// Clears all items from this inventory.
    pub fn clear(self: Inventory) void {
        return abi.call(raw.@"[method]inventory.clear", void, .{abi.borrow(self)});
    }

    /// Returns all items in this inventory as a list of slots.
    pub fn getAllItems(self: Inventory) []const ?ItemStack {
        return abi.call(raw.@"[method]inventory.get-all-items", []const ?ItemStack, .{abi.borrow(self)});
    }

    /// Sets all items in this inventory from a list.
    pub fn setAllItems(self: Inventory, items: []const ?ItemStack) void {
        return abi.call(raw.@"[method]inventory.set-all-items", void, .{ abi.borrow(self), items });
    }

    /// Counts the total number of items with the given ID in this inventory.
    pub fn countItem(self: Inventory, item_id: []const u8) u32 {
        return abi.call(raw.@"[method]inventory.count-item", u32, .{ abi.borrow(self), item_id });
    }

    /// Checks if the inventory contains at least one item with the given ID.
    pub fn containsItem(self: Inventory, item_id: []const u8) bool {
        return abi.call(raw.@"[method]inventory.contains-item", bool, .{ abi.borrow(self), item_id });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: Inventory) void {
        abi.keep(Inventory, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: Inventory) void {
        abi.drop(Inventory, self);
    }
};

/// Specialized player inventory handle providing access to main inventory, armor, offhand, and hotbar.
pub const PlayerInventory = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]player-inventory";

    /// Returns the generic 36-slot inventory handle (hotbar + main storage).
    pub fn asInventory(self: PlayerInventory) Inventory {
        return abi.call(raw.@"[method]player-inventory.as-inventory", Inventory, .{abi.borrow(self)});
    }

    /// Returns the item currently held in the specified hand.
    pub fn getItemInHand(self: PlayerInventory, hand: Hand) ?ItemStack {
        return abi.call(raw.@"[method]player-inventory.get-item-in-hand", ?ItemStack, .{ abi.borrow(self), hand });
    }

    /// Sets the item in the specified hand.
    pub fn setItemInHand(self: PlayerInventory, hand: Hand, item: ?ItemStack) void {
        return abi.call(raw.@"[method]player-inventory.set-item-in-hand", void, .{ abi.borrow(self), hand, item });
    }

    /// Returns the currently selected hotbar slot index (0-8).
    pub fn getSelectedSlot(self: PlayerInventory) u8 {
        return abi.call(raw.@"[method]player-inventory.get-selected-slot", u8, .{abi.borrow(self)});
    }

    /// Sets the currently selected hotbar slot index (0-8).
    pub fn setSelectedSlot(self: PlayerInventory, slot: u8) void {
        return abi.call(raw.@"[method]player-inventory.set-selected-slot", void, .{ abi.borrow(self), slot });
    }

    /// Armor slot accessors
    pub fn getHelmet(self: PlayerInventory) ?ItemStack {
        return abi.call(raw.@"[method]player-inventory.get-helmet", ?ItemStack, .{abi.borrow(self)});
    }

    pub fn setHelmet(self: PlayerInventory, item: ?ItemStack) void {
        return abi.call(raw.@"[method]player-inventory.set-helmet", void, .{ abi.borrow(self), item });
    }

    pub fn getChestplate(self: PlayerInventory) ?ItemStack {
        return abi.call(raw.@"[method]player-inventory.get-chestplate", ?ItemStack, .{abi.borrow(self)});
    }

    pub fn setChestplate(self: PlayerInventory, item: ?ItemStack) void {
        return abi.call(raw.@"[method]player-inventory.set-chestplate", void, .{ abi.borrow(self), item });
    }

    pub fn getLeggings(self: PlayerInventory) ?ItemStack {
        return abi.call(raw.@"[method]player-inventory.get-leggings", ?ItemStack, .{abi.borrow(self)});
    }

    pub fn setLeggings(self: PlayerInventory, item: ?ItemStack) void {
        return abi.call(raw.@"[method]player-inventory.set-leggings", void, .{ abi.borrow(self), item });
    }

    pub fn getBoots(self: PlayerInventory) ?ItemStack {
        return abi.call(raw.@"[method]player-inventory.get-boots", ?ItemStack, .{abi.borrow(self)});
    }

    pub fn setBoots(self: PlayerInventory, item: ?ItemStack) void {
        return abi.call(raw.@"[method]player-inventory.set-boots", void, .{ abi.borrow(self), item });
    }

    pub fn getOffHand(self: PlayerInventory) ?ItemStack {
        return abi.call(raw.@"[method]player-inventory.get-off-hand", ?ItemStack, .{abi.borrow(self)});
    }

    pub fn setOffHand(self: PlayerInventory, item: ?ItemStack) void {
        return abi.call(raw.@"[method]player-inventory.set-off-hand", void, .{ abi.borrow(self), item });
    }

    /// Clears all armor slots.
    pub fn clearArmor(self: PlayerInventory) void {
        return abi.call(raw.@"[method]player-inventory.clear-armor", void, .{abi.borrow(self)});
    }

    /// Clears the 36 main inventory slots.
    pub fn clearMain(self: PlayerInventory) void {
        return abi.call(raw.@"[method]player-inventory.clear-main", void, .{abi.borrow(self)});
    }

    /// Clears all slots (main inventory, armor, offhand).
    pub fn clearAll(self: PlayerInventory) void {
        return abi.call(raw.@"[method]player-inventory.clear-all", void, .{abi.borrow(self)});
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: PlayerInventory) void {
        abi.keep(PlayerInventory, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: PlayerInventory) void {
        abi.drop(PlayerInventory, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.get-size"(i32) i32;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.is-empty"(i32) i32;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.get-item"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.set-item"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.remove-item"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.clear"(i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.get-all-items"(i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.set-all-items"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.count-item"(i32, i32, i32) i32;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]inventory.contains-item"(i32, i32, i32) i32;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.as-inventory"(i32) i32;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.get-item-in-hand"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.set-item-in-hand"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.get-selected-slot"(i32) i32;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.set-selected-slot"(i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.get-helmet"(i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.set-helmet"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.get-chestplate"(i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.set-chestplate"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.get-leggings"(i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.set-leggings"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.get-boots"(i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.set-boots"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.get-off-hand"(i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.set-off-hand"(i32, i32, i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.clear-armor"(i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.clear-main"(i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[method]player-inventory.clear-all"(i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[resource-drop]inventory"(i32) void;
    extern "pumpkin:plugin/inventory@0.1.0" fn @"[resource-drop]player-inventory"(i32) void;
};
