// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");

pub const PluginId = []const u8;

pub const IpcMessage = []const u8;

/// Sends a message to the specified plugin, synchronously receiving a response (or an error).
pub fn sendIpcMessage(recipient: PluginId, message: IpcMessage) abi.Result(abi.Result(IpcMessage, []const u8), void) {
    return abi.call(raw.@"send-ipc-message", abi.Result(abi.Result(IpcMessage, []const u8), void), .{ recipient, message });
}

const raw = struct {
    extern "pumpkin:plugin/ipc@0.1.0" fn @"send-ipc-message"(i32, i32, i32, i32, i32) void;
};
