// Generated by tools/gen.zig, do not edit.

const uuid = @import("uuid.zig");

pub const Uuid = uuid.Uuid;

pub const ConfigSClientInformationConfig = struct {
    locale: []const u8,
    view_distance: u8,
    chat_mode: i32,
    chat_colors: bool,
    skin_parts: u8,
    main_hand: i32,
    text_filtering: bool,
    server_listing: bool,
};

pub const ConfigSConfigCookieResponse = struct {
    key: []const u8,
    has_payload: bool,
    payload: ?[]const u8,
};

pub const ConfigSCustomClickAction = struct {
    action_id: []const u8,
    payload: ?[]const u8,
};

pub const ConfigSKeepAlive = struct {
    keep_alive_id: i64,
};

pub const ConfigSKnownPacks = struct {
    known_packs: []const []const u8,
};

pub const ConfigSPluginMessage = struct {
    channel: []const u8,
    data: []const u8,
};

pub const ConfigSConfigPong = struct {
    id: i32,
};

pub const ResourcePackResponseResult = union(enum) {
    download_success,
    download_fail,
    downloaded,
    accepted,
    declined,
    invalid_url,
    reload_failed,
    discarded,
    unknown: i32,
};

pub const ConfigSConfigResourcePack = struct {
    uuid: Uuid,
    result: i32,
};

pub const LoginSLoginCookieResponse = struct {
    key: []const u8,
    payload: ?[]const u8,
};

pub const SEncryptionResponse = struct {
    shared_secret: []const u8,
    verify_token: []const u8,
};

pub const LoginSLoginStart = struct {
    name: []const u8,
    uuid: Uuid,
};

pub const LoginSLoginPluginResponse = struct {
    message_id: i32,
    data: ?[]const u8,
};

pub const SAttack = struct {
    entity_id: i32,
};

pub const SBlockEntityTagQuery = struct {
    transaction_id: i32,
    location: struct { i32, i32, i32 },
};

pub const SBundleItemSelected = struct {
    slot_id: i32,
    selected_item_index: i32,
};

pub const SChangeDifficulty = struct {
    difficulty: []const u8,
};

pub const SChangeGameMode = struct {
    game_mode: []const u8,
};

pub const SChatAck = struct {
    offset: i32,
};

pub const SChatCommand = struct {
    command: []const u8,
};

pub const ArgumentSignature = struct {
    name: []const u8,
    signature: []const u8,
};

pub const SChatCommandSigned = struct {
    command: []const u8,
    timestamp: i64,
    salt: i64,
    argument_signatures: []const ArgumentSignature,
    message_count: i32,
    acknowledged: []const u8,
    checksum: u8,
};

pub const SChatMessage = struct {
    message: []const u8,
    timestamp: i64,
    salt: i64,
    signature: ?[]const u8,
    message_count: i32,
    acknowledged: []const u8,
    checksum: u8,
};

pub const SChunkBatch = struct {
    chunks_per_tick: f32,
};

pub const SlotActionType = enum(u8) {
    pickup,
    quick_move,
    swap,
    clone,
    throw,
    quick_craft,
    pickup_all,
};

pub const SClickSlot = struct {
    sync_id: i32,
    revision: i32,
    slot: i32,
    button: u8,
    mode: SlotActionType,
    length_of_array: i32,
    array_of_changed_slots: []const struct { i32, []const u8 },
    carried_item: []const u8,
};

pub const SClientCommand = struct {
    action_id: i32,
};

pub const SClientInformationPlay = struct {
    locale: []const u8,
    view_distance: u8,
    chat_mode: i32,
    chat_colors: bool,
    skin_parts: u8,
    main_hand: i32,
    text_filtering: bool,
    server_listing: bool,
};

pub const SCloseContainer = struct {
    window_id: i32,
};

pub const SCommandSuggestion = struct {
    id: i32,
    command: []const u8,
};

pub const SConfirmTeleport = struct {
    teleport_id: i32,
    position: struct { f64, f64, f64 },
    yaw: f32,
    pitch: f32,
};

pub const SContainerButtonClick = struct {
    window_id: i32,
    button_id: i32,
};

pub const SContainerSlotStateChanged = struct {
    slot_id: i32,
    container_id: i32,
    new_state: bool,
};

pub const SCookieResponse = struct {
    key: []const u8,
    payload: ?[]const u8,
};

pub const SCustomClickAction = struct {
    action_id: []const u8,
    payload: ?[]const u8,
};

pub const SCustomPayload = struct {
    channel: []const u8,
    data: []const u8,
};

pub const SDebugSampleSubscription = struct {
    sample_type: i32,
};

pub const SDebugSubscriptionRequest = struct {
    sample_type: i32,
};

pub const SEditBook = struct {
    slot: i32,
    pages: []const []const u8,
    title: ?[]const u8,
};

pub const SEntityTagQuery = struct {
    transaction_id: i32,
    entity_id: i32,
};

pub const SInteract = struct {
    entity_id: i32,
    r_type: i32,
    target_position: ?struct { f64, f64, f64 },
    hand: ?i32,
    sneaking: bool,
};

pub const ActionType = enum(u8) {
    interact,
    attack,
    interact_at,
};

pub const SJigsawGenerate = struct {
    pos: struct { i32, i32, i32 },
    levels: i32,
    keep_jigsaws: bool,
};

pub const SKeepAlive = struct {
    keep_alive_id: i64,
};

pub const SLockDifficulty = struct {
    locked: bool,
};

pub const SMoveVehicle = struct {
    x: f64,
    y: f64,
    z: f64,
    yaw: f32,
    pitch: f32,
    on_ground: bool,
};

pub const SPaddleBoat = struct {
    left_paddle: bool,
    right_paddle: bool,
};

pub const SPickItemFromBlock = struct {
    pos: struct { i32, i32, i32 },
    include_data: bool,
};

pub const SPickItemFromEntity = struct {
    id: i32,
    include_data: bool,
};

pub const SPlayPingRequest = struct {
    payload: i64,
};

pub const SPlaceRecipe = struct {
    container_id: u8,
    recipe_display_id: i32,
    use_max_items: bool,
};

pub const SPlayerAbilities = struct {
    flags: u8,
    fly_speed: ?f32,
    walk_speed: ?f32,
};

pub const SPlayerAction = struct {
    status: i32,
    position: struct { i32, i32, i32 },
    face: u8,
    sequence: i32,
};

pub const Status = enum(u8) {
    started_digging,
    cancelled_digging,
    finished_digging,
    drop_item_stack,
    drop_item,
    release_item_in_use,
    swap_item,
    spear_jab,
    change_destroy_direction,
};

pub const Action = enum(u8) {
    start_sneaking,
    stop_sneaking,
    leave_bed,
    start_sprinting,
    stop_sprinting,
    start_horse_jump,
    stop_horse_jump,
    open_vehicle_inventory,
    start_flying_elytra,
};

pub const SPlayerCommand = struct {
    entity_id: i32,
    action: Action,
    jump_boost: i32,
};

pub const SSetPlayerGround = struct {
    on_ground: bool,
};

pub const SPlayerInput = struct {
    input: u8,
};

pub const SPlayerPosition = struct {
    position: struct { f64, f64, f64 },
    collision: u8,
};

pub const SPlayerPositionRotation = struct {
    position: struct { f64, f64, f64 },
    yaw: f32,
    pitch: f32,
    collision: u8,
};

pub const SPlayerRotation = struct {
    yaw: f32,
    pitch: f32,
    ground: bool,
};

pub const SPlayerSession = struct {
    session_id: Uuid,
    expires_at: i64,
    public_key: []const u8,
    key_signature: []const u8,
};

pub const SPlayPong = struct {
    id: i32,
};

pub const SRecipeBookChangeSettings = struct {
    book_type: i32,
    is_open: bool,
    is_filtering: bool,
};

pub const SRecipeBookSeenRecipe = struct {
    recipe_display_id: i32,
};

pub const SRenameItem = struct {
    item_name: []const u8,
};

pub const PlayResourcePackResult = union(enum) {
    download_success,
    declined,
    download_fail,
    accepted,
    downloaded,
    invalid_url,
    reload_failed,
    discarded,
    unknown: i32,
};

pub const SPlayResourcePack = struct {
    uuid: Uuid,
    result: i32,
};

pub const SSeenAdvancement = union(enum) {
    open_tab: []const u8,
    close_tab,
};

pub const SSelectTrade = struct {
    selected_slot: i32,
};

pub const SSetBeacon = struct {
    primary_effect: ?i32,
    secondary_effect: ?i32,
};

pub const SSetCommandBlock = struct {
    pos: struct { i32, i32, i32 },
    command: []const u8,
    mode: i32,
    flags: u8,
};

pub const CommandBlockMode = enum(u8) {
    chain,
    repeating,
    impulse,
};

pub const SSetCommandMinecart = struct {
    entity_id: i32,
    command: []const u8,
    track_output: bool,
};

pub const SSetCreativeSlot = struct {
    slot: i32,
    clicked_item: []const u8,
};

pub const GameRuleEntry = struct {
    game_rule_key: []const u8,
    value: []const u8,
};

pub const SSetGameRule = struct {
    entries: []const GameRuleEntry,
};

pub const SSetHeldItem = struct {
    slot: i32,
};

pub const SSetJigsawBlock = struct {
    pos: struct { i32, i32, i32 },
    name: []const u8,
    target: []const u8,
    pool: []const u8,
    final_state: []const u8,
    joint: []const u8,
    selection_priority: i32,
    placement_priority: i32,
};

pub const SSetStructureBlock = struct {
    location: struct { i32, i32, i32 },
    action: i32,
    mode: i32,
    name: []const u8,
    offset_x: u8,
    offset_y: u8,
    offset_z: u8,
    size_x: u8,
    size_y: u8,
    size_z: u8,
    mirror: i32,
    rotation: i32,
    metadata: []const u8,
    integrity: f32,
    seed: i64,
    flags: u8,
};

pub const TestBlockMode = enum(u8) {
    start,
    log,
    fail,
    accept,
};

pub const SSetTestBlock = struct {
    position: struct { i32, i32, i32 },
    mode: TestBlockMode,
    message: []const u8,
};

pub const SSpectateEntity = struct {
    target: Uuid,
};

pub const SSwingArm = struct {
    hand: i32,
};

pub const STeleportToEntity = struct {
    target: Uuid,
};

pub const TestInstanceBlockAction = enum(u8) {
    init,
    query,
    set,
    reset,
    save,
    @"export",
    run,
};

pub const VarIntVector3 = struct {
    x: i32,
    y: i32,
    z: i32,
};

pub const TestInstanceBlockStatus = enum(u8) {
    cleared,
    running,
    success,
    failed,
};

pub const TestInstanceBlockData = struct {
    @"test": ?[]const u8,
    size: VarIntVector3,
    rotation: []const u8,
    ignore_entities: bool,
    status: TestInstanceBlockStatus,
    error_message: ?[]const u8,
};

pub const STestInstanceBlockAction = struct {
    pos: struct { i32, i32, i32 },
    action: TestInstanceBlockAction,
    data: TestInstanceBlockData,
};

pub const SUpdateSign = struct {
    location: struct { i32, i32, i32 },
    is_front_text: bool,
    line_1: []const u8,
    line_2: []const u8,
    line_3: []const u8,
    line_4: []const u8,
};

pub const SUseItem = struct {
    hand: i32,
    sequence: i32,
    yaw: f32,
    pitch: f32,
};

pub const SUseItemOn = struct {
    hand: i32,
    position: struct { i32, i32, i32 },
    face: i32,
    cursor_pos: struct { f64, f64, f64 },
    inside_block: bool,
    is_against_world_border: bool,
    sequence: i32,
};

pub const StatusSStatusPingRequest = struct {
    payload: i64,
};

pub const ConfigCConfigAddResourcePack = struct {
    uuid: Uuid,
    url: []const u8,
    hash: []const u8,
    forced: bool,
    prompt_message: ?[]const u8,
};

pub const ConfigCCodeOfConduct = struct {
    code_of_conduct: []const u8,
};

pub const ConfigCConfigDisconnect = struct {
    reason: []const u8,
};

pub const ConfigCCookieRequest = struct {
    key: []const u8,
};

pub const ConfigCConfigCustomReportDetails = struct {
    details: []const struct { []const u8, []const u8 },
};

pub const ConfigCFeatureFlags = struct {
    features: []const []const u8,
};

pub const ConfigCKnownPacks = struct {
    known_packs: []const []const u8,
};

pub const ConfigCConfigPing = struct {
    id: i32,
};

pub const ConfigCPluginMessage = struct {
    channel: []const u8,
    data: []const u8,
};

pub const ConfigCConfigPostEffects = struct {
    effects: []const []const u8,
};

pub const ConfigCRegistryData = struct {
    registry_id: []const u8,
    entries: []const []const u8,
};

pub const ConfigCConfigRemoveResourcePack = struct {
    uuid: ?Uuid,
};

pub const ConfigCConfigServerLinks = struct {
    links: []const []const u8,
};

pub const ConfigCConfigShowDialog = struct {
    dialog: []const u8,
};

pub const ConfigCStoreCookie = struct {
    key: []const u8,
    payload: []const u8,
};

pub const ConfigCTransfer = struct {
    host: []const u8,
    port: i32,
};

pub const ConfigCUpdateTags = struct {
    tags: []const []const u8,
};

pub const LoginCLoginCookieRequest = struct {
    key: []const u8,
};

pub const CEncryptionRequest = struct {
    server_id: []const u8,
    public_key: []const u8,
    verify_token: []const u8,
    should_authenticate: bool,
};

pub const LoginCLoginDisconnect = struct {
    json_reason: []const u8,
};

pub const LoginCLoginPluginRequest = struct {
    message_id: i32,
    channel: []const u8,
    data: []const u8,
};

pub const LoginCSetCompression = struct {
    threshold: i32,
};

pub const CAcknowledgeBlockChange = struct {
    sequence_id: i32,
};

pub const CActionBar = struct {
    action_bar: []const u8,
};

pub const CAddResourcePack = struct {
    uuid: Uuid,
    url: []const u8,
    hash: []const u8,
    forced: bool,
    prompt_message: ?[]const u8,
};

pub const Statistic = struct {
    category_id: i32,
    statistic_id: i32,
    value: i32,
};

pub const CAwardStats = struct {
    stats: []const Statistic,
};

pub const CSetBlockDestroyStage = struct {
    entity_id: i32,
    location: struct { i32, i32, i32 },
    destroy_stage: u8,
};

pub const CBlockEntityData = struct {
    location: struct { i32, i32, i32 },
    r_type: i32,
    nbt_data: []const u8,
};

pub const CBlockEvent = struct {
    location: struct { i32, i32, i32 },
    action_id: u8,
    action_parameter: u8,
    block_type: i32,
};

pub const CBlockUpdate = struct {
    location: struct { i32, i32, i32 },
    state_id: i32,
};

pub const BosseventActionAdd = struct {
    title: []const u8,
    health: f32,
    color: i32,
    division: i32,
    flags: u8,
};

pub const BosseventActionUpdateStyle = struct {
    color: i32,
    dividers: i32,
};

pub const BosseventAction = union(enum) {
    add: BosseventActionAdd,
    remove,
    update_health: f32,
    update_tile: []const u8,
    update_style: BosseventActionUpdateStyle,
    update_flags: u8,
};

pub const CBossEvent = struct {
    uuid: Uuid,
    action: BosseventAction,
};

pub const CCenterChunk = struct {
    chunk_x: i32,
    chunk_z: i32,
};

pub const CChangeDifficulty = struct {
    difficulty: u8,
    locked: bool,
};

pub const CChunkBatchEnd = struct {
    batch_size: i32,
};

pub const ChunkHeightmaps = struct {
    world_surface: ?[]const i64,
    motion_blocking: ?[]const i64,
    motion_blocking_no_leaves: ?[]const i64,
};

pub const ChunkBlockEntity = struct {
    packed_xz: u8,
    y: i32,
    type_id: i32,
    data: []const u8,
};

pub const ChunkBiomeEntry = struct {
    chunk_x: i32,
    chunk_z: i32,
    data: []const u8,
};

pub const CChunksBiomes = struct {
    chunks: []const ChunkBiomeEntry,
};

pub const CClearTitle = struct {
    reset: bool,
};

pub const CCloseContainer = struct {
    sync_id: i32,
};

pub const CCombatDeath = struct {
    player_id: i32,
    message: []const u8,
};

pub const CCombatEnd = struct {
    duration_ticks: i32,
};

pub const CommandSuggestion = struct {
    suggestion: []const u8,
    tooltip: ?[]const u8,
};

pub const CCommandSuggestions = struct {
    id: i32,
    start: i32,
    length: i32,
    matches: []const CommandSuggestion,
};

pub const ProtoNodeTypeLiteral = struct {
    name: []const u8,
    is_executable: bool,
    redirect_target: ?i32,
    restricted: bool,
};

pub const ArgumentTypeFloat = struct {
    min: ?f32,
    max: ?f32,
};

pub const ArgumentTypeDouble = struct {
    min: ?f64,
    max: ?f64,
};

pub const ArgumentTypeInteger = struct {
    min: ?i32,
    max: ?i32,
};

pub const ArgumentTypeLong = struct {
    min: ?i64,
    max: ?i64,
};

pub const ArgumentTypeEntity = struct {
    flags: u8,
};

pub const ArgumentTypeScoreHolder = struct {
    flags: u8,
};

pub const ArgumentTypeTime = struct {
    min: i32,
};

pub const ArgumentTypeResourceOrTag = struct {
    identifier: []const u8,
};

pub const ArgumentTypeResourceOrTagKey = struct {
    identifier: []const u8,
};

pub const ArgumentTypeResource = struct {
    identifier: []const u8,
};

pub const ArgumentTypeResourceKey = struct {
    identifier: []const u8,
};

pub const StringProtoArgBehavior = enum(u8) {
    single_word,
    quotable_phrase,
    greedy_phrase,
};

pub const ArgumentType = union(enum) {
    bool,
    float: ArgumentTypeFloat,
    double: ArgumentTypeDouble,
    integer: ArgumentTypeInteger,
    long: ArgumentTypeLong,
    string: StringProtoArgBehavior,
    entity: ArgumentTypeEntity,
    game_profile,
    block_pos,
    column_pos,
    vec3,
    vec2,
    block_state,
    block_predicate,
    item_stack,
    item_predicate,
    color,
    hex_color,
    component,
    style,
    message,
    nbt_compound,
    nbt_tag,
    nbt_path,
    objective,
    objective_criteria,
    operation,
    particle,
    angle,
    rotation,
    scoreboard_slot,
    score_holder: ArgumentTypeScoreHolder,
    swizzle,
    team,
    item_slot,
    item_slots,
    resource_location,
    function,
    entity_anchor,
    int_range,
    float_range,
    dimension,
    gamemode,
    time: ArgumentTypeTime,
    resource_or_tag: ArgumentTypeResourceOrTag,
    resource_or_tag_key: ArgumentTypeResourceOrTagKey,
    resource: ArgumentTypeResource,
    resource_key: ArgumentTypeResourceKey,
    resource_selector,
    template_mirror,
    template_rotation,
    heightmap,
    loot_table,
    loot_predicate,
    loot_modifier,
    dialog,
    uuid,
};

pub const SuggestionProviders = enum(u8) {
    ask_server,
    all_recipes,
    available_sounds,
    summonable_entities,
};

pub const ProtoNodeTypeArgument = struct {
    name: []const u8,
    is_executable: bool,
    redirect_target: ?i32,
    parser: ArgumentType,
    override_suggestion_type: ?SuggestionProviders,
    restricted: bool,
};

pub const ProtoNodeType = union(enum) {
    root,
    literal: ProtoNodeTypeLiteral,
    argument: ProtoNodeTypeArgument,
};

pub const ProtoNode = struct {
    children: []const i32,
    node_type: ProtoNodeType,
};

pub const CCommands = struct {
    nodes: []const ProtoNode,
    root_node_index: i32,
};

pub const CPlayCookieRequest = struct {
    key: []const u8,
};

pub const CCustomChatCompletions = struct {
    action: i32,
    entries: []const []const u8,
};

pub const CCustomPayload = struct {
    channel: []const u8,
    data: []const u8,
};

pub const CPlayCustomReportDetails = struct {
    details: []const struct { []const u8, []const u8 },
};

pub const CDamageEvent = struct {
    entity_id: i32,
    source_type_id: i32,
    source_cause_id: i32,
    source_direct_id: i32,
    source_position: ?struct { f64, f64, f64 },
};

pub const CDebugBlockValue = struct {
    pos: struct { i32, i32, i32 },
    name: []const u8,
    value: []const u8,
};

pub const CDebugChunkValue = struct {
    chunk_pos: struct { f64, f64 },
    name: []const u8,
    value: []const u8,
};

pub const CDebugEntityValue = struct {
    entity_id: i32,
    name: []const u8,
    value: []const u8,
};

pub const CDebugEvent = struct {
    name: []const u8,
    data: []const u8,
};

pub const CDebugSample = struct {
    sample: []const i64,
    sample_type: i32,
};

pub const CDeleteChat = struct {
    signature_id: i32,
    signature: ?[]const u8,
};

pub const CPlayDisconnect = struct {
    reason: []const u8,
};

pub const CDisguisedChatMessage = struct {
    message: []const u8,
    chat_type: i32,
    sender_name: []const u8,
    target_name: ?[]const u8,
};

pub const CDisplayObjective = struct {
    position: i32,
    score_name: []const u8,
};

pub const CEntityAnimation = struct {
    entity_id: i32,
    animation: u8,
};

pub const CSwingArm = struct {
    entity_id: i32,
    off_hand: bool,
};

pub const Animation = enum(u8) {
    swing_main_arm,
    leave_bed,
    swing_offhand,
    critical_effect,
    magic_criticaleffect,
};

pub const CSetEntityMetadata = struct {
    entity_id: i32,
    metadata: []const u8,
};

pub const CEntityPositionSync = struct {
    entity_id: i32,
    position: struct { f64, f64, f64 },
    delta: struct { f64, f64, f64 },
    yaw: f32,
    pitch: f32,
    on_ground: bool,
};

pub const CEntitySoundEffect = struct {
    sound_event: []const u8,
    sound_category: i32,
    entity_id: i32,
    volume: f32,
    pitch: f32,
    seed: i64,
};

pub const CEntityStatus = struct {
    entity_id: i32,
    entity_status: u8,
};

pub const CEntityVelocity = struct {
    entity_id: i32,
    velocity: []const u8,
};

pub const CExplosion = struct {
    center: struct { f64, f64, f64 },
    radius: f32,
    block_count: i32,
    knockback: ?struct { f64, f64, f64 },
    particle: i32,
    sound: []const u8,
    block_particles_pool_size: i32,
};

pub const CGameEvent = struct {
    event: u8,
    value: f32,
};

pub const GameEvent = enum(u8) {
    no_respawn_block_available,
    begin_raining,
    end_raining,
    change_game_mode,
    win_game,
    demo_event,
    arrow_hit_player,
    rain_level_change,
    thunder_level_change,
    play_pufferfish_string_sound,
    play_elder_guardian_mob_appearance,
    enabled_respawn_screen,
    limited_crafting,
    start_waiting_chunks,
};

pub const CGameRuleValues = struct {
    rules: []const struct { []const u8, []const u8 },
};

pub const CGameTestHighlightPos = struct {
    pos: struct { i32, i32, i32 },
    color: i32,
    label: []const u8,
    duration_ms: i32,
};

pub const CHeadRot = struct {
    entity_id: i32,
    head_yaw: u8,
};

pub const CHurtAnimation = struct {
    entity_id: i32,
    yaw: f32,
};

pub const CInitializeWorldBorder = struct {
    x: f64,
    z: f64,
    old_diameter: f64,
    new_diameter: f64,
    speed: i64,
    portal_teleport_boundary: i32,
    warning_blocks: i32,
    warning_time: i32,
};

pub const CItemCooldown = struct {
    group: []const u8,
    cooldown: i32,
};

pub const CKeepAlive = struct {
    keep_alive_id: i64,
};

pub const CLevelEvent = struct {
    event: i32,
    location: struct { i32, i32, i32 },
    data: i32,
    disable_relative_volume: bool,
};

pub const LightData = struct {
    trust_edges: bool,
    sky_light_mask: []const i64,
    block_light_mask: []const i64,
    empty_sky_light_mask: []const i64,
    empty_block_light_mask: []const i64,
    sky_light_arrays: []const []const u8,
    block_light_arrays: []const []const u8,
};

pub const CChunkData = struct {
    chunk_x: i32,
    chunk_z: i32,
    heightmaps: ChunkHeightmaps,
    data: []const u8,
    block_entities: []const ChunkBlockEntity,
    light_data: LightData,
};

pub const CLightUpdate = struct {
    chunk_x: i32,
    chunk_z: i32,
    light_data: LightData,
};

pub const MapIcon = struct {
    icon_type: i32,
    x: u8,
    z: u8,
    direction: u8,
    display_name: ?[]const u8,
};

pub const MapPatch = struct {
    columns: u8,
    rows: u8,
    x: u8,
    z: u8,
    data: []const u8,
};

pub const CMapItemData = struct {
    map_id: i32,
    scale: u8,
    tracking_position: bool,
    locked: bool,
    icons: ?[]const MapIcon,
    data: ?MapPatch,
};

pub const MerchantOffer = struct {
    base_cost_a: []const u8,
    output: []const u8,
    cost_b: ?[]const u8,
    reward_exp: bool,
    uses: i32,
    max_uses: i32,
    xp: i32,
    special_price: i32,
    price_multiplier: f32,
    demand: i32,
};

pub const CMerchantOffers = struct {
    window_id: i32,
    offers: []const MerchantOffer,
    villager_level: i32,
    experience: i32,
    is_regular_villager: bool,
    can_restock: bool,
};

pub const MinecartStep = struct {
    position: struct { f64, f64, f64 },
    movement: struct { f64, f64, f64 },
    yaw: f32,
    pitch: f32,
    weight: f32,
};

pub const CMoveMinecartAlongTrack = struct {
    entity_id: i32,
    steps: []const MinecartStep,
};

pub const CMoveVehicle = struct {
    x: f64,
    y: f64,
    z: f64,
    yaw: f32,
    pitch: f32,
};

pub const CMultiBlockUpdate = struct {
    chunk_section: struct { f64, f64, f64 },
    suppress_light_updates: bool,
    updates: []const struct { struct { i32, i32, i32 }, []const u8 },
};

pub const COpenBook = struct {
    hand: i32,
};

pub const COpenMountScreen = struct {
    window_id: u8,
    slot_count: i32,
    entity_id: i32,
};

pub const COpenScreen = struct {
    sync_id: i32,
    window_type: i32,
    window_title: []const u8,
};

pub const COpenSignEditor = struct {
    location: struct { i32, i32, i32 },
    is_front_text: bool,
};

pub const CParticle = struct {
    force_spawn: bool,
    important: bool,
    position: struct { f64, f64, f64 },
    offset: struct { f64, f64, f64 },
    max_speed: f32,
    particle_count: i32,
    particle_id: i32,
    data: []const u8,
};

pub const CPlayPing = struct {
    id: i32,
};

pub const CPingResponse = struct {
    payload: i64,
};

pub const CPlaceGhostRecipe = struct {
    window_id: u8,
    recipe_id: []const u8,
};

pub const CPlayerAbilities = struct {
    flags: u8,
    flying_speed: f32,
    field_of_view: f32,
};

pub const InitChat = struct {
    session_id: Uuid,
    expires_at: i64,
    public_key: []const u8,
    signature: []const u8,
};

pub const PreviousMessage = struct {
    id: i32,
    signature: ?[]const u8,
};

pub const FilterType = union(enum) {
    pass_through,
    fully_filtered,
    partially_filtered: []const i64,
};

pub const CPlayerChatMessage = struct {
    global_index: i32,
    sender: Uuid,
    index: i32,
    message_signature: ?[]const u8,
    message: []const u8,
    timestamp: i64,
    salt: i64,
    previous_messages: []const PreviousMessage,
    unsigned_content: ?[]const u8,
    filter_type: FilterType,
    chat_type: i32,
    sender_name: []const u8,
    target_name: ?[]const u8,
};

pub const CPlayerLookAt = struct {
    from_anchor: i32,
    target_x: f64,
    target_y: f64,
    target_z: f64,
    entity: ?struct { i32, i32 },
};

pub const CPlayerPosition = struct {
    teleport_id: i32,
    position: struct { f64, f64, f64 },
    delta: struct { f64, f64, f64 },
    yaw: f32,
    pitch: f32,
    relatives: []const []const u8,
};

pub const CRemovePlayerInfo = struct {
    players: []const Uuid,
};

pub const CPlayerRotation = struct {
    yaw: f32,
    pitch: f32,
};

pub const PlayerSpawnData = struct {
    dimension: []const u8,
    hashed_seed: i64,
    game_mode: u8,
    previous_gamemode: u8,
    debug: bool,
    is_flat: bool,
    death_dimension_name: ?struct { []const u8, struct { i32, i32, i32 } },
    portal_cooldown: i32,
    sealevel: i32,
};

pub const CLogin = struct {
    entity_id: i32,
    is_hardcore: bool,
    dimension_names: []const []const u8,
    max_players: i32,
    view_distance: i32,
    simulated_distance: i32,
    reduced_debug_info: bool,
    enabled_respawn_screen: bool,
    limited_crafting: bool,
    spawn_data: PlayerSpawnData,
    online_mode: bool,
    enforce_secure_chat: bool,
};

pub const CPlayerSpawnPosition = struct {
    dimension_name: []const u8,
    location: struct { i32, i32, i32 },
    yaw: f32,
    pitch: f32,
};

pub const CPostEffects = struct {
    effects: []const []const u8,
};

pub const CProjectilePower = struct {
    entity_id: i32,
    x_power: f64,
    y_power: f64,
    z_power: f64,
};

pub const CRecipeBookAdd = struct {
    replace: bool,
};

pub const CRecipeBookRemove = struct {
    recipes: []const i32,
};

pub const CRecipeBookSettings = struct {
    crafting_open: bool,
    crafting_filtering: bool,
    furnace_open: bool,
    furnace_filtering: bool,
    blast_furnace_open: bool,
    blast_furnace_filtering: bool,
    smoker_open: bool,
    smoker_filtering: bool,
};

pub const CRemoveEntities = struct {
    entity_ids: []const i32,
};

pub const CRemoveMobEffect = struct {
    entity_id: i32,
    effect_id: i32,
};

pub const CRemoveResourcePack = struct {
    uuid: ?Uuid,
};

pub const CResetScore = struct {
    entity_name: []const u8,
    objective_name: ?[]const u8,
};

pub const CRespawn = struct {
    player_spawn_info: PlayerSpawnData,
    data_kept: u8,
};

pub const CSelectAdvancementsTab = struct {
    tab_id: ?[]const u8,
};

pub const CServerData = struct {
    motd: []const u8,
    icon_base64: ?[]const u8,
};

pub const CPlayServerLinks = struct {
    links: []const []const u8,
};

pub const CSetBorderCenter = struct {
    x: f64,
    z: f64,
};

pub const CSetBorderLerpSize = struct {
    old_diameter: f64,
    new_diameter: f64,
    speed: i64,
};

pub const CSetBorderSize = struct {
    diameter: f64,
};

pub const CSetBorderWarningDelay = struct {
    warning_time: i32,
};

pub const CSetBorderWarningDistance = struct {
    warning_blocks: i32,
};

pub const CSetCamera = struct {
    camera_id: i32,
};

pub const CSetChunkCacheRadius = struct {
    radius: i32,
};

pub const CSetContainerContent = struct {
    window_id: i32,
    state_id: i32,
    slot_data: []const []const u8,
    carried_item: []const u8,
};

pub const CSetContainerProperty = struct {
    window_id: i32,
    property: i32,
    value: i32,
};

pub const CSetContainerSlot = struct {
    window_id: u8,
    state_id: i32,
    slot: i32,
    slot_data: []const u8,
};

pub const CSetCursorItem = struct {
    stack: []const u8,
};

pub const CSetEntityLink = struct {
    attached_entity_id: i32,
    holding_entity_id: i32,
    leash: bool,
};

pub const CSetEquipment = struct {
    entity_id: i32,
    equipment: []const struct { u8, []const u8 },
};

pub const CSetExperience = struct {
    progress: f32,
    level: i32,
    total_experience: i32,
};

pub const CSetHealth = struct {
    health: f32,
    food: i32,
    food_saturation: f32,
};

pub const CSetSelectedSlot = struct {
    slot: u8,
};

pub const CSetPassengers = struct {
    entity_id: i32,
    passengers: []const i32,
};

pub const CSetPlayerInventory = struct {
    slot: i32,
    item: []const u8,
};

pub const TeamMethod = enum(u8) {
    create,
    remove,
    update,
    add_players,
    remove_players,
};

pub const TeamParameters = struct {
    display_name: []const u8,
    options: u8,
    nametag_visibility: []const u8,
    collision_rule: []const u8,
    color: i32,
    player_prefix: []const u8,
    player_suffix: []const u8,
};

pub const CSetPlayerTeam = struct {
    team_name: []const u8,
    method: TeamMethod,
    parameters: ?TeamParameters,
    players: []const []const u8,
};

pub const CSetSimulationDistance = struct {
    simulation_distance: i32,
};

pub const CUpdateTime = struct {
    game_time: i64,
    clock_updates: []const struct { i32, i64, f32, f32 },
};

pub const CTitleText = struct {
    title: []const u8,
};

pub const CTitleAnimation = struct {
    fade_in_ticks: i32,
    stay_ticks: i32,
    fade_out_ticks: i32,
};

pub const CPlayShowDialog = struct {
    dialog: []const u8,
};

pub const CSoundEffect = struct {
    sound_event: []const u8,
    sound_category: i32,
    position: struct { f64, f64, f64 },
    volume: f32,
    pitch: f32,
    seed: i64,
};

pub const CSpawnEntity = struct {
    entity_id: i32,
    entity_uuid: Uuid,
    r_type: i32,
    position: struct { f64, f64, f64 },
    velocity: []const u8,
    pitch: u8,
    yaw: u8,
    head_yaw: u8,
    data: i32,
};

pub const CStopSound = struct {
    sound_id: ?[]const u8,
    category: ?[]const u8,
};

pub const CStoreCookie = struct {
    key: []const u8,
    payload: []const u8,
};

pub const CSubtitle = struct {
    subtitle: []const u8,
};

pub const CSystemChatMessage = struct {
    content: []const u8,
    overlay: bool,
};

pub const CTabList = struct {
    header: []const u8,
    footer: []const u8,
};

pub const CTagQueryResponse = struct {
    transaction_id: i32,
    nbt_bytes: []const u8,
};

pub const CTakeItemEntity = struct {
    entity_id: i32,
    collector_entity_id: i32,
    stack_amount: i32,
};

pub const CTeleportEntity = struct {
    entity_id: i32,
    position: struct { f64, f64, f64 },
    delta: struct { f64, f64, f64 },
    yaw: f32,
    pitch: f32,
    relatives: []const []const u8,
    on_ground: bool,
};

pub const CTestInstanceBlockStatus = struct {
    pos: struct { i32, i32, i32 },
    status: i32,
    message: ?[]const u8,
};

pub const CTickingState = struct {
    tick_rate: f32,
    is_frozen: bool,
};

pub const CTickingStep = struct {
    tick_steps: i32,
};

pub const CTransfer = struct {
    host: []const u8,
    port: i32,
};

pub const CUnloadChunk = struct {
    x: i32,
    z: i32,
};

pub const CUpdateAdvancements = struct {
    reset: bool,
    added: []const []const u8,
    removed: []const []const u8,
    progress: []const []const u8,
    show_advancements: bool,
};

pub const AttributeModifier = struct {
    id: []const u8,
    amount: f64,
    operation: u8,
};

pub const Property = struct {
    id: i32,
    value: f64,
    modifiers: []const AttributeModifier,
};

pub const CLoginSuccess = struct {
    uuid: Uuid,
    username: []const u8,
    properties: []const Property,
    strict_error_handling: bool,
    session_id: Uuid,
};

pub const PlayerActionAddPlayer = struct {
    name: []const u8,
    properties: []const Property,
};

pub const PlayerAction = union(enum) {
    add_player: PlayerActionAddPlayer,
    initialize_chat: ?InitChat,
    update_game_mode: i32,
    update_listed: bool,
    update_latency: i32,
    update_display_name: ?[]const u8,
    update_list_order: i32,
    update_hat: bool,
};

pub const Player = struct {
    uuid: Uuid,
    actions: []const PlayerAction,
};

pub const CPlayerInfoUpdate = struct {
    actions: u8,
    players: []const Player,
};

pub const CUpdateAttributes = struct {
    entity_id: i32,
    properties: []const Property,
};

pub const CUpdateEntityPos = struct {
    entity_id: i32,
    delta: struct { f64, f64, f64 },
    on_ground: bool,
};

pub const CUpdateEntityPosRot = struct {
    entity_id: i32,
    delta: struct { f64, f64, f64 },
    yaw: u8,
    pitch: u8,
    on_ground: bool,
};

pub const CUpdateEntityRot = struct {
    entity_id: i32,
    yaw: u8,
    pitch: u8,
    on_ground: bool,
};

pub const CUpdateMobEffect = struct {
    entity_id: i32,
    effect_id: i32,
    amplifier: i32,
    duration: i32,
    flags: u8,
};

pub const CUpdateObjectives = struct {
    objective_name: []const u8,
    mode: u8,
    display_name: []const u8,
    render_type: i32,
    number_format: ?[]const u8,
};

pub const Mode = enum(u8) {
    add,
    remove,
    update,
};

pub const RenderType = enum(u8) {
    integer,
    hearts,
};

pub const CUpdateRecipes = struct {
    raw_data: []const u8,
};

pub const CUpdateScore = struct {
    entity_name: []const u8,
    objective_name: []const u8,
    value: i32,
    display_name: ?[]const u8,
    number_format: ?[]const u8,
};

pub const CUpdateTagsPlay = struct {
    tags: []const []const u8,
};

pub const WaypointOperation = enum(u8) {
    track,
    untrack,
    update,
};

pub const WaypointTargetChunk = struct {
    x: i32,
    z: i32,
};

pub const WaypointTarget = union(enum) {
    position: struct { i32, i32, i32 },
    chunk: WaypointTargetChunk,
    azimuth: f32,
    empty,
};

pub const WaypointIcon = struct {
    style: ?[]const u8,
    color: i32,
};

pub const TrackedWaypoint = struct {
    identifier: Uuid,
    icon: ?WaypointIcon,
    target: WaypointTarget,
};

pub const CWaypoint = struct {
    operation: WaypointOperation,
    waypoint: TrackedWaypoint,
};

pub const CWorldEvent = struct {
    event: i32,
    location: struct { i32, i32, i32 },
    data: i32,
    disable_relative_volume: bool,
};

pub const StatusCPingResponse = struct {
    payload: i64,
};

pub const StatusCStatusResponse = struct {
    json_response: []const u8,
};

pub const ServerboundPacket = union(enum) {
    config_s_accept_code_of_conduct,
    config_s_acknowledge_finish_config,
    config_s_client_information_config: ConfigSClientInformationConfig,
    config_s_config_cookie_response: ConfigSConfigCookieResponse,
    config_s_custom_click_action: ConfigSCustomClickAction,
    config_s_keep_alive: ConfigSKeepAlive,
    config_s_known_packs: ConfigSKnownPacks,
    config_s_plugin_message: ConfigSPluginMessage,
    config_s_config_pong: ConfigSConfigPong,
    config_s_config_resource_pack: ConfigSConfigResourcePack,
    login_s_login_cookie_response: LoginSLoginCookieResponse,
    login_s_login_acknowledged,
    login_s_login_start: LoginSLoginStart,
    login_s_login_plugin_response: LoginSLoginPluginResponse,
    s_attack: SAttack,
    s_block_entity_tag_query: SBlockEntityTagQuery,
    s_bundle_item_selected: SBundleItemSelected,
    s_change_difficulty: SChangeDifficulty,
    s_change_game_mode: SChangeGameMode,
    s_chat_ack: SChatAck,
    s_chat_command: SChatCommand,
    s_chat_command_signed: SChatCommandSigned,
    s_chat_message: SChatMessage,
    s_chunk_batch: SChunkBatch,
    s_click_slot: SClickSlot,
    s_client_command: SClientCommand,
    s_client_information_play: SClientInformationPlay,
    s_client_tick_end,
    s_close_container: SCloseContainer,
    s_command_suggestion: SCommandSuggestion,
    s_configuration_acknowledged,
    s_container_button_click: SContainerButtonClick,
    s_container_slot_state_changed: SContainerSlotStateChanged,
    s_cookie_response: SCookieResponse,
    s_custom_click_action: SCustomClickAction,
    s_custom_payload: SCustomPayload,
    s_debug_sample_subscription: SDebugSampleSubscription,
    s_debug_subscription_request: SDebugSubscriptionRequest,
    s_edit_book: SEditBook,
    s_entity_tag_query: SEntityTagQuery,
    s_interact: SInteract,
    s_jigsaw_generate: SJigsawGenerate,
    s_keep_alive: SKeepAlive,
    s_lock_difficulty: SLockDifficulty,
    s_move_vehicle: SMoveVehicle,
    s_paddle_boat: SPaddleBoat,
    s_pick_item_from_block: SPickItemFromBlock,
    s_pick_item_from_entity: SPickItemFromEntity,
    s_play_ping_request: SPlayPingRequest,
    s_place_recipe: SPlaceRecipe,
    s_player_abilities: SPlayerAbilities,
    s_player_action: SPlayerAction,
    s_player_command: SPlayerCommand,
    s_set_player_ground: SSetPlayerGround,
    s_player_input: SPlayerInput,
    s_player_loaded,
    s_player_position: SPlayerPosition,
    s_player_position_rotation: SPlayerPositionRotation,
    s_player_rotation: SPlayerRotation,
    s_player_session: SPlayerSession,
    s_play_pong: SPlayPong,
    s_recipe_book_change_settings: SRecipeBookChangeSettings,
    s_recipe_book_seen_recipe: SRecipeBookSeenRecipe,
    s_rename_item: SRenameItem,
    s_play_resource_pack: SPlayResourcePack,
    s_seen_advancement: SSeenAdvancement,
    s_select_trade: SSelectTrade,
    s_set_beacon: SSetBeacon,
    s_set_command_block: SSetCommandBlock,
    s_set_command_minecart: SSetCommandMinecart,
    s_set_creative_slot: SSetCreativeSlot,
    s_set_game_rule: SSetGameRule,
    s_set_held_item: SSetHeldItem,
    s_set_jigsaw_block: SSetJigsawBlock,
    s_set_structure_block: SSetStructureBlock,
    s_set_test_block: SSetTestBlock,
    s_spectate_entity: SSpectateEntity,
    s_teleport_to_entity: STeleportToEntity,
    s_test_instance_block_action: STestInstanceBlockAction,
    s_update_sign: SUpdateSign,
    s_use_item: SUseItem,
    s_use_item_on: SUseItemOn,
    status_s_status_ping_request: StatusSStatusPingRequest,
    status_s_status_request,
    unknown,
};

pub const ClientboundPacket = union(enum) {
    config_c_config_add_resource_pack: ConfigCConfigAddResourcePack,
    config_c_config_clear_dialog,
    config_c_code_of_conduct: ConfigCCodeOfConduct,
    config_c_config_disconnect: ConfigCConfigDisconnect,
    config_c_cookie_request: ConfigCCookieRequest,
    config_c_config_custom_report_details: ConfigCConfigCustomReportDetails,
    config_c_feature_flags: ConfigCFeatureFlags,
    config_c_finish_config,
    config_c_known_packs: ConfigCKnownPacks,
    config_c_config_ping: ConfigCConfigPing,
    config_c_plugin_message: ConfigCPluginMessage,
    config_c_config_post_effects: ConfigCConfigPostEffects,
    config_c_registry_data: ConfigCRegistryData,
    config_c_config_remove_resource_pack: ConfigCConfigRemoveResourcePack,
    config_c_config_reset_chat,
    config_c_config_server_links: ConfigCConfigServerLinks,
    config_c_config_show_dialog: ConfigCConfigShowDialog,
    config_c_store_cookie: ConfigCStoreCookie,
    config_c_transfer: ConfigCTransfer,
    config_c_update_tags: ConfigCUpdateTags,
    login_c_login_cookie_request: LoginCLoginCookieRequest,
    login_c_login_disconnect: LoginCLoginDisconnect,
    login_c_login_plugin_request: LoginCLoginPluginRequest,
    login_c_set_compression: LoginCSetCompression,
    c_acknowledge_block_change: CAcknowledgeBlockChange,
    c_action_bar: CActionBar,
    c_add_resource_pack: CAddResourcePack,
    c_award_stats: CAwardStats,
    c_set_block_destroy_stage: CSetBlockDestroyStage,
    c_block_entity_data: CBlockEntityData,
    c_block_event: CBlockEvent,
    c_block_update: CBlockUpdate,
    c_boss_event: CBossEvent,
    c_bundle_delimiter,
    c_center_chunk: CCenterChunk,
    c_change_difficulty: CChangeDifficulty,
    c_chunk_batch_end: CChunkBatchEnd,
    c_chunk_batch_start,
    c_chunks_biomes: CChunksBiomes,
    c_play_clear_dialog,
    c_clear_title: CClearTitle,
    c_close_container: CCloseContainer,
    c_combat_death: CCombatDeath,
    c_combat_enter,
    c_combat_end: CCombatEnd,
    c_command_suggestions: CCommandSuggestions,
    c_commands: CCommands,
    c_play_cookie_request: CPlayCookieRequest,
    c_custom_chat_completions: CCustomChatCompletions,
    c_custom_payload: CCustomPayload,
    c_play_custom_report_details: CPlayCustomReportDetails,
    c_damage_event: CDamageEvent,
    c_debug_block_value: CDebugBlockValue,
    c_debug_chunk_value: CDebugChunkValue,
    c_debug_entity_value: CDebugEntityValue,
    c_debug_event: CDebugEvent,
    c_debug_sample: CDebugSample,
    c_delete_chat: CDeleteChat,
    c_play_disconnect: CPlayDisconnect,
    c_disguised_chat_message: CDisguisedChatMessage,
    c_display_objective: CDisplayObjective,
    c_entity_animation: CEntityAnimation,
    c_set_entity_metadata: CSetEntityMetadata,
    c_entity_sound_effect: CEntitySoundEffect,
    c_entity_status: CEntityStatus,
    c_entity_velocity: CEntityVelocity,
    c_explosion: CExplosion,
    c_game_event: CGameEvent,
    c_game_rule_values: CGameRuleValues,
    c_game_test_highlight_pos: CGameTestHighlightPos,
    c_head_rot: CHeadRot,
    c_hurt_animation: CHurtAnimation,
    c_initialize_world_border: CInitializeWorldBorder,
    c_item_cooldown: CItemCooldown,
    c_keep_alive: CKeepAlive,
    c_level_event: CLevelEvent,
    c_light_update: CLightUpdate,
    c_login: CLogin,
    c_low_disk_space_warning,
    c_map_item_data: CMapItemData,
    c_merchant_offers: CMerchantOffers,
    c_move_minecart_along_track: CMoveMinecartAlongTrack,
    c_move_vehicle: CMoveVehicle,
    c_multi_block_update: CMultiBlockUpdate,
    c_open_book: COpenBook,
    c_open_mount_screen: COpenMountScreen,
    c_open_screen: COpenScreen,
    c_open_sign_editor: COpenSignEditor,
    c_particle: CParticle,
    c_play_ping: CPlayPing,
    c_ping_response: CPingResponse,
    c_place_ghost_recipe: CPlaceGhostRecipe,
    c_player_abilities: CPlayerAbilities,
    c_player_chat_message: CPlayerChatMessage,
    c_player_info_update: CPlayerInfoUpdate,
    c_player_look_at: CPlayerLookAt,
    c_player_position: CPlayerPosition,
    c_remove_player_info: CRemovePlayerInfo,
    c_player_rotation: CPlayerRotation,
    c_player_spawn_position: CPlayerSpawnPosition,
    c_post_effects: CPostEffects,
    c_projectile_power: CProjectilePower,
    c_recipe_book_add: CRecipeBookAdd,
    c_recipe_book_remove: CRecipeBookRemove,
    c_recipe_book_settings: CRecipeBookSettings,
    c_remove_entities: CRemoveEntities,
    c_remove_mob_effect: CRemoveMobEffect,
    c_remove_resource_pack: CRemoveResourcePack,
    c_reset_score: CResetScore,
    c_respawn: CRespawn,
    c_select_advancements_tab: CSelectAdvancementsTab,
    c_server_data: CServerData,
    c_play_server_links: CPlayServerLinks,
    c_set_border_center: CSetBorderCenter,
    c_set_border_lerp_size: CSetBorderLerpSize,
    c_set_border_size: CSetBorderSize,
    c_set_border_warning_delay: CSetBorderWarningDelay,
    c_set_border_warning_distance: CSetBorderWarningDistance,
    c_set_camera: CSetCamera,
    c_set_chunk_cache_radius: CSetChunkCacheRadius,
    c_set_container_content: CSetContainerContent,
    c_set_container_property: CSetContainerProperty,
    c_set_container_slot: CSetContainerSlot,
    c_set_cursor_item: CSetCursorItem,
    c_set_entity_link: CSetEntityLink,
    c_set_equipment: CSetEquipment,
    c_set_experience: CSetExperience,
    c_set_health: CSetHealth,
    c_set_passengers: CSetPassengers,
    c_set_player_inventory: CSetPlayerInventory,
    c_set_player_team: CSetPlayerTeam,
    c_set_simulation_distance: CSetSimulationDistance,
    c_update_time: CUpdateTime,
    c_title_text: CTitleText,
    c_title_animation: CTitleAnimation,
    c_play_show_dialog: CPlayShowDialog,
    c_sound_effect: CSoundEffect,
    c_spawn_entity: CSpawnEntity,
    c_start_configuration,
    c_stop_sound: CStopSound,
    c_store_cookie: CStoreCookie,
    c_subtitle: CSubtitle,
    c_tab_list: CTabList,
    c_tag_query_response: CTagQueryResponse,
    c_take_item_entity: CTakeItemEntity,
    c_teleport_entity: CTeleportEntity,
    c_test_instance_block_status: CTestInstanceBlockStatus,
    c_ticking_state: CTickingState,
    c_ticking_step: CTickingStep,
    c_transfer: CTransfer,
    c_unload_chunk: CUnloadChunk,
    c_update_advancements: CUpdateAdvancements,
    c_update_attributes: CUpdateAttributes,
    c_update_entity_pos: CUpdateEntityPos,
    c_update_entity_pos_rot: CUpdateEntityPosRot,
    c_update_entity_rot: CUpdateEntityRot,
    c_update_mob_effect: CUpdateMobEffect,
    c_update_objectives: CUpdateObjectives,
    c_update_recipes: CUpdateRecipes,
    c_update_score: CUpdateScore,
    c_waypoint: CWaypoint,
    c_world_event: CWorldEvent,
    status_c_ping_response: StatusCPingResponse,
    status_c_status_response: StatusCStatusResponse,
    unknown,
};
