// Generated by tools/gen.zig, do not edit.

const text = @import("text.zig");
const item_stack = @import("item_stack.zig");

pub const TextComponent = text.TextComponent;
pub const ItemStack = item_stack.ItemStack;

/// Represents the layout and button configuration of a dialog.
pub const DialogType = enum(u8) {
    /// A simple dialog with a single "OK" button.
    notice,
    /// A dialog with "Yes" and "No" buttons.
    confirmation,
    /// A scrollable list of custom buttons.
    multi_action,
    /// A list of buttons that open other registered dialogs.
    dialog_list,
    /// A dedicated menu for displaying server-related links.
    server_links,
};

/// Represents an element in the main content area of a dialog.
pub const DialogBody = union(enum) {
    /// A simple text message.
    plain_message: TextComponent,
    /// A visual item display.
    item: ItemStack,
};

/// A checkbox input control.
pub const DialogInputBool = struct {
    label: TextComponent,
    default_value: bool,
};

/// A text field input control.
pub const DialogInputText = struct {
    label: TextComponent,
    placeholder: TextComponent,
    default_value: []const u8,
};

/// A numerical range slider input control.
pub const DialogInputNumberRange = struct {
    label: TextComponent,
    min_value: f32,
    max_value: f32,
    initial_value: f32,
    step: f32,
    label_format: ?[]const u8,
};

/// A multiple-choice selection input control.
pub const DialogInputSingleOption = struct {
    label: TextComponent,
    options: []const TextComponent,
    initial_index: u32,
};

/// Represents an interactive input control in a dialog.
pub const DialogInput = union(enum) {
    /// A checkbox for true/false states.
    bool: DialogInputBool,
    /// A simple string input field.
    text: DialogInputText,
    /// A slider for numerical input within a range.
    number_range: DialogInputNumberRange,
    /// A multiple-choice selection button.
    single_option: DialogInputSingleOption,
};

/// Defines what happens after a dialog is closed.
pub const AfterAction = enum(u8) {
    /// Returns the player to the previous screen (e.g., keeping an inventory open).
    peek,
    /// Closes all open screens.
    pop,
};

/// Represents a custom server-side action.
pub const CustomClickAction = struct {
    /// A unique identifier for the action (sent back to the server).
    id: []const u8,
    /// Optional binary data to send with the action.
    payload: ?[]const u8,
};

/// Represents an action triggered by a button click.
pub const Action = union(enum) {
    /// Opens an external URL.
    open_url: []const u8,
    /// Triggers a custom server-side callback with an ID and optional payload.
    custom_click: CustomClickAction,
};

/// Represents a clickable button in a dialog.
pub const ActionButton = struct {
    text: TextComponent,
    tooltip: ?TextComponent,
    width: ?u32,
    action: Action,
};

/// Built-in link types recognized by the Java Edition client.
pub const LinkType = enum(u8) {
    bug_report,
    community_guidelines,
    support,
    status,
    feedback,
    community,
    website,
    forums,
    news,
    announcements,
};

/// The label for a link, which can be a built-in type or custom text.
pub const LinkLabel = union(enum) {
    /// A built-in link type with a predefined icon/label.
    built_in: LinkType,
    /// A custom text component label.
    custom: TextComponent,
};

/// Represents a link displayed in a Java Edition dialog.
pub const Link = struct {
    /// The label to display for the link.
    label: LinkLabel,
    /// The URL the link points to.
    url: []const u8,
};

/// Represents a dialog shown to a Java Edition player.
pub const Dialog = struct {
    /// The main title of the dialog.
    title: TextComponent,
    /// The layout type of the dialog.
    type: DialogType,
    /// A list of body elements to display in the main area.
    body: []const DialogBody,
    /// A list of interactive input controls.
    inputs: []const DialogInput,
    /// A list of clickable buttons (for multi-action and other types).
    buttons: []const ActionButton,
    /// A list of links (primarily for server-links type).
    links: []const Link,
    /// What to do after the dialog is closed.
    after_action: ?AfterAction,
    /// Whether the player can exit the dialog using the Esc key.
    can_close_with_escape: bool,
    /// The text shown on buttons that link to/open this dialog.
    external_title: ?TextComponent,
};
