// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const common = @import("common.zig");
const item_stack = @import("item_stack.zig");
const world = @import("world.zig");
const permission = @import("permission.zig");
const text = @import("text.zig");
const gui = @import("gui.zig");
const forms = @import("forms.zig");
const java_dialogs = @import("java_dialogs.zig");
const java_packets = @import("java_packets.zig");
const bedrock_packets = @import("bedrock_packets.zig");
const uuid = @import("uuid.zig");
const status_effect = @import("status_effect.zig");
const scoreboard = @import("scoreboard.zig");
const advancement = @import("advancement.zig");
const damage_types = @import("damage_types.zig");
const statistics = @import("statistics.zig");
const inventory = @import("inventory.zig");
const sounds = @import("sounds.zig");
const particles = @import("particles.zig");
const entity_statuses = @import("entity_statuses.zig");

pub const Hand = common.Hand;
pub const Position = common.Position;
pub const GameMode = common.GameMode;
pub const BlockPos = common.BlockPos;
pub const ItemStack = item_stack.ItemStack;
pub const World = world.World;
pub const Entity = world.Entity;
pub const RayTraceBlockResult = world.RayTraceBlockResult;
pub const RayTraceEntityResult = world.RayTraceEntityResult;
pub const PermissionLevel = permission.PermissionLevel;
pub const TextComponent = text.TextComponent;
pub const Gui = gui.Gui;
pub const Form = forms.Form;
pub const Dialog = java_dialogs.Dialog;
pub const JavaPacket = java_packets.ClientboundPacket;
pub const BedrockPacket = bedrock_packets.ClientboundPacket;
pub const Uuid = uuid.Uuid;
pub const StatusEffectType = status_effect.StatusEffectType;
pub const StatusEffectInstance = status_effect.StatusEffectInstance;
pub const Scoreboard = scoreboard.Scoreboard;
pub const BedrockScoreboard = scoreboard.BedrockScoreboard;
pub const AdvancementProgress = advancement.AdvancementProgress;
pub const DamageType = damage_types.DamageType;
pub const StatisticCategory = statistics.StatisticCategory;
pub const CustomStatistic = statistics.CustomStatistic;
pub const Inventory = inventory.Inventory;
pub const PlayerInventory = inventory.PlayerInventory;
pub const Sound = sounds.Sound;
pub const SoundCategory = sounds.SoundCategory;
pub const Particle = particles.Particle;
pub const EntityStatus = entity_statuses.EntityStatus;

/// Represents per-player weather condition overrides.
pub const PlayerWeather = enum(u8) {
    clear,
    downfall,
};

/// Types of projectiles that can be launched by a player.
pub const ProjectileType = enum(u8) {
    arrow,
    snowball,
    egg,
    ender_pearl,
    splash_potion,
    fireball,
    small_fireball,
    trident,
    wind_charge,
};

/// Types of clientbound game events.
pub const ClientGameEvent = enum(u8) {
    no_respawn_block_available,
    begin_raining,
    end_raining,
    change_game_mode,
    win_game,
    demo_event,
    arrow_hit_player,
    rain_level_change,
    thunder_level_change,
    play_pufferfish_string_sound,
    play_elder_guardian_mob_appearance,
    enabled_respawn_screen,
    limited_crafting,
    start_waiting_chunks,
};

/// Built-in known server link types displayed in the client Escape pause menu.
pub const KnownServerLink = enum(u8) {
    bug_report,
    community_guidelines,
    support,
    status,
    feedback,
    community,
    website,
    forums,
    news,
    announcements,
};

/// Label for a server link: either a built-in standard link type or a custom text component.
pub const ServerLinkLabel = union(enum) {
    known: KnownServerLink,
    custom: TextComponent,
};

/// Represents a server link entry with a label and destination URL.
pub const ServerLink = struct {
    label: ServerLinkLabel,
    url: []const u8,
};

/// Various abilities a player can have.
pub const PlayerAbilities = struct {
    /// Whether the player is invulnerable to damage.
    invulnerable: bool,
    /// Whether the player is currently flying.
    flying: bool,
    /// Whether the player is allowed to fly.
    allow_flying: bool,
    /// Whether the player is in creative mode.
    creative: bool,
    /// Whether the player can modify the world.
    allow_modify_world: bool,
    /// The speed at which the player flies.
    fly_speed: f32,
    /// The speed at which the player walks.
    walk_speed: f32,
};

/// Represents a player's skin textures and metadata.
pub const PlayerSkin = struct {
    /// The base64-encoded texture data (usually JSON containing skin/cape URLs).
    value: []const u8,
    /// The optional signature for the texture data.
    signature: ?[]const u8,
};

/// Represents which skin parts are visible.
pub const SkinParts = packed struct(u8) {
    cape: bool = false,
    jacket: bool = false,
    left_sleeve: bool = false,
    right_sleeve: bool = false,
    left_pants_leg: bool = false,
    right_pants_leg: bool = false,
    hat: bool = false,
    _: u1 = 0,
};

/// Represents the various abilities a Bedrock Edition player can have.
pub const BedrockAbility = enum(u8) {
    /// Whether the player can build.
    build,
    /// Whether the player can mine blocks.
    mine,
    /// Whether the player can use doors and switches.
    doors_and_switches,
    /// Whether the player can open containers.
    open_containers,
    /// Whether the player can attack other players.
    attack_players,
    /// Whether the player can attack mobs.
    attack_mobs,
    /// Whether the player can use operator commands.
    operator_commands,
    /// Whether the player can teleport.
    teleport,
    /// Whether the player is invulnerable.
    invulnerable,
    /// Whether the player is currently flying.
    flying,
    /// Whether the player is allowed to fly.
    may_fly,
    /// Whether the player has instant build (creative).
    instabuild,
    /// Whether the player can use lightning-related abilities.
    lightning,
    /// The speed at which the player flies.
    fly_speed,
    /// The speed at which the player walks.
    walk_speed,
    /// Whether the player is muted.
    muted,
    /// Whether the player is a world builder.
    world_builder,
    /// Whether the player has no-clip enabled.
    no_clip,
    /// Whether the player is a privileged builder.
    privileged_builder,
    /// The speed at which the player flies vertically.
    vertical_fly_speed,
};

/// Represents the various status flags a Bedrock Edition entity can have.
/// These flags control client-side rendering and behavior.
pub const BedrockStatusFlag = enum(u8) {
    /// Whether the entity is currently on fire.
    on_fire,
    /// Whether the entity is sneaking.
    sneaking,
    /// Whether the entity is riding another entity.
    riding,
    /// Whether the entity is sprinting.
    sprinting,
    /// Whether the entity is using an item (e.g., eating, blocking).
    using_item,
    /// Whether the entity is invisible.
    invisible,
    /// Whether the entity is tempted by an item.
    tempted,
    /// Whether the entity is in love (breeding).
    in_love,
    /// Whether the entity is saddled.
    saddled,
    /// Whether the entity is powered (e.g., charged creeper).
    powered,
    /// Whether the entity is ignited.
    ignited,
    /// Whether the entity is a baby.
    baby,
    /// Whether the entity is currently converting to another type.
    converting,
    /// Whether the entity is in a critical state.
    critical,
    /// Whether to show the entity's name tag.
    show_name,
    /// Whether to always show the entity's name tag.
    always_show_name,
    /// Whether the entity has no AI.
    no_ai,
    /// Whether the entity is silent.
    silent,
    /// Whether the entity is climbing a wall.
    wall_climbing,
    /// Whether the entity is climbing.
    climb,
    /// Whether the entity is swimming.
    swim,
    /// Whether the entity is flying.
    fly,
    /// Whether the entity is walking.
    walk,
    /// Whether the entity is resting.
    resting,
    /// Whether the entity is sitting.
    sitting,
    /// Whether the entity is angry.
    angry,
    /// Whether the entity is interested.
    interested,
    /// Whether the entity is charged.
    charged,
    /// Whether the entity is tamed.
    tamed,
    /// Whether the entity is orphaned.
    orphaned,
    /// Whether the entity is leashed.
    leashed,
    /// Whether the entity is sheared.
    sheared,
    /// Whether the entity is gliding (elytra).
    gliding,
    /// Whether the entity is an elder (e.g., elder guardian).
    elder,
    /// Whether the entity is moving.
    moving,
    /// Whether the entity is breathing.
    breathing,
    /// Whether the entity has a chest (e.g., donkey).
    chested,
    /// Whether the entity is stackable.
    stackable,
    /// Whether to show the bottom of the entity.
    show_bottom,
    /// Whether the entity is standing.
    standing,
    /// Whether the entity is shaking.
    shaking,
    /// Whether the entity is idling.
    idling,
    /// Whether the entity is casting (e.g., evoker).
    casting,
    /// Whether the entity is charging an attack.
    charging,
    /// Whether the entity is controlled by a keyboard.
    keyboard_controlled,
    /// Whether the entity is performing a power jump.
    power_jump,
    /// Whether the entity is dashing.
    dash,
    /// Whether the entity is lingering.
    lingering,
    /// Whether the entity has collision.
    has_collision,
    /// Whether the entity has gravity.
    has_gravity,
    /// Whether the entity is immune to fire.
    fire_immune,
    /// Whether the entity is dancing.
    dancing,
    /// Whether the entity is enchanted.
    enchanted,
    /// Whether a trident will return to the entity.
    return_trident,
    /// Whether the container is private.
    container_private,
    /// Whether the entity is transforming.
    transforming,
    /// Whether the entity damages nearby mobs.
    damage_nearby_mobs,
    /// Whether the entity is swimming.
    swimming,
    /// Whether the entity has been bribed.
    bribed,
    /// Whether the entity is pregnant.
    pregnant,
    /// Whether the entity is laying an egg.
    laying_egg,
    /// Whether a passenger can pick up the entity.
    passenger_can_pick,
    /// Whether the entity is transitioning to sitting.
    transition_sitting,
    /// Whether the entity is eating.
    eating,
    /// Whether the entity is laying down.
    laying_down,
    /// Whether the entity is sneezing.
    sneezing,
    /// Whether the entity is trusting.
    trusting,
    /// Whether the entity is rolling.
    rolling,
    /// Whether the entity is scared.
    scared,
    /// Whether the entity is in scaffolding.
    in_scaffolding,
    /// Whether the entity is over scaffolding.
    over_scaffolding,
    /// Whether the entity is descending through a block.
    descend_through_block,
    /// Whether the entity is blocking.
    blocking,
    /// Whether the entity is transitioning to blocking.
    transition_blocking,
    /// Whether the entity is blocked using a shield.
    blocked_using_shield,
    /// Whether the entity is blocked using a damaged shield.
    blocked_using_damaged_shield,
    /// Whether the entity is sleeping.
    sleeping,
    /// Whether the entity wants to wake up.
    wants_to_wake,
    /// Whether the entity shows interest in trading.
    trade_interest,
    /// Whether the entity can break doors.
    door_breaker,
    /// Whether the entity is breaking an obstruction.
    breaking_obstruction,
    /// Whether the entity can open doors.
    door_opener,
    /// Whether the entity is a captain (raid).
    captain,
    /// Whether the entity is stunned.
    stunned,
    /// Whether the entity is roaring.
    roaring,
    /// Whether the entity has a delayed attack.
    delayed_attack,
    /// Whether the entity is avoiding mobs.
    avoiding_mobs,
    /// Whether the entity is avoiding a block.
    avoiding_block,
    /// Whether the entity is facing a target for a ranged attack.
    facing_target_to_range_attack,
    /// Whether the entity is hidden when invisible.
    hidden_when_invisible,
    /// Whether the entity is in a UI.
    in_ui,
    /// Whether the entity is stalking.
    stalking,
    /// Whether the entity is emoting.
    emoting,
    /// Whether the entity is celebrating.
    celebrating,
    /// Whether the entity is admiring (piglin).
    admiring,
    /// Whether the entity is celebrating a special event.
    celebrating_special,
    /// Whether the entity is out of control.
    out_of_control,
    /// Whether the entity is performing a ram attack.
    ram_attack,
    /// Whether the entity is playing dead.
    playing_dead,
    /// Whether the entity is in an ascending block.
    in_ascending_block,
    /// Whether the entity is over a descending block.
    over_descending_block,
    /// Whether the entity is croaking (frog).
    croaking,
    /// Whether the entity is digesting a mob.
    digest_mob,
    /// Whether the entity has a jump goal.
    jump_goal,
    /// Whether the entity is emerging.
    emerging,
    /// Whether the entity is sniffing.
    sniffing,
    /// Whether the entity is digging.
    digging,
    /// Whether the entity is performing a sonic boom.
    sonic_boom,
    /// Whether the entity has a dash timeout.
    has_dash_timeout,
    /// Whether the entity is pushed towards the closest space.
    push_towards_closest_space,
    /// Whether the entity is scenting.
    scenting,
    /// Whether the entity is rising.
    rising,
    /// Whether the entity is feeling happy.
    feeling_happy,
    /// Whether the entity is searching.
    searching,
    /// Whether the entity is crawling.
    crawling,
    /// Whether the entity's body rotation is blocked.
    body_rotation_blocked,
    /// Whether the entity is rendered when invisible.
    render_when_invisible,
    /// Whether the entity's body rotation is axis-aligned.
    body_rotation_axis_aligned,
    /// Whether the entity is collidable.
    collidable,
    /// Whether the entity is air-controlled via WASD.
    wasd_air_controlled,
    /// Whether only the server can authorize a dismount.
    does_server_auth_only_dismount,
    /// Whether the body rotation always follows the head.
    body_rotation_always_follows_head,
    /// Whether the entity can use vertical movement actions.
    can_use_vertical_movement_action,
    /// Whether rotation is locked to the vehicle.
    rotation_locked_to_vehicle,
};

/// Represents a specific version of the Minecraft Java Edition protocol.
pub const JavaMinecraftVersion = enum(u8) {
    v_1_7_2,
    v_1_7_6,
    v_1_8,
    v_1_9,
    v_1_9_1,
    v_1_9_2,
    v_1_9_3,
    v_1_10,
    v_1_11,
    v_1_11_1,
    v_1_12,
    v_1_12_1,
    v_1_12_2,
    v_1_13,
    v_1_13_1,
    v_1_13_2,
    v_1_14,
    v_1_14_1,
    v_1_14_2,
    v_1_14_3,
    v_1_14_4,
    v_1_15,
    v_1_15_1,
    v_1_15_2,
    v_1_16,
    v_1_16_1,
    v_1_16_2,
    v_1_16_3,
    v_1_16_4,
    v_1_17,
    v_1_17_1,
    v_1_18,
    v_1_18_2,
    v_1_19,
    v_1_19_1,
    v_1_19_3,
    v_1_19_4,
    v_1_20,
    v_1_20_2,
    v_1_20_3,
    v_1_20_5,
    v_1_21,
    v_1_21_2,
    v_1_21_4,
    v_1_21_5,
    v_1_21_6,
    v_1_21_7,
    v_1_21_9,
    v_1_21_11,
    v_26_1,
    v_26_2,
    v_26_3,
    unknown,
};

/// Represents a specific version of the Minecraft Bedrock Edition protocol.
pub const BedrockMinecraftVersion = enum(u8) {
    v_1_21,
    v_1_26_30,
    unknown,
};

/// The chat visibility settings for a player.
pub const ChatMode = enum(u8) {
    /// Chat is fully enabled.
    enabled,
    /// Only system messages and commands are shown.
    commands_only,
    /// Chat is completely hidden.
    hidden,
};

/// Represents settings for a Java Edition player.
pub const JavaPlayerSettings = struct {
    /// The player's preferred language (e.g., \"en_us\").
    locale: []const u8,
    /// The maximum distance at which chunks are rendered.
    view_distance: u8,
    /// The player's chat visibility settings.
    chat_mode: ChatMode,
    /// Whether chat colors are enabled.
    chat_colors: bool,
    /// The player's skin configuration options.
    skin_parts: SkinParts,
    /// The player's dominant hand (left or right).
    main_hand: Hand,
    /// Whether text filtering is enabled.
    text_filtering: bool,
    /// Whether the player wants to appear in the server list.
    server_listing: bool,
};

/// Represents the operating system of a Bedrock Edition client.
pub const BedrockDeviceOs = enum(u8) {
    android,
    ios,
    osx,
    amazon,
    gear_vr,
    holo_lens,
    windows_10,
    win_32,
    dedicated,
    tv_os,
    playstation,
    nintendo,
    xbox,
    windows_phone,
    linux,
    /// Fallback for unrecognized operating systems.
    unknown,
};

/// Represents the input mode used by a Bedrock Edition client.
pub const BedrockInputMode = enum(u8) {
    /// Unknown input mode.
    unknown,
    /// Mouse and keyboard.
    mouse,
    /// Touch screen.
    touch,
    /// Game controller.
    game_pad,
    /// Motion-based controller.
    motion_controller,
};

/// Represents the UI profile used by a Bedrock Edition client.
pub const BedrockUiProfile = enum(u8) {
    /// Classic desktop UI.
    classic,
    /// Pocket/Mobile optimized UI.
    pocket,
    /// Unknown UI profile.
    unknown,
};

/// Represents the graphics mode used by a Bedrock Edition client.
pub const BedrockGraphicsMode = enum(u8) {
    simple,
    fancy,
    ray_traced,
    unknown,
};

/// Represents settings and client data for a Bedrock Edition player.
pub const BedrockPlayerSettings = struct {
    /// The client's specific game version string.
    game_version: []const u8,
    /// The operating system of the client device.
    device_os: BedrockDeviceOs,
    /// A unique identifier for the client device.
    device_id: []const u8,
    /// The model name of the client device.
    device_model: []const u8,
    /// The player's preferred language code (e.g., \"en_US\").
    language_code: []const u8,
    /// The input mode currently used by the player.
    current_input_mode: BedrockInputMode,
    /// The default input mode for the client device.
    default_input_mode: BedrockInputMode,
    /// The UI layout profile used by the client.
    ui_profile: BedrockUiProfile,
    /// The current GUI scale setting.
    gui_scale: i32,
    /// Whether the player is in Editor mode.
    is_editor_mode: bool,
    /// The maximum view distance the client supports.
    max_view_distance: i32,
    /// The memory tier of the client device (indicates performance level).
    memory_tier: i32,
    /// The graphics mode used by the client.
    graphics_mode: BedrockGraphicsMode,
    /// The player's unique PlayFab identifier.
    playfab_id: []const u8,
    /// A random 64-bit ID generated by the client.
    client_random_id: i64,
    /// Platform-specific offline identifier.
    platform_offline_id: []const u8,
    /// Platform-specific online identifier.
    platform_online_id: []const u8,
    /// The unique ID of the player's current skin.
    skin_id: []const u8,
    /// The model arm size (e.g., \"wide\" or \"slim\").
    arm_size: []const u8,
    /// Whether the player is using a Character Creator (Persona) skin.
    is_persona_skin: bool,
    /// Whether the skin is a premium (paid) skin.
    is_premium_skin: bool,
    /// Whether the skin is from a trusted source.
    is_trusted_skin: bool,
};

/// Protocol-level disconnect reasons for Minecraft Bedrock Edition.
pub const BedrockDisconnectReason = enum(u8) {
    unknown,
    cant_connect_no_internet,
    no_permissions,
    unrecoverable_error,
    third_party_blocked,
    third_party_no_internet,
    third_party_bad_ip,
    third_party_no_server_or_server_locked,
    version_mismatch,
    skin_issue,
    invite_session_not_found,
    edu_level_settings_missing,
    local_server_not_found,
    legacy_disconnect,
    user_leave_game_attempted,
    platform_locked_skins_error,
    realms_world_unassigned,
    realms_server_cant_connect,
    realms_server_hidden,
    realms_server_disabled_beta,
    realms_server_disabled,
    cross_platform_disabled,
    cant_connect,
    session_not_found,
    client_settings_incompatible_with_server,
    server_full,
    invalid_platform_skin,
    edition_version_mismatch,
    edition_mismatch,
    level_newer_than_exe_version,
    no_fail_occurred,
    banned_skin,
    timeout,
    server_not_found,
    outdated_server,
    outdated_client,
    no_premium_platform,
    multiplayer_disabled,
    no_wifi,
    world_corruption,
    no_reason,
    disconnected,
    invalid_player,
    logged_in_other_location,
    server_id_conflict,
    not_allowed,
    not_authenticated,
    invalid_tenant,
    unknown_packet,
    unexpected_packet,
    invalid_command_request_packet,
    host_suspended,
    login_packet_no_request,
    login_packet_no_cert,
    missing_client,
    kicked,
    kicked_for_exploit,
    kicked_for_idle,
    resource_pack_problem,
    incompatible_pack,
    out_of_storage,
    invalid_level,
    disconnect_packet,
    block_mismatch,
    invalid_heights,
    invalid_widths,
    connection_lost,
    zombie_connection,
    shutdown,
    reason_not_set,
    loading_state_timeout,
    resource_pack_loading_failed,
    searching_for_session_loading_screen_failed,
    nether_net_protocol_version,
    subsystem_status_error,
    empty_auth_from_discovery,
    empty_url_from_discovery,
    expired_auth_from_discovery,
    unknown_signal_service_sign_in_failure,
    xbl_join_lobby_failure,
    unspecified_client_instance_disconnection,
    nether_net_session_not_found,
    nether_net_create_peer_connection,
    nether_net_ice,
    nether_net_connect_request,
    nether_net_connect_response,
    nether_net_negotiation_timeout,
    nether_net_inactivity_timeout,
    stale_connection_being_replaced,
    realms_session_not_found,
    bad_packet,
    nether_net_failed_to_create_offer,
    nether_net_failed_to_create_answer,
    nether_net_failed_to_set_local_description,
    nether_net_failed_to_set_remote_description,
    nether_net_negotiation_timeout_waiting_for_response,
    nether_net_negotiation_timeout_waiting_for_accept,
    nether_net_incoming_connection_ignored,
    nether_net_signaling_parsing_failure,
    nether_net_signaling_unknown_error,
    nether_net_signaling_unicast_delivery_failed,
    nether_net_signaling_broadcast_delivery_failed,
    nether_net_signaling_generic_delivery_failed,
    editor_mismatch_editor_world,
    editor_mismatch_vanilla_world,
    world_transfer_not_primary_client,
    request_server_shutdown,
    client_game_setup_cancelled,
    client_game_setup_failed,
    no_venue,
    nether_net_signaling_signin_failed,
    session_access_denied,
    service_signin_issue,
    nether_net_no_signaling_channel,
    nether_net_not_logged_in,
    nether_net_client_signaling_error,
    sub_client_login_disabled,
    deep_link_trying_to_open_demo_world_while_signed_in,
    async_join_task_denied,
    realms_timeline_required,
    guest_without_host,
    failed_to_join_experience,
    nether_net_data_channel_closed,
    discovery_environment_mismatch,
    host_without_keys,
    host_signed_out,
    script_watchdog_exception,
    script_memory_limit_exceeded,
    storage_low_during_gameplay,
    storage_full_during_gameplay,
    level_storage_corruption,
    edition_mismatch_vanilla_to_edu,
    edition_mismatch_edu_to_vanilla,
    editor_mismatch_editor_to_vanilla,
    editor_mismatch_vanilla_to_editor,
    deny_listed,
    nonce_missing,
    nonce_not_found,
    nonce_expired,
    nonce_not_valid,
    host_disconnected,
    editor_join_intent_policy_failure,
    nether_net_identity_not_allowed,
    invalid_name,
    expired_token,
    host_accepts_no_type_of_auth,
    not_authenticated_fast_fail,
    editor_not_allowed,
};

/// Policy for tearing down the player's network connection.
pub const SocketTeardownPolicy = enum(u8) {
    /// Send the disconnect packet and gracefully close the connection.
    graceful,
    /// Send the disconnect packet and close the socket immediately.
    immediate_close,
    /// Terminate the connection immediately without sending any disconnect packet.
    drop_connection,
};

/// Options for disconnecting a Java Edition player.
pub const JavaKickOptions = struct {
    /// The formatted text component displayed on the Java disconnect screen.
    reason: TextComponent,
    /// Whether to log the kick in the server console (default: true).
    log_to_console: bool,
    /// How the connection is closed (default: graceful).
    teardown_policy: SocketTeardownPolicy,
};

/// Options for disconnecting a Bedrock Edition player.
pub const BedrockKickOptions = struct {
    /// Protocol level disconnect code (default: kicked).
    reason: BedrockDisconnectReason,
    /// Message displayed on the Bedrock disconnect screen (default: "").
    message: []const u8,
    /// Whether to suppress the disconnect message on the client screen (default: false).
    skip_message: bool,
    /// Filtered message string for safety/parental filters (default: "").
    filtered_message: []const u8,
    /// Whether to log the kick in the server console (default: true).
    log_to_console: bool,
    /// How the connection is closed (default: graceful).
    teardown_policy: SocketTeardownPolicy,
};

/// Options for banning a player.
pub const BanPlayerOptions = struct {
    /// Ban reason displayed to the player and stored in the ban list.
    reason: ?TextComponent,
    /// Source or authority responsible for the ban (default: "Plugin").
    source: ?[]const u8,
    /// Ban expiration in RFC-3339 format, if temporary.
    expires_at_utc: ?[]const u8,
    /// Ban duration in seconds from now, if temporary.
    duration_seconds: ?u64,
    /// Whether to immediately kick the player if currently online (default: true).
    kick_if_online: bool,
    /// Whether to log the ban action to the server console (default: true).
    log_to_console: bool,
};

/// Options for banning an IP address.
pub const BanIpOptions = struct {
    /// Ban reason stored in the IP ban list.
    reason: ?TextComponent,
    /// Source or authority responsible for the ban (default: "Plugin").
    source: ?[]const u8,
    /// Ban expiration in RFC-3339 format, if temporary.
    expires_at_utc: ?[]const u8,
    /// Ban duration in seconds from now, if temporary.
    duration_seconds: ?u64,
    /// Whether to immediately kick all online players with this IP (default: true).
    kick_matching_players: bool,
    /// Whether to log the IP ban action to the server console (default: true).
    log_to_console: bool,
};

/// A handle to a player on the server.
pub const Player = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]player";

    /// Returns the player as an entity.
    pub fn asEntity(self: Player) Entity {
        return abi.call(raw.@"[method]player.as-entity", Entity, .{abi.borrow(self)});
    }

    /// Returns the player's unique UUID as a string.
    pub fn getId(self: Player) Uuid {
        return abi.call(raw.@"[method]player.get-id", Uuid, .{abi.borrow(self)});
    }

    /// Returns the player's username.
    pub fn getName(self: Player) []const u8 {
        return abi.call(raw.@"[method]player.get-name", []const u8, .{abi.borrow(self)});
    }

    /// Basic state
    /// Returns the player's current position in the world.
    pub fn getPosition(self: Player) Position {
        return abi.call(raw.@"[method]player.get-position", Position, .{abi.borrow(self)});
    }

    /// Returns the player's current yaw (horizontal rotation).
    pub fn getYaw(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-yaw", f32, .{abi.borrow(self)});
    }

    /// Returns the player's current pitch (vertical rotation).
    pub fn getPitch(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-pitch", f32, .{abi.borrow(self)});
    }

    /// Returns the world the player is currently in.
    pub fn getWorld(self: Player) World {
        return abi.call(raw.@"[method]player.get-world", World, .{abi.borrow(self)});
    }

    /// Returns the player's current game mode.
    pub fn getGamemode(self: Player) GameMode {
        return abi.call(raw.@"[method]player.get-gamemode", GameMode, .{abi.borrow(self)});
    }

    /// Changes the player's game mode. Returns true if successful.
    pub fn setGamemode(self: Player, mode: GameMode) bool {
        return abi.call(raw.@"[method]player.set-gamemode", bool, .{ abi.borrow(self), mode });
    }

    /// Returns the player's locale (e.g., \"en_us\").
    pub fn getLocale(self: Player) []const u8 {
        return abi.call(raw.@"[method]player.get-locale", []const u8, .{abi.borrow(self)});
    }

    /// Returns the player's current ping in milliseconds.
    pub fn getPing(self: Player) u32 {
        return abi.call(raw.@"[method]player.get-ping", u32, .{abi.borrow(self)});
    }

    /// Permissions & metadata
    /// Returns the player's permission level (0-4).
    pub fn getPermissionLevel(self: Player) PermissionLevel {
        return abi.call(raw.@"[method]player.get-permission-level", PermissionLevel, .{abi.borrow(self)});
    }

    /// Sets the player's permission level.
    pub fn setPermissionLevel(self: Player, level: PermissionLevel) void {
        return abi.call(raw.@"[method]player.set-permission-level", void, .{ abi.borrow(self), level });
    }

    /// Grants or denies a specific permission node for the player.
    pub fn setPermission(self: Player, node: []const u8, value: bool) void {
        return abi.call(raw.@"[method]player.set-permission", void, .{ abi.borrow(self), node, value });
    }

    /// Removes an explicitly set permission node from the player.
    pub fn unsetPermission(self: Player, node: []const u8) void {
        return abi.call(raw.@"[method]player.unset-permission", void, .{ abi.borrow(self), node });
    }

    /// Returns `Some(true)` if granted, `Some(false)` if denied, or `None` if not set.
    pub fn hasPermissionSet(self: Player, node: []const u8) ?bool {
        return abi.call(raw.@"[method]player.has-permission-set", ?bool, .{ abi.borrow(self), node });
    }

    /// Checks if the player has a specific permission node.
    pub fn hasPermission(self: Player, node: []const u8) bool {
        return abi.call(raw.@"[method]player.has-permission", bool, .{ abi.borrow(self), node });
    }

    /// Returns the player's display name, which may include formatting.
    pub fn getDisplayName(self: Player) TextComponent {
        return abi.call(raw.@"[method]player.get-display-name", TextComponent, .{abi.borrow(self)});
    }

    /// Sets the player's display name.
    ///
    /// Consumes `display_name`.
    pub fn setDisplayName(self: Player, display_name: TextComponent) void {
        return abi.call(raw.@"[method]player.set-display-name", void, .{ abi.borrow(self), display_name });
    }

    /// Gets the player's custom tab list name.
    pub fn getTabListName(self: Player) ?TextComponent {
        return abi.call(raw.@"[method]player.get-tab-list-name", ?TextComponent, .{abi.borrow(self)});
    }

    /// Sets the player's custom tab list name.
    pub fn setTabListName(self: Player, name: ?TextComponent) void {
        return abi.call(raw.@"[method]player.set-tab-list-name", void, .{ abi.borrow(self), name });
    }

    /// Messaging & titles
    /// Sends a system message to the player's chat.
    ///
    /// Consumes `text_`.
    pub fn sendSystemMessage(self: Player, text_: TextComponent, overlay: bool) void {
        return abi.call(raw.@"[method]player.send-system-message", void, .{ abi.borrow(self), text_, overlay });
    }

    /// Deletes a signed chat message from the player's chat window using its 256-byte signature.
    pub fn deleteMessageBySignature(self: Player, signature: []const u8) void {
        return abi.call(raw.@"[method]player.delete-message-by-signature", void, .{ abi.borrow(self), signature });
    }

    /// Deletes a signed chat message from the player's chat window using its signature cache ID.
    pub fn deleteMessageById(self: Player, signature_id: i32) void {
        return abi.call(raw.@"[method]player.delete-message-by-id", void, .{ abi.borrow(self), signature_id });
    }

    /// Sets the header and footer of the player's Tab list.
    ///
    /// Consumes `header`.
    /// Consumes `footer`.
    pub fn setTabListHeaderFooter(self: Player, header: TextComponent, footer: TextComponent) void {
        return abi.call(raw.@"[method]player.set-tab-list-header-footer", void, .{ abi.borrow(self), header, footer });
    }

    /// Sets the sorting order of the player in the Tab list.
    pub fn setTabListOrder(self: Player, order: i32) void {
        return abi.call(raw.@"[method]player.set-tab-list-order", void, .{ abi.borrow(self), order });
    }

    /// Sets the latency (ping) shown for the player in the Tab list.
    pub fn setTabListLatency(self: Player, latency: i32) void {
        return abi.call(raw.@"[method]player.set-tab-list-latency", void, .{ abi.borrow(self), latency });
    }

    /// Sets whether the player is visible in the Tab list.
    pub fn setTabListListed(self: Player, listed: bool) void {
        return abi.call(raw.@"[method]player.set-tab-list-listed", void, .{ abi.borrow(self), listed });
    }

    /// Shows a large title on the player's screen.
    ///
    /// Consumes `text_`.
    pub fn showTitle(self: Player, text_: TextComponent) void {
        return abi.call(raw.@"[method]player.show-title", void, .{ abi.borrow(self), text_ });
    }

    /// Shows a smaller subtitle on the player's screen.
    ///
    /// Consumes `text_`.
    pub fn showSubtitle(self: Player, text_: TextComponent) void {
        return abi.call(raw.@"[method]player.show-subtitle", void, .{ abi.borrow(self), text_ });
    }

    /// Shows a message in the action bar area.
    ///
    /// Consumes `text_`.
    pub fn showActionbar(self: Player, text_: TextComponent) void {
        return abi.call(raw.@"[method]player.show-actionbar", void, .{ abi.borrow(self), text_ });
    }

    /// Sets the fade-in, stay, and fade-out times for titles.
    pub fn sendTitleAnimation(self: Player, fade_in: i32, stay: i32, fade_out: i32) void {
        return abi.call(raw.@"[method]player.send-title-animation", void, .{ abi.borrow(self), fade_in, stay, fade_out });
    }

    /// Camera & Spectating
    /// Sets the player's camera to view from the perspective of another entity.
    /// If `entity` is `none`, the camera is reset back to the player.
    pub fn setCamera(self: Player, entity: ?Entity) void {
        return abi.call(raw.@"[method]player.set-camera", void, .{ abi.borrow(self), entity });
    }

    /// Sets the player's camera to view from the perspective of an entity with the given entity ID.
    /// If `entity-id` is the player's own entity ID, the camera is reset back to the player.
    pub fn setCameraEntityId(self: Player, entity_id: u32) void {
        return abi.call(raw.@"[method]player.set-camera-entity-id", void, .{ abi.borrow(self), entity_id });
    }

    /// Gets the entity ID of the entity that the player's camera is currently attached to,
    /// or the player's own entity ID if the camera has not been overridden.
    pub fn getCameraEntityId(self: Player) u32 {
        return abi.call(raw.@"[method]player.get-camera-entity-id", u32, .{abi.borrow(self)});
    }

    /// Resets the player's camera back to their own perspective.
    pub fn resetCamera(self: Player) void {
        return abi.call(raw.@"[method]player.reset-camera", void, .{abi.borrow(self)});
    }

    /// Audio & Particles
    /// Plays a sound effect for this player at their current location.
    pub fn playSound(self: Player, sound: Sound, category: SoundCategory, volume: f32, pitch: f32) void {
        return abi.call(raw.@"[method]player.play-sound", void, .{ abi.borrow(self), sound, category, volume, pitch });
    }

    /// Plays a sound effect for this player at a specific location.
    pub fn playSoundAt(self: Player, pos: Position, sound: Sound, category: SoundCategory, volume: f32, pitch: f32) void {
        return abi.call(raw.@"[method]player.play-sound-at", void, .{ abi.borrow(self), pos, sound, category, volume, pitch });
    }

    /// Stops a sound effect from playing for this player.
    pub fn stopSound(self: Player, sound: ?Sound, category: ?SoundCategory) void {
        return abi.call(raw.@"[method]player.stop-sound", void, .{ abi.borrow(self), sound, category });
    }

    /// Plays a custom resource pack sound identifier for this player at their current location.
    pub fn playCustomSound(self: Player, sound_name: []const u8, category: SoundCategory, volume: f32, pitch: f32) void {
        return abi.call(raw.@"[method]player.play-custom-sound", void, .{ abi.borrow(self), sound_name, category, volume, pitch });
    }

    /// Plays a custom resource pack sound identifier for this player at a specific location.
    pub fn playCustomSoundAt(self: Player, pos: Position, sound_name: []const u8, category: SoundCategory, volume: f32, pitch: f32) void {
        return abi.call(raw.@"[method]player.play-custom-sound-at", void, .{ abi.borrow(self), pos, sound_name, category, volume, pitch });
    }

    /// Stops a custom sound identifier from playing for this player.
    pub fn stopCustomSound(self: Player, sound_name: ?[]const u8, category: ?SoundCategory) void {
        return abi.call(raw.@"[method]player.stop-custom-sound", void, .{ abi.borrow(self), sound_name, category });
    }

    /// Spawns particles visible only to this player.
    pub fn spawnParticles(self: Player, particle: Particle, pos: Position, count: u32, offset: Position, max_speed: f32) void {
        return abi.call(raw.@"[method]player.spawn-particles", void, .{ abi.borrow(self), particle, pos, count, offset, max_speed });
    }

    /// Visuals & Client Overrides
    /// Sends a temporary fake block change to the player's client without modifying the server world.
    pub fn sendBlockChange(self: Player, pos: BlockPos, block_id: u16) void {
        return abi.call(raw.@"[method]player.send-block-change", void, .{ abi.borrow(self), pos, block_id });
    }

    /// Resets a temporary fake block change by resending the actual world block at that position.
    pub fn resetBlockChange(self: Player, pos: BlockPos) void {
        return abi.call(raw.@"[method]player.reset-block-change", void, .{ abi.borrow(self), pos });
    }

    /// Sends a hurt / damage-tilt animation to the player's client (causes screen shake in the given yaw direction).
    pub fn sendHurtAnimation(self: Player, yaw: f32) void {
        return abi.call(raw.@"[method]player.send-hurt-animation", void, .{ abi.borrow(self), yaw });
    }

    /// Opens a written book interface for the player from the specified hand.
    pub fn openBook(self: Player, hand: Hand) void {
        return abi.call(raw.@"[method]player.open-book", void, .{ abi.borrow(self), hand });
    }

    /// Forces the sign text editor to open for the player at the specified sign block position.
    pub fn openSignEditor(self: Player, pos: BlockPos, is_front_text: bool) void {
        return abi.call(raw.@"[method]player.open-sign-editor", void, .{ abi.borrow(self), pos, is_front_text });
    }

    /// Velocity & Physics
    /// Sets the player's velocity / motion vector.
    pub fn setVelocity(self: Player, velocity: Position) void {
        return abi.call(raw.@"[method]player.set-velocity", void, .{ abi.borrow(self), velocity });
    }

    /// Applies directional knockback impulse to the player.
    pub fn applyKnockback(self: Player, strength: f64, x: f64, z: f64) void {
        return abi.call(raw.@"[method]player.apply-knockback", void, .{ abi.borrow(self), strength, x, z });
    }

    /// Movement Lock & Freezing
    /// Sets whether the player's movement is locked (frozen in place) for cutscenes and NPC dialogues.
    pub fn setMovementLocked(self: Player, locked: bool) void {
        return abi.call(raw.@"[method]player.set-movement-locked", void, .{ abi.borrow(self), locked });
    }

    /// Returns whether the player's movement is currently locked.
    pub fn isMovementLocked(self: Player) bool {
        return abi.call(raw.@"[method]player.is-movement-locked", bool, .{abi.borrow(self)});
    }

    /// Sets the number of freeze ticks on the player (controlling the powdered snow / frostbite screen vignette).
    pub fn setFreezeTicks(self: Player, ticks: i32) void {
        return abi.call(raw.@"[method]player.set-freeze-ticks", void, .{ abi.borrow(self), ticks });
    }

    /// Returns the current number of freeze ticks on the player.
    pub fn getFreezeTicks(self: Player) i32 {
        return abi.call(raw.@"[method]player.get-freeze-ticks", i32, .{abi.borrow(self)});
    }

    /// Sends custom server links to the player (displayed in the client Esc pause menu in 1.21+).
    pub fn setServerLinks(self: Player, links: []const ServerLink) void {
        return abi.call(raw.@"[method]player.set-server-links", void, .{ abi.borrow(self), links });
    }

    /// Teleport & kick
    /// Teleports the player to a position in a world.
    ///
    /// Consumes `world_`.
    pub fn teleport(self: Player, position: Position, yaw: ?f32, pitch: ?f32, world_: World) void {
        return abi.call(raw.@"[method]player.teleport", void, .{ abi.borrow(self), position, yaw, pitch, world_ });
    }

    /// Teleports the player to another world at a specific position.
    ///
    /// Consumes `world_ref`.
    pub fn teleportWorld(self: Player, world_ref: World, position: Position, yaw: ?f32, pitch: ?f32) void {
        return abi.call(raw.@"[method]player.teleport-world", void, .{ abi.borrow(self), world_ref, position, yaw, pitch });
    }

    /// Forces the player to respawn.
    pub fn respawn(self: Player) void {
        return abi.call(raw.@"[method]player.respawn", void, .{abi.borrow(self)});
    }

    /// Opens a GUI for the player.
    ///
    /// Consumes `gui_ref`.
    pub fn openGui(self: Player, gui_ref: Gui) void {
        return abi.call(raw.@"[method]player.open-gui", void, .{ abi.borrow(self), gui_ref });
    }

    /// Bans the player with the specified options.
    pub fn ban(self: Player, options: BanPlayerOptions) void {
        return abi.call(raw.@"[method]player.ban", void, .{ abi.borrow(self), options });
    }

    /// Bans the player's IP address with the specified options.
    pub fn banIp(self: Player, options: BanIpOptions) void {
        return abi.call(raw.@"[method]player.ban-ip", void, .{ abi.borrow(self), options });
    }

    /// Transfers the player to another server.
    pub fn transfer(self: Player, host: []const u8, port: u16) void {
        return abi.call(raw.@"[method]player.transfer", void, .{ abi.borrow(self), host, port });
    }

    /// Status Effects
    /// Gives a status effect to the player.
    pub fn addEffect(self: Player, effect: StatusEffectInstance) void {
        return abi.call(raw.@"[method]player.add-effect", void, .{ abi.borrow(self), effect });
    }

    /// Removes a status effect from the player.
    pub fn removeEffect(self: Player, effect: StatusEffectType) void {
        return abi.call(raw.@"[method]player.remove-effect", void, .{ abi.borrow(self), effect });
    }

    /// Clears all active status effects from the player.
    pub fn clearEffects(self: Player) void {
        return abi.call(raw.@"[method]player.clear-effects", void, .{abi.borrow(self)});
    }

    /// Checks if a status effect is currently applied to the player.
    pub fn hasEffect(self: Player, effect: StatusEffectType) bool {
        return abi.call(raw.@"[method]player.has-effect", bool, .{ abi.borrow(self), effect });
    }

    /// Returns the status effect instance applied to the player, if any.
    pub fn getEffect(self: Player, effect: StatusEffectType) ?StatusEffectInstance {
        return abi.call(raw.@"[method]player.get-effect", ?StatusEffectInstance, .{ abi.borrow(self), effect });
    }

    /// Returns all status effects currently applied to the player.
    pub fn getActiveEffects(self: Player) []const StatusEffectInstance {
        return abi.call(raw.@"[method]player.get-active-effects", []const StatusEffectInstance, .{abi.borrow(self)});
    }

    /// Health & Damage
    /// Heals the player by a specified amount.
    pub fn heal(self: Player, amount: f32) void {
        return abi.call(raw.@"[method]player.heal", void, .{ abi.borrow(self), amount });
    }

    /// Deals damage to the player by a specified amount with a damage type.
    pub fn damage(self: Player, amount: f32, damage_type: DamageType) void {
        return abi.call(raw.@"[method]player.damage", void, .{ abi.borrow(self), amount, damage_type });
    }

    /// Kills the player instantly.
    pub fn kill(self: Player) void {
        return abi.call(raw.@"[method]player.kill", void, .{abi.borrow(self)});
    }

    /// Statistics
    /// Gets the value of a statistic for this player in the given category and ID.
    pub fn getStatistic(self: Player, category: StatisticCategory, stat_id: i32) i32 {
        return abi.call(raw.@"[method]player.get-statistic", i32, .{ abi.borrow(self), category, stat_id });
    }

    /// Sets the value of a statistic for this player in the given category and ID.
    pub fn setStatistic(self: Player, category: StatisticCategory, stat_id: i32, value: i32) void {
        return abi.call(raw.@"[method]player.set-statistic", void, .{ abi.borrow(self), category, stat_id, value });
    }

    /// Increments the value of a statistic for this player in the given category and ID.
    pub fn incrementStatistic(self: Player, category: StatisticCategory, stat_id: i32, amount: i32) void {
        return abi.call(raw.@"[method]player.increment-statistic", void, .{ abi.borrow(self), category, stat_id, amount });
    }

    /// Gets the value of a custom statistic for this player.
    pub fn getCustomStatistic(self: Player, stat: CustomStatistic) i32 {
        return abi.call(raw.@"[method]player.get-custom-statistic", i32, .{ abi.borrow(self), stat });
    }

    /// Sets the value of a custom statistic for this player.
    pub fn setCustomStatistic(self: Player, stat: CustomStatistic, value: i32) void {
        return abi.call(raw.@"[method]player.set-custom-statistic", void, .{ abi.borrow(self), stat, value });
    }

    /// Increments the value of a custom statistic for this player.
    pub fn incrementCustomStatistic(self: Player, stat: CustomStatistic, amount: i32) void {
        return abi.call(raw.@"[method]player.increment-custom-statistic", void, .{ abi.borrow(self), stat, amount });
    }

    /// Sends the player's updated statistics packet to the client.
    pub fn sendStats(self: Player) void {
        return abi.call(raw.@"[method]player.send-stats", void, .{abi.borrow(self)});
    }

    /// Gets the team name that this player belongs to on their active scoreboard, if any.
    pub fn getTeam(self: Player) ?[]const u8 {
        return abi.call(raw.@"[method]player.get-team", ?[]const u8, .{abi.borrow(self)});
    }

    /// Cooldowns
    /// Starts an item cooldown for a specific item group name.
    pub fn startCooldown(self: Player, group: []const u8, duration_ticks: i32) void {
        return abi.call(raw.@"[method]player.start-cooldown", void, .{ abi.borrow(self), group, duration_ticks });
    }

    /// Returns the cooldown progress (0.0 to 1.0) for a specific item group.
    pub fn getCooldown(self: Player, group: []const u8) f32 {
        return abi.call(raw.@"[method]player.get-cooldown", f32, .{ abi.borrow(self), group });
    }

    /// Checks if a specific item group is currently on cooldown.
    pub fn isOnCooldown(self: Player, group: []const u8) bool {
        return abi.call(raw.@"[method]player.is-on-cooldown", bool, .{ abi.borrow(self), group });
    }

    /// Abilities & Flight
    /// Sets whether the player is allowed to fly.
    pub fn setAllowFlight(self: Player, allowed: bool) void {
        return abi.call(raw.@"[method]player.set-allow-flight", void, .{ abi.borrow(self), allowed });
    }

    /// Sets the player's flying speed.
    pub fn setFlySpeed(self: Player, speed: f32) void {
        return abi.call(raw.@"[method]player.set-fly-speed", void, .{ abi.borrow(self), speed });
    }

    /// Sets the player's walking speed.
    pub fn setWalkSpeed(self: Player, speed: f32) void {
        return abi.call(raw.@"[method]player.set-walk-speed", void, .{ abi.borrow(self), speed });
    }

    /// Sets whether the player is invulnerable to damage.
    pub fn setInvulnerable(self: Player, invulnerable: bool) void {
        return abi.call(raw.@"[method]player.set-invulnerable", void, .{ abi.borrow(self), invulnerable });
    }

    /// Inventory
    /// Returns the player's inventory handle for managing main storage, armor, and equipment.
    pub fn getInventory(self: Player) PlayerInventory {
        return abi.call(raw.@"[method]player.get-inventory", PlayerInventory, .{abi.borrow(self)});
    }

    /// Returns the player's ender chest inventory handle.
    pub fn getEnderChest(self: Player) Inventory {
        return abi.call(raw.@"[method]player.get-ender-chest", Inventory, .{abi.borrow(self)});
    }

    /// Returns the index of the currently selected hotbar slot (0-8).
    pub fn getSelectedSlot(self: Player) u8 {
        return abi.call(raw.@"[method]player.get-selected-slot", u8, .{abi.borrow(self)});
    }

    /// Returns the item currently in the specified hand.
    pub fn getItemInHand(self: Player, hand: Hand) ?ItemStack {
        return abi.call(raw.@"[method]player.get-item-in-hand", ?ItemStack, .{ abi.borrow(self), hand });
    }

    /// Returns the item in the specified inventory slot.
    pub fn getInventoryItem(self: Player, slot: u8) ?ItemStack {
        return abi.call(raw.@"[method]player.get-inventory-item", ?ItemStack, .{ abi.borrow(self), slot });
    }

    /// Sets the item in the specified hand.
    pub fn setItemInHand(self: Player, hand: Hand, stack: ?ItemStack) void {
        return abi.call(raw.@"[method]player.set-item-in-hand", void, .{ abi.borrow(self), hand, stack });
    }

    /// Sets the item in the specified inventory slot.
    pub fn setInventoryItem(self: Player, slot: u8, stack: ?ItemStack) void {
        return abi.call(raw.@"[method]player.set-inventory-item", void, .{ abi.borrow(self), slot, stack });
    }

    /// Ender Chest Inventory
    /// Returns the item in the specified ender chest slot (0-26).
    pub fn getEnderChestItem(self: Player, slot: u8) ?ItemStack {
        return abi.call(raw.@"[method]player.get-ender-chest-item", ?ItemStack, .{ abi.borrow(self), slot });
    }

    /// Sets the item in the specified ender chest slot (0-26).
    pub fn setEnderChestItem(self: Player, slot: u8, stack: ?ItemStack) void {
        return abi.call(raw.@"[method]player.set-ender-chest-item", void, .{ abi.borrow(self), slot, stack });
    }

    /// Clears all items from the player's ender chest.
    pub fn clearEnderChest(self: Player) void {
        return abi.call(raw.@"[method]player.clear-ender-chest", void, .{abi.borrow(self)});
    }

    /// Opens the player's ender chest inventory screen for them.
    pub fn openEnderChest(self: Player) void {
        return abi.call(raw.@"[method]player.open-ender-chest", void, .{abi.borrow(self)});
    }

    /// Status
    /// Returns the player's current health.
    pub fn getHealth(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-health", f32, .{abi.borrow(self)});
    }

    /// Sets the player's current health.
    pub fn setHealth(self: Player, health: f32) void {
        return abi.call(raw.@"[method]player.set-health", void, .{ abi.borrow(self), health });
    }

    /// Returns the player's maximum health.
    pub fn getMaxHealth(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-max-health", f32, .{abi.borrow(self)});
    }

    /// Sets the player's maximum health.
    pub fn setMaxHealth(self: Player, max_health: f32) void {
        return abi.call(raw.@"[method]player.set-max-health", void, .{ abi.borrow(self), max_health });
    }

    /// Returns the player's food level (0-20).
    pub fn getFoodLevel(self: Player) u8 {
        return abi.call(raw.@"[method]player.get-food-level", u8, .{abi.borrow(self)});
    }

    /// Sets the player's food level.
    pub fn setFoodLevel(self: Player, food_level: u8) void {
        return abi.call(raw.@"[method]player.set-food-level", void, .{ abi.borrow(self), food_level });
    }

    /// Returns the player's food saturation level.
    pub fn getSaturation(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-saturation", f32, .{abi.borrow(self)});
    }

    /// Sets the player's food saturation level.
    pub fn setSaturation(self: Player, saturation: f32) void {
        return abi.call(raw.@"[method]player.set-saturation", void, .{ abi.borrow(self), saturation });
    }

    /// Returns the player's food exhaustion level.
    pub fn getExhaustion(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-exhaustion", f32, .{abi.borrow(self)});
    }

    /// Sets the player's food exhaustion level.
    pub fn setExhaustion(self: Player, exhaustion: f32) void {
        return abi.call(raw.@"[method]player.set-exhaustion", void, .{ abi.borrow(self), exhaustion });
    }

    /// Returns the player's current absorption amount.
    pub fn getAbsorption(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-absorption", f32, .{abi.borrow(self)});
    }

    /// Sets the player's current absorption amount.
    pub fn setAbsorption(self: Player, absorption: f32) void {
        return abi.call(raw.@"[method]player.set-absorption", void, .{ abi.borrow(self), absorption });
    }

    /// Returns the player's total experience level.
    pub fn getExperienceLevel(self: Player) i32 {
        return abi.call(raw.@"[method]player.get-experience-level", i32, .{abi.borrow(self)});
    }

    /// Returns the player's progress toward the next level (0.0 to 1.0).
    pub fn getExperienceProgress(self: Player) f32 {
        return abi.call(raw.@"[method]player.get-experience-progress", f32, .{abi.borrow(self)});
    }

    /// Returns the total experience points the player has.
    pub fn getExperiencePoints(self: Player) i32 {
        return abi.call(raw.@"[method]player.get-experience-points", i32, .{abi.borrow(self)});
    }

    /// Sets the player's total experience level.
    pub fn setExperienceLevel(self: Player, level: i32) void {
        return abi.call(raw.@"[method]player.set-experience-level", void, .{ abi.borrow(self), level });
    }

    /// Sets the player's progress toward the next level.
    pub fn setExperienceProgress(self: Player, progress: f32) void {
        return abi.call(raw.@"[method]player.set-experience-progress", void, .{ abi.borrow(self), progress });
    }

    /// Sets the player's total experience points.
    pub fn setExperiencePoints(self: Player, points: i32) void {
        return abi.call(raw.@"[method]player.set-experience-points", void, .{ abi.borrow(self), points });
    }

    /// Adds experience levels to the player.
    pub fn addExperienceLevels(self: Player, levels: i32) void {
        return abi.call(raw.@"[method]player.add-experience-levels", void, .{ abi.borrow(self), levels });
    }

    /// Adds experience points to the player.
    pub fn addExperiencePoints(self: Player, points: i32) void {
        return abi.call(raw.@"[method]player.add-experience-points", void, .{ abi.borrow(self), points });
    }

    /// Returns whether the player is currently flying.
    pub fn isFlying(self: Player) bool {
        return abi.call(raw.@"[method]player.is-flying", bool, .{abi.borrow(self)});
    }

    /// Sets whether the player should be flying.
    pub fn setFlying(self: Player, flying: bool) void {
        return abi.call(raw.@"[method]player.set-flying", void, .{ abi.borrow(self), flying });
    }

    /// Returns the player's current abilities.
    pub fn getAbilities(self: Player) PlayerAbilities {
        return abi.call(raw.@"[method]player.get-abilities", PlayerAbilities, .{abi.borrow(self)});
    }

    /// Updates the player's abilities.
    pub fn setAbilities(self: Player, abilities: PlayerAbilities) void {
        return abi.call(raw.@"[method]player.set-abilities", void, .{ abi.borrow(self), abilities });
    }

    /// Returns the player's IP address.
    pub fn getIp(self: Player) []const u8 {
        return abi.call(raw.@"[method]player.get-ip", []const u8, .{abi.borrow(self)});
    }

    /// Returns the player's current skin textures.
    pub fn getSkin(self: Player) ?PlayerSkin {
        return abi.call(raw.@"[method]player.get-skin", ?PlayerSkin, .{abi.borrow(self)});
    }

    /// Updates the player's skin textures.
    /// Note: this only updates the fields, it doesn't reload the skin.
    pub fn setSkin(self: Player, skin: PlayerSkin) void {
        return abi.call(raw.@"[method]player.set-skin", void, .{ abi.borrow(self), skin });
    }

    /// Returns which skin parts are visible.
    pub fn getSkinParts(self: Player) SkinParts {
        return abi.call(raw.@"[method]player.get-skin-parts", SkinParts, .{abi.borrow(self)});
    }

    /// Sets which skin parts are visible.
    pub fn setSkinParts(self: Player, parts: SkinParts) void {
        return abi.call(raw.@"[method]player.set-skin-parts", void, .{ abi.borrow(self), parts });
    }

    /// Per-Player Environment & Overrides
    /// Overrides the time of day shown to this player.
    pub fn setPlayerTime(self: Player, time: u64, relative: bool) void {
        return abi.call(raw.@"[method]player.set-player-time", void, .{ abi.borrow(self), time, relative });
    }

    /// Resets the player's time to sync with the server world time.
    pub fn resetPlayerTime(self: Player) void {
        return abi.call(raw.@"[method]player.reset-player-time", void, .{abi.borrow(self)});
    }

    /// Returns the custom time set for this player, if any.
    pub fn getPlayerTime(self: Player) ?u64 {
        return abi.call(raw.@"[method]player.get-player-time", ?u64, .{abi.borrow(self)});
    }

    /// Checks if the custom player time is relative to the world time.
    pub fn isPlayerTimeRelative(self: Player) bool {
        return abi.call(raw.@"[method]player.is-player-time-relative", bool, .{abi.borrow(self)});
    }

    /// Overrides the weather condition shown to this player.
    pub fn setPlayerWeather(self: Player, weather: PlayerWeather) void {
        return abi.call(raw.@"[method]player.set-player-weather", void, .{ abi.borrow(self), weather });
    }

    /// Resets the player's weather to match the server world weather.
    pub fn resetPlayerWeather(self: Player) void {
        return abi.call(raw.@"[method]player.reset-player-weather", void, .{abi.borrow(self)});
    }

    /// Returns the custom weather set for this player, if any.
    pub fn getPlayerWeather(self: Player) ?PlayerWeather {
        return abi.call(raw.@"[method]player.get-player-weather", ?PlayerWeather, .{abi.borrow(self)});
    }

    /// Sets the position where the player's compass points.
    pub fn setCompassTarget(self: Player, pos: Position) void {
        return abi.call(raw.@"[method]player.set-compass-target", void, .{ abi.borrow(self), pos });
    }

    /// Returns the position where the player's compass currently points.
    pub fn getCompassTarget(self: Player) Position {
        return abi.call(raw.@"[method]player.get-compass-target", Position, .{abi.borrow(self)});
    }

    /// Sets the player's custom respawn / bed location.
    pub fn setRespawnLocation(self: Player, pos: Position) void {
        return abi.call(raw.@"[method]player.set-respawn-location", void, .{ abi.borrow(self), pos });
    }

    /// Returns the player's custom respawn / bed location, if set.
    pub fn getRespawnLocation(self: Player) ?Position {
        return abi.call(raw.@"[method]player.get-respawn-location", ?Position, .{abi.borrow(self)});
    }

    /// Hides another player from this player's view (vanish).
    ///
    /// Consumes `other`.
    pub fn hidePlayer(self: Player, other: Player) void {
        return abi.call(raw.@"[method]player.hide-player", void, .{ abi.borrow(self), other });
    }

    /// Shows a previously hidden player to this player.
    ///
    /// Consumes `other`.
    pub fn showPlayer(self: Player, other: Player) void {
        return abi.call(raw.@"[method]player.show-player", void, .{ abi.borrow(self), other });
    }

    /// Checks if this player can see another specified player.
    ///
    /// Consumes `other`.
    pub fn canSee(self: Player, other: Player) bool {
        return abi.call(raw.@"[method]player.can-see", bool, .{ abi.borrow(self), other });
    }

    /// Checks if this player can see another specified player.
    ///
    /// Consumes `other`.
    pub fn canSeePlayer(self: Player, other: Player) bool {
        return abi.call(raw.@"[method]player.can-see-player", bool, .{ abi.borrow(self), other });
    }

    /// Sets the tab list ping / latency indicator in milliseconds.
    pub fn setTabListPing(self: Player, latency_ms: i32) void {
        return abi.call(raw.@"[method]player.set-tab-list-ping", void, .{ abi.borrow(self), latency_ms });
    }

    /// Sets a client-side item cooldown overlay.
    pub fn setItemCooldown(self: Player, item_id: []const u8, ticks: i32) void {
        return abi.call(raw.@"[method]player.set-item-cooldown", void, .{ abi.borrow(self), item_id, ticks });
    }

    /// Returns the remaining cooldown ticks for an item, if active.
    pub fn getItemCooldown(self: Player, item_id: []const u8) ?i32 {
        return abi.call(raw.@"[method]player.get-item-cooldown", ?i32, .{ abi.borrow(self), item_id });
    }

    /// Checks if an item is currently on cooldown.
    pub fn hasItemCooldown(self: Player, item_id: []const u8) bool {
        return abi.call(raw.@"[method]player.has-item-cooldown", bool, .{ abi.borrow(self), item_id });
    }

    /// Performs a ray-trace from the player's eye position in looking direction to find the targeted block.
    pub fn rayTraceBlock(self: Player, max_distance: f64, include_fluids: bool) ?RayTraceBlockResult {
        return abi.call(raw.@"[method]player.ray-trace-block", ?RayTraceBlockResult, .{ abi.borrow(self), max_distance, include_fluids });
    }

    /// Performs a ray-trace from the player's eye position in looking direction to find the targeted entity.
    pub fn rayTraceEntity(self: Player, max_distance: f64) ?RayTraceEntityResult {
        return abi.call(raw.@"[method]player.ray-trace-entity", ?RayTraceEntityResult, .{ abi.borrow(self), max_distance });
    }

    /// Returns the entity currently targeted in the looking direction within the specified distance.
    pub fn getTargetEntity(self: Player, max_distance: f64) ?Entity {
        return abi.call(raw.@"[method]player.get-target-entity", ?Entity, .{ abi.borrow(self), max_distance });
    }

    /// Raycasts from the player's eyes to find the block being targeted.
    pub fn getTargetBlock(self: Player, max_distance: u32) ?Position {
        return abi.call(raw.@"[method]player.get-target-block", ?Position, .{ abi.borrow(self), max_distance });
    }

    /// Performs a raycast from the player's eyes to find the exact block and face being targeted.
    pub fn getTargetBlockExact(self: Player, max_distance: f64, include_fluids: bool) ?RayTraceBlockResult {
        return abi.call(raw.@"[method]player.get-target-block-exact", ?RayTraceBlockResult, .{ abi.borrow(self), max_distance, include_fluids });
    }

    /// Launches a projectile from the player's eyes in their line of sight.
    pub fn launchProjectile(self: Player, @"type": ProjectileType) ?Entity {
        return abi.call(raw.@"[method]player.launch-projectile", ?Entity, .{ abi.borrow(self), @"type" });
    }

    /// Advancements
    /// Returns the progress of the specified advancement for this player, if the advancement exists.
    pub fn getAdvancementProgress(self: Player, advancement_id: []const u8) ?AdvancementProgress {
        return abi.call(raw.@"[method]player.get-advancement-progress", ?AdvancementProgress, .{ abi.borrow(self), advancement_id });
    }

    /// Awards a specific criterion of an advancement to the player.
    /// Returns true if the criterion was successfully awarded (was not already completed).
    pub fn awardAdvancementCriterion(self: Player, advancement_id: []const u8, criterion: []const u8) bool {
        return abi.call(raw.@"[method]player.award-advancement-criterion", bool, .{ abi.borrow(self), advancement_id, criterion });
    }

    /// Revokes a specific criterion of an advancement from the player.
    /// Returns true if the criterion was successfully revoked (was previously completed).
    pub fn revokeAdvancementCriterion(self: Player, advancement_id: []const u8, criterion: []const u8) bool {
        return abi.call(raw.@"[method]player.revoke-advancement-criterion", bool, .{ abi.borrow(self), advancement_id, criterion });
    }

    /// Awards all criteria of the specified advancement to the player.
    /// Returns true if any criterion was newly awarded.
    pub fn awardAdvancement(self: Player, advancement_id: []const u8) bool {
        return abi.call(raw.@"[method]player.award-advancement", bool, .{ abi.borrow(self), advancement_id });
    }

    /// Revokes all criteria of the specified advancement from the player.
    /// Returns true if any criterion was newly revoked.
    pub fn revokeAdvancement(self: Player, advancement_id: []const u8) bool {
        return abi.call(raw.@"[method]player.revoke-advancement", bool, .{ abi.borrow(self), advancement_id });
    }

    /// Checks whether the player has completed the specified advancement.
    pub fn hasAdvancement(self: Player, advancement_id: []const u8) bool {
        return abi.call(raw.@"[method]player.has-advancement", bool, .{ abi.borrow(self), advancement_id });
    }

    /// Returns a list of all advancement IDs completed by this player.
    pub fn getCompletedAdvancements(self: Player) []const []const u8 {
        return abi.call(raw.@"[method]player.get-completed-advancements", []const []const u8, .{abi.borrow(self)});
    }

    /// Returns the ID of the currently selected advancement tab for this player, if any.
    pub fn getSelectedAdvancementTab(self: Player) ?[]const u8 {
        return abi.call(raw.@"[method]player.get-selected-advancement-tab", ?[]const u8, .{abi.borrow(self)});
    }

    /// Sets the selected advancement tab for this player (must be a root advancement ID).
    pub fn setSelectedAdvancementTab(self: Player, tab_id: ?[]const u8) void {
        return abi.call(raw.@"[method]player.set-selected-advancement-tab", void, .{ abi.borrow(self), tab_id });
    }

    /// Returns a Java-specific player handle, if the player is connected via Java Edition.
    ///
    /// This allows access to Java-exclusive features like sending specific packets
    /// or retrieving the client brand.
    pub fn asJava(self: Player) ?JavaPlayer {
        return abi.call(raw.@"[method]player.as-java", ?JavaPlayer, .{abi.borrow(self)});
    }

    /// Returns a Bedrock-specific player handle, if the player is connected via Bedrock Edition.
    ///
    /// This allows access to Bedrock-exclusive features like custom forms
    /// or detailed device information.
    pub fn asBedrock(self: Player) ?BedrockPlayer {
        return abi.call(raw.@"[method]player.as-bedrock", ?BedrockPlayer, .{abi.borrow(self)});
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: Player) void {
        abi.keep(Player, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: Player) void {
        abi.drop(Player, self);
    }
};

/// Represents a resource pack sent to a Java Edition player.
pub const JavaResourcePack = struct {
    /// Unique identifier for the resource pack.
    id: Uuid,
    /// The URL to the resource pack file.
    url: []const u8,
    /// The SHA1 hash (40-character hex string) of the pack.
    hash: []const u8,
    /// Whether the player is forced to accept the pack.
    forced: bool,
    /// Optional prompt message displayed in the pack acceptance screen.
    prompt_message: ?TextComponent,
};

/// Represents an individual Bedrock Edition resource pack entry.
pub const BedrockResourcePackEntry = struct {
    /// Unique identifier for the Bedrock pack.
    id: Uuid,
    /// Version string of the Bedrock pack (e.g., "1.0.0").
    version: []const u8,
    /// Size of the pack in bytes.
    size: u64,
    /// Download URL for remote Bedrock packs.
    download_url: []const u8,
    /// Optional encryption content key for encrypted packs.
    content_key: ?[]const u8,
    /// Optional sub-pack name inside the archive.
    sub_pack_name: ?[]const u8,
    /// Optional content identifier.
    content_id: ?[]const u8,
    /// Whether the pack contains client scripts.
    has_scripts: bool,
    /// Whether the pack is marked as an addon pack.
    addon_pack: bool,
    /// Whether Ray Tracing / RTX features are enabled for the pack.
    rtx_enabled: bool,
};

/// Represents the resource packs information payload sent to Bedrock clients.
pub const BedrockResourcePacksInfo = struct {
    /// If true, players cannot join without accepting packs.
    required: bool,
    /// Whether the server offers addon packs.
    has_addon_packs: bool,
    /// Whether any of the packs contain client scripts.
    has_scripts: bool,
    /// Whether vibrant visuals should be forced disabled.
    is_vibrant_visuals_force_disabled: bool,
    /// World template ID, if any.
    world_template_id: ?Uuid,
    /// World template version, if any.
    world_template_version: ?[]const u8,
    /// List of resource packs to send to the player.
    packs: []const BedrockResourcePackEntry,
};

/// A handle to a player connected via the Java Edition.
pub const JavaPlayer = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]java-player";

    /// Returns the Minecraft Java Edition version of the player.
    pub fn getVersion(self: JavaPlayer) JavaMinecraftVersion {
        return abi.call(raw.@"[method]java-player.get-version", JavaMinecraftVersion, .{abi.borrow(self)});
    }

    /// Returns the brand of the player's client (e.g., \"vanilla\", \"fabric\").
    pub fn getBrand(self: JavaPlayer) []const u8 {
        return abi.call(raw.@"[method]java-player.get-brand", []const u8, .{abi.borrow(self)});
    }

    /// Returns the server address the player used to connect.
    pub fn getServerAddress(self: JavaPlayer) []const u8 {
        return abi.call(raw.@"[method]java-player.get-server-address", []const u8, .{abi.borrow(self)});
    }

    /// Returns the player's configuration settings.
    pub fn getSettings(self: JavaPlayer) JavaPlayerSettings {
        return abi.call(raw.@"[method]java-player.get-settings", JavaPlayerSettings, .{abi.borrow(self)});
    }

    /// Sends a Java-specific clientbound packet to the player.
    pub fn sendPacket(self: JavaPlayer, packet: JavaPacket) void {
        return abi.call(raw.@"[method]java-player.send-packet", void, .{ abi.borrow(self), packet });
    }

    /// Sends a custom payload packet (plugin message) to the player.
    pub fn sendCustomPayload(self: JavaPlayer, channel: []const u8, data: []const u8) void {
        return abi.call(raw.@"[method]java-player.send-custom-payload", void, .{ abi.borrow(self), channel, data });
    }

    /// Shows a dialog to the player.
    pub fn showDialog(self: JavaPlayer, dialog: Dialog) void {
        return abi.call(raw.@"[method]java-player.show-dialog", void, .{ abi.borrow(self), dialog });
    }

    /// Clears any currently shown dialog for the player.
    pub fn clearDialog(self: JavaPlayer) void {
        return abi.call(raw.@"[method]java-player.clear-dialog", void, .{abi.borrow(self)});
    }

    /// Returns the Java scoreboard handle for this player.
    pub fn getScoreboard(self: JavaPlayer) Scoreboard {
        return abi.call(raw.@"[method]java-player.get-scoreboard", Scoreboard, .{abi.borrow(self)});
    }

    /// Resets the player's custom Java scoreboard back to the world scoreboard.
    pub fn resetScoreboard(self: JavaPlayer) void {
        return abi.call(raw.@"[method]java-player.reset-scoreboard", void, .{abi.borrow(self)});
    }

    /// Sends a resource pack to the Java player.
    pub fn sendResourcePack(self: JavaPlayer, pack: JavaResourcePack) void {
        return abi.call(raw.@"[method]java-player.send-resource-pack", void, .{ abi.borrow(self), pack });
    }

    /// Removes a specific resource pack by UUID for the Java player.
    pub fn removeResourcePack(self: JavaPlayer, id: Uuid) void {
        return abi.call(raw.@"[method]java-player.remove-resource-pack", void, .{ abi.borrow(self), id });
    }

    /// Clears all custom resource packs for the Java player.
    pub fn clearResourcePacks(self: JavaPlayer) void {
        return abi.call(raw.@"[method]java-player.clear-resource-packs", void, .{abi.borrow(self)});
    }

    /// Kicks the Java player with the specified options.
    pub fn kick(self: JavaPlayer, options: JavaKickOptions) void {
        return abi.call(raw.@"[method]java-player.kick", void, .{ abi.borrow(self), options });
    }

    /// Sends a clientbound GameEvent packet to the Java player.
    pub fn sendGameEvent(self: JavaPlayer, event: ClientGameEvent, value: f32) void {
        return abi.call(raw.@"[method]java-player.send-game-event", void, .{ abi.borrow(self), event, value });
    }

    /// Sends an entity status / animation event packet to the Java player for a specific entity ID.
    pub fn sendEntityStatus(self: JavaPlayer, entity_id: i32, status: EntityStatus) void {
        return abi.call(raw.@"[method]java-player.send-entity-status", void, .{ abi.borrow(self), entity_id, status });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: JavaPlayer) void {
        abi.keep(JavaPlayer, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: JavaPlayer) void {
        abi.drop(JavaPlayer, self);
    }
};

/// A handle to a player connected via the Bedrock Edition.
pub const BedrockPlayer = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]bedrock-player";

    /// Returns the Minecraft Bedrock Edition version of the player.
    pub fn getVersion(self: BedrockPlayer) BedrockMinecraftVersion {
        return abi.call(raw.@"[method]bedrock-player.get-version", BedrockMinecraftVersion, .{abi.borrow(self)});
    }

    /// Returns the player's configuration settings.
    pub fn getSettings(self: BedrockPlayer) BedrockPlayerSettings {
        return abi.call(raw.@"[method]bedrock-player.get-settings", BedrockPlayerSettings, .{abi.borrow(self)});
    }

    /// Returns whether a specific Bedrock-only ability is enabled for the player.
    pub fn getAbility(self: BedrockPlayer, ability: BedrockAbility) bool {
        return abi.call(raw.@"[method]bedrock-player.get-ability", bool, .{ abi.borrow(self), ability });
    }

    /// Sets whether a specific Bedrock-only ability is enabled for the player.
    pub fn setAbility(self: BedrockPlayer, ability: BedrockAbility, value: bool) void {
        return abi.call(raw.@"[method]bedrock-player.set-ability", void, .{ abi.borrow(self), ability, value });
    }

    /// Returns whether a specific Bedrock-only status flag is enabled for the player.
    ///
    /// Status flags control things like whether the player is on fire, sneaking,
    /// sprinting, or has specific visual effects.
    pub fn getStatusFlag(self: BedrockPlayer, flag: BedrockStatusFlag) bool {
        return abi.call(raw.@"[method]bedrock-player.get-status-flag", bool, .{ abi.borrow(self), flag });
    }

    /// Sets whether a specific Bedrock-only status flag is enabled for the player.
    ///
    /// This can be used to manually trigger client-side visual states.
    pub fn setStatusFlag(self: BedrockPlayer, flag: BedrockStatusFlag, value: bool) void {
        return abi.call(raw.@"[method]bedrock-player.set-status-flag", void, .{ abi.borrow(self), flag, value });
    }

    /// Sends a Bedrock-specific clientbound packet to the player.
    pub fn sendPacket(self: BedrockPlayer, packet: BedrockPacket) void {
        return abi.call(raw.@"[method]bedrock-player.send-packet", void, .{ abi.borrow(self), packet });
    }

    /// Opens a Bedrock custom form for the player.
    pub fn openForm(self: BedrockPlayer, form: Form) u32 {
        return abi.call(raw.@"[method]bedrock-player.open-form", u32, .{ abi.borrow(self), form });
    }

    /// Returns the Bedrock scoreboard handle for this player.
    pub fn getScoreboard(self: BedrockPlayer) BedrockScoreboard {
        return abi.call(raw.@"[method]bedrock-player.get-scoreboard", BedrockScoreboard, .{abi.borrow(self)});
    }

    /// Resets the player's custom Bedrock scoreboard back to the world scoreboard.
    pub fn resetScoreboard(self: BedrockPlayer) void {
        return abi.call(raw.@"[method]bedrock-player.reset-scoreboard", void, .{abi.borrow(self)});
    }

    /// Sends resource packs information to the Bedrock player.
    pub fn sendResourcePacksInfo(self: BedrockPlayer, info: BedrockResourcePacksInfo) void {
        return abi.call(raw.@"[method]bedrock-player.send-resource-packs-info", void, .{ abi.borrow(self), info });
    }

    /// Kicks the Bedrock player with the specified options.
    pub fn kick(self: BedrockPlayer, options: BedrockKickOptions) void {
        return abi.call(raw.@"[method]bedrock-player.kick", void, .{ abi.borrow(self), options });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: BedrockPlayer) void {
        abi.keep(BedrockPlayer, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: BedrockPlayer) void {
        abi.drop(BedrockPlayer, self);
    }
};

/// Returns a list of all players in a specific world.
///
/// Consumes `world_ref`.
pub fn getWorldPlayers(world_ref: World) []const Player {
    return abi.call(raw.@"get-world-players", []const Player, .{world_ref});
}

const raw = struct {
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.as-entity"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-id"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-name"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-position"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-yaw"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-pitch"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-world"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-gamemode"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-gamemode"(i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-locale"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-ping"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-permission-level"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-permission-level"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-permission"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.unset-permission"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.has-permission-set"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.has-permission"(i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-display-name"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-display-name"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-tab-list-name"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-tab-list-name"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.send-system-message"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.delete-message-by-signature"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.delete-message-by-id"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-tab-list-header-footer"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-tab-list-order"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-tab-list-latency"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-tab-list-listed"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.show-title"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.show-subtitle"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.show-actionbar"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.send-title-animation"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-camera"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-camera-entity-id"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-camera-entity-id"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.reset-camera"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.play-sound"(i32, i32, i32, f32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.play-sound-at"(i32, f64, f64, f64, i32, i32, f32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.stop-sound"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.play-custom-sound"(i32, i32, i32, i32, f32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.play-custom-sound-at"(i32, f64, f64, f64, i32, i32, i32, f32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.stop-custom-sound"(i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.spawn-particles"(i32, i32, f64, f64, f64, i32, f64, f64, f64, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.send-block-change"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.reset-block-change"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.send-hurt-animation"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.open-book"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.open-sign-editor"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-velocity"(i32, f64, f64, f64) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.apply-knockback"(i32, f64, f64, f64) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-movement-locked"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.is-movement-locked"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-freeze-ticks"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-freeze-ticks"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-server-links"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.teleport"(i32, f64, f64, f64, i32, f32, i32, f32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.teleport-world"(i32, i32, f64, f64, f64, i32, f32, i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.respawn"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.open-gui"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.ban"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i64, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.ban-ip"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i64, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.transfer"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.add-effect"(i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.remove-effect"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.clear-effects"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.has-effect"(i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-effect"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-active-effects"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.heal"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.damage"(i32, f32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.kill"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-statistic"(i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-statistic"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.increment-statistic"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-custom-statistic"(i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-custom-statistic"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.increment-custom-statistic"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.send-stats"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-team"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.start-cooldown"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-cooldown"(i32, i32, i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.is-on-cooldown"(i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-allow-flight"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-fly-speed"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-walk-speed"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-invulnerable"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-inventory"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-ender-chest"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-selected-slot"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-item-in-hand"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-inventory-item"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-item-in-hand"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-inventory-item"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-ender-chest-item"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-ender-chest-item"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.clear-ender-chest"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.open-ender-chest"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-health"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-health"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-max-health"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-max-health"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-food-level"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-food-level"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-saturation"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-saturation"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-exhaustion"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-exhaustion"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-absorption"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-absorption"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-experience-level"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-experience-progress"(i32) f32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-experience-points"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-experience-level"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-experience-progress"(i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-experience-points"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.add-experience-levels"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.add-experience-points"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.is-flying"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-flying"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-abilities"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-abilities"(i32, i32, i32, i32, i32, i32, f32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-ip"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-skin"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-skin"(i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-skin-parts"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-skin-parts"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-player-time"(i32, i64, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.reset-player-time"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-player-time"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.is-player-time-relative"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-player-weather"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.reset-player-weather"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-player-weather"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-compass-target"(i32, f64, f64, f64) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-compass-target"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-respawn-location"(i32, f64, f64, f64) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-respawn-location"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.hide-player"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.show-player"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.can-see"(i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.can-see-player"(i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-tab-list-ping"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-item-cooldown"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-item-cooldown"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.has-item-cooldown"(i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.ray-trace-block"(i32, f64, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.ray-trace-entity"(i32, f64, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-target-entity"(i32, f64, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-target-block"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-target-block-exact"(i32, f64, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.launch-projectile"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-advancement-progress"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.award-advancement-criterion"(i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.revoke-advancement-criterion"(i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.award-advancement"(i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.revoke-advancement"(i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.has-advancement"(i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-completed-advancements"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.get-selected-advancement-tab"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.set-selected-advancement-tab"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.as-java"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]player.as-bedrock"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.get-version"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.get-brand"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.get-server-address"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.get-settings"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.send-packet"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.send-custom-payload"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.show-dialog"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.clear-dialog"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.get-scoreboard"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.reset-scoreboard"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.send-resource-pack"(i32, i64, i64, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.remove-resource-pack"(i32, i64, i64) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.clear-resource-packs"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.kick"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.send-game-event"(i32, i32, f32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]java-player.send-entity-status"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.get-version"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.get-settings"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.get-ability"(i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.set-ability"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.get-status-flag"(i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.set-status-flag"(i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.send-packet"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.open-form"(i32, i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.get-scoreboard"(i32) i32;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.reset-scoreboard"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.send-resource-packs-info"(i32, i32, i32, i32, i32, i32, i64, i64, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[method]bedrock-player.kick"(i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"get-world-players"(i32, i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[resource-drop]player"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[resource-drop]java-player"(i32) void;
    extern "pumpkin:plugin/player@0.1.0" fn @"[resource-drop]bedrock-player"(i32) void;
};
