// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const item_stack = @import("item_stack.zig");

pub const ItemStack = item_stack.ItemStack;

/// Recipe category for the recipe book.
pub const RecipeCategory = enum(u8) {
    building,
    redstone,
    equipment,
    misc,
    food,
    blocks,
};

/// Represents an ingredient in a recipe.
pub const Ingredient = union(enum) {
    /// A specific item (e.g. "minecraft:diamond").
    item: []const u8,
    /// A tag group of items (e.g., "minecraft:logs").
    tag: []const u8,
    /// One of multiple specific items.
    one_of: []const []const u8,
};

/// Represents a shaped crafting recipe.
pub const ShapedRecipe = struct {
    /// The pattern of the recipe (e.g., ["# #", " s ", "# #"]).
    pattern: []const []const u8,
    /// Mapping of characters in the pattern to ingredients.
    key: []const struct { []const u8, Ingredient },
    /// The resulting item stack.
    output: ItemStack,
    /// The recipe group (optional).
    group: ?[]const u8,
    /// The recipe category in the recipe book.
    category: ?RecipeCategory,
    /// Whether to show a toast notification when the recipe is unlocked.
    show_notification: ?bool,
};

/// Represents a shapeless crafting recipe.
pub const ShapelessRecipe = struct {
    /// The list of ingredients required.
    ingredients: []const Ingredient,
    /// The resulting item stack.
    output: ItemStack,
    /// The recipe group (optional).
    group: ?[]const u8,
    /// The recipe category in the recipe book.
    category: ?RecipeCategory,
};

/// Represents a cooking recipe (Smelting, Blasting, Smoking, Campfire).
pub const CookingRecipe = struct {
    /// The ingredient to cook.
    ingredient: Ingredient,
    /// The resulting item stack.
    output: ItemStack,
    /// Experience points awarded.
    experience: f32,
    /// Cooking time in ticks.
    cooking_time: u32,
    /// The recipe group (optional).
    group: ?[]const u8,
    /// The recipe category in the recipe book.
    category: ?RecipeCategory,
};

/// Types of cooking stations.
pub const CookingType = enum(u8) {
    smelting,
    blasting,
    smoking,
    campfire,
};

/// Common interface for registering recipes.
pub const RecipeManager = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]recipe-manager";

    /// Registers a shaped crafting recipe.
    pub fn registerShaped(self: RecipeManager, id: []const u8, recipe: ShapedRecipe) void {
        return abi.call(raw.@"[method]recipe-manager.register-shaped", void, .{ abi.borrow(self), id, recipe });
    }

    /// Registers a shapeless crafting recipe.
    pub fn registerShapeless(self: RecipeManager, id: []const u8, recipe: ShapelessRecipe) void {
        return abi.call(raw.@"[method]recipe-manager.register-shapeless", void, .{ abi.borrow(self), id, recipe });
    }

    /// Registers a cooking recipe.
    pub fn registerCooking(self: RecipeManager, id: []const u8, station_type: CookingType, recipe: CookingRecipe) void {
        return abi.call(raw.@"[method]recipe-manager.register-cooking", void, .{ abi.borrow(self), id, station_type, recipe });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: RecipeManager) void {
        abi.keep(RecipeManager, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: RecipeManager) void {
        abi.drop(RecipeManager, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/recipe@0.1.0" fn @"[method]recipe-manager.register-shaped"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/recipe@0.1.0" fn @"[method]recipe-manager.register-shapeless"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/recipe@0.1.0" fn @"[method]recipe-manager.register-cooking"(i32, i32, i32, i32, i32, i32, i32, i32, f32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/recipe@0.1.0" fn @"[resource-drop]recipe-manager"(i32) void;
};
