// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");

/// Schedules a task to be executed once after the specified number of ticks.
///
/// * `handler-id`: The unique ID of the handler to call when the task executes.
/// * `delay-ticks`: The number of game ticks to wait before execution (20 ticks = 1 second).
///
/// Returns a unique task ID that can be used to cancel the task.
pub fn scheduleDelayedTask(handler_id: u32, delay_ticks: u64) u32 {
    return abi.call(raw.@"schedule-delayed-task", u32, .{ handler_id, delay_ticks });
}

/// Schedules a task to be executed repeatedly.
///
/// * `handler-id`: The unique ID of the handler to call when the task executes.
/// * `delay-ticks`: The number of game ticks to wait before the first execution.
/// * `period-ticks`: The number of game ticks between subsequent executions.
///
/// Returns a unique task ID that can be used to cancel the task.
pub fn scheduleRepeatingTask(handler_id: u32, delay_ticks: u64, period_ticks: u64) u32 {
    return abi.call(raw.@"schedule-repeating-task", u32, .{ handler_id, delay_ticks, period_ticks });
}

/// Cancels a scheduled task if it hasn't finished yet.
///
/// * `task-id`: The ID of the task to cancel.
pub fn cancelTask(task_id: u32) void {
    return abi.call(raw.@"cancel-task", void, .{task_id});
}

const raw = struct {
    extern "pumpkin:plugin/scheduler@0.1.0" fn @"schedule-delayed-task"(i32, i64) i32;
    extern "pumpkin:plugin/scheduler@0.1.0" fn @"schedule-repeating-task"(i32, i64, i64) i32;
    extern "pumpkin:plugin/scheduler@0.1.0" fn @"cancel-task"(i32) void;
};
