// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const text = @import("text.zig");
const common = @import("common.zig");

pub const TextComponent = text.TextComponent;
pub const NamedColor = common.NamedColor;

pub const RenderType = enum(u8) {
    integer,
    hearts,
};

pub const NumberFormat = union(enum) {
    blank,
    fixed: TextComponent,
};

pub const DisplaySlot = enum(u8) {
    player_list,
    sidebar,
    below_name,
    sidebar_team_black,
    sidebar_team_dark_blue,
    sidebar_team_dark_green,
    sidebar_team_dark_aqua,
    sidebar_team_dark_red,
    sidebar_team_dark_purple,
    sidebar_team_gold,
    sidebar_team_gray,
    sidebar_team_dark_gray,
    sidebar_team_blue,
    sidebar_team_green,
    sidebar_team_aqua,
    sidebar_team_red,
    sidebar_team_light_purple,
    sidebar_team_yellow,
    sidebar_team_white,
};

pub const NametagVisibility = enum(u8) {
    always,
    never,
    hide_for_other_teams,
    hide_for_own_team,
};

pub const CollisionRule = enum(u8) {
    always,
    never,
    push_other_teams,
    push_own_team,
};

pub const TeamSettings = struct {
    display_name: TextComponent,
    friendly_fire: bool,
    see_friendly_invisibles: bool,
    nametag_visibility: NametagVisibility,
    collision_rule: CollisionRule,
    color: NamedColor,
    prefix: TextComponent,
    suffix: TextComponent,
};

pub const Scoreboard = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]scoreboard";

    /// Consumes `display_name`.
    pub fn addObjective(self: Scoreboard, name: []const u8, display_name: TextComponent, render_type: RenderType, number_format: ?NumberFormat) void {
        return abi.call(raw.@"[method]scoreboard.add-objective", void, .{ abi.borrow(self), name, display_name, render_type, number_format });
    }

    /// Consumes `display_name`.
    pub fn updateObjective(self: Scoreboard, name: []const u8, display_name: TextComponent, render_type: RenderType, number_format: ?NumberFormat) void {
        return abi.call(raw.@"[method]scoreboard.update-objective", void, .{ abi.borrow(self), name, display_name, render_type, number_format });
    }

    pub fn removeObjective(self: Scoreboard, name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.remove-objective", void, .{ abi.borrow(self), name });
    }

    pub fn setDisplaySlot(self: Scoreboard, slot: DisplaySlot, objective_name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.set-display-slot", void, .{ abi.borrow(self), slot, objective_name });
    }

    pub fn clearDisplaySlot(self: Scoreboard, slot: DisplaySlot) void {
        return abi.call(raw.@"[method]scoreboard.clear-display-slot", void, .{ abi.borrow(self), slot });
    }

    pub fn updateScore(self: Scoreboard, entity_name: []const u8, objective_name: []const u8, value: i32, number_format: ?NumberFormat) void {
        return abi.call(raw.@"[method]scoreboard.update-score", void, .{ abi.borrow(self), entity_name, objective_name, value, number_format });
    }

    pub fn addScore(self: Scoreboard, entity_name: []const u8, objective_name: []const u8, delta: i32) i32 {
        return abi.call(raw.@"[method]scoreboard.add-score", i32, .{ abi.borrow(self), entity_name, objective_name, delta });
    }

    pub fn removeScore(self: Scoreboard, entity_name: []const u8, objective_name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.remove-score", void, .{ abi.borrow(self), entity_name, objective_name });
    }

    pub fn resetEntityScores(self: Scoreboard, entity_name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.reset-entity-scores", void, .{ abi.borrow(self), entity_name });
    }

    pub fn createTeam(self: Scoreboard, name: []const u8, settings: TeamSettings) void {
        return abi.call(raw.@"[method]scoreboard.create-team", void, .{ abi.borrow(self), name, settings });
    }

    pub fn removeTeam(self: Scoreboard, name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.remove-team", void, .{ abi.borrow(self), name });
    }

    pub fn updateTeam(self: Scoreboard, name: []const u8, settings: TeamSettings) void {
        return abi.call(raw.@"[method]scoreboard.update-team", void, .{ abi.borrow(self), name, settings });
    }

    pub fn addPlayerToTeam(self: Scoreboard, team_name: []const u8, player_name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.add-player-to-team", void, .{ abi.borrow(self), team_name, player_name });
    }

    pub fn removePlayerFromTeam(self: Scoreboard, team_name: []const u8, player_name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.remove-player-from-team", void, .{ abi.borrow(self), team_name, player_name });
    }

    pub fn clearTeamPlayers(self: Scoreboard, team_name: []const u8) void {
        return abi.call(raw.@"[method]scoreboard.clear-team-players", void, .{ abi.borrow(self), team_name });
    }

    pub fn getTeams(self: Scoreboard) []const []const u8 {
        return abi.call(raw.@"[method]scoreboard.get-teams", []const []const u8, .{abi.borrow(self)});
    }

    pub fn getTeam(self: Scoreboard, name: []const u8) ?TeamSettings {
        return abi.call(raw.@"[method]scoreboard.get-team", ?TeamSettings, .{ abi.borrow(self), name });
    }

    pub fn getTeamPlayers(self: Scoreboard, team_name: []const u8) []const []const u8 {
        return abi.call(raw.@"[method]scoreboard.get-team-players", []const []const u8, .{ abi.borrow(self), team_name });
    }

    pub fn getPlayerTeam(self: Scoreboard, player_name: []const u8) ?[]const u8 {
        return abi.call(raw.@"[method]scoreboard.get-player-team", ?[]const u8, .{ abi.borrow(self), player_name });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: Scoreboard) void {
        abi.keep(Scoreboard, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: Scoreboard) void {
        abi.drop(Scoreboard, self);
    }
};

pub const BedrockSortOrder = enum(u8) {
    ascending,
    descending,
};

pub const BedrockDisplaySlot = enum(u8) {
    player_list,
    sidebar,
    below_name,
};

pub const BedrockScoreboard = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]bedrock-scoreboard";

    pub fn addObjective(self: BedrockScoreboard, name: []const u8, display_name: []const u8, sort_order: BedrockSortOrder) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.add-objective", void, .{ abi.borrow(self), name, display_name, sort_order });
    }

    pub fn updateObjective(self: BedrockScoreboard, name: []const u8, display_name: []const u8, sort_order: BedrockSortOrder) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.update-objective", void, .{ abi.borrow(self), name, display_name, sort_order });
    }

    pub fn removeObjective(self: BedrockScoreboard, name: []const u8) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.remove-objective", void, .{ abi.borrow(self), name });
    }

    pub fn setDisplaySlot(self: BedrockScoreboard, slot: BedrockDisplaySlot, objective_name: []const u8) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.set-display-slot", void, .{ abi.borrow(self), slot, objective_name });
    }

    pub fn clearDisplaySlot(self: BedrockScoreboard, slot: BedrockDisplaySlot) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.clear-display-slot", void, .{ abi.borrow(self), slot });
    }

    pub fn updateScore(self: BedrockScoreboard, entity_name: []const u8, objective_name: []const u8, value: i32) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.update-score", void, .{ abi.borrow(self), entity_name, objective_name, value });
    }

    pub fn addScore(self: BedrockScoreboard, entity_name: []const u8, objective_name: []const u8, delta: i32) i32 {
        return abi.call(raw.@"[method]bedrock-scoreboard.add-score", i32, .{ abi.borrow(self), entity_name, objective_name, delta });
    }

    pub fn removeScore(self: BedrockScoreboard, entity_name: []const u8, objective_name: []const u8) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.remove-score", void, .{ abi.borrow(self), entity_name, objective_name });
    }

    pub fn resetEntityScores(self: BedrockScoreboard, entity_name: []const u8) void {
        return abi.call(raw.@"[method]bedrock-scoreboard.reset-entity-scores", void, .{ abi.borrow(self), entity_name });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: BedrockScoreboard) void {
        abi.keep(BedrockScoreboard, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: BedrockScoreboard) void {
        abi.drop(BedrockScoreboard, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.add-objective"(i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.update-objective"(i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.remove-objective"(i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.set-display-slot"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.clear-display-slot"(i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.update-score"(i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.add-score"(i32, i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.remove-score"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.reset-entity-scores"(i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.create-team"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.remove-team"(i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.update-team"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.add-player-to-team"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.remove-player-from-team"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.clear-team-players"(i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.get-teams"(i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.get-team"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.get-team-players"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]scoreboard.get-player-team"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.add-objective"(i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.update-objective"(i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.remove-objective"(i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.set-display-slot"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.clear-display-slot"(i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.update-score"(i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.add-score"(i32, i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.remove-score"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[method]bedrock-scoreboard.reset-entity-scores"(i32, i32, i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[resource-drop]scoreboard"(i32) void;
    extern "pumpkin:plugin/scoreboard@0.1.0" fn @"[resource-drop]bedrock-scoreboard"(i32) void;
};
