// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const player = @import("player.zig");
const common = @import("common.zig");
const world = @import("world.zig");
const text = @import("text.zig");
const uuid = @import("uuid.zig");
const recipe = @import("recipe.zig");
const enchantments = @import("enchantments.zig");
const permission = @import("permission.zig");
const advancement = @import("advancement.zig");
const datapack = @import("datapack.zig");

pub const Player = player.Player;
pub const BanPlayerOptions = player.BanPlayerOptions;
pub const BanIpOptions = player.BanIpOptions;
pub const ServerLink = player.ServerLink;
pub const KnownServerLink = player.KnownServerLink;
pub const ServerLinkLabel = player.ServerLinkLabel;
pub const GameMode = common.GameMode;
pub const World = world.World;
pub const TextComponent = text.TextComponent;
pub const Uuid = uuid.Uuid;
pub const RecipeManager = recipe.RecipeManager;
pub const EnchantmentManager = enchantments.EnchantmentManager;
pub const CustomEnchantment = enchantments.CustomEnchantment;
pub const PermissionLevel = permission.PermissionLevel;
pub const AdvancementInfo = advancement.AdvancementInfo;
pub const DatapackManager = datapack.DatapackManager;
pub const DatapackInfo = datapack.DatapackInfo;

/// Represents an operator entry in the ops configuration.
pub const OpEntry = struct {
    uuid: Uuid,
    name: []const u8,
    level: PermissionLevel,
    bypasses_player_limit: bool,
};

/// Interface for querying and managing server operators.
pub const OpManager = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]op-manager";

    /// Checks if a player UUID is currently an operator.
    pub fn isOp(self: OpManager, id: Uuid) bool {
        return abi.call(raw.@"[method]op-manager.is-op", bool, .{ abi.borrow(self), id });
    }

    /// Retrieves the operator entry for a player UUID, if present.
    pub fn getOp(self: OpManager, id: Uuid) ?OpEntry {
        return abi.call(raw.@"[method]op-manager.get-op", ?OpEntry, .{ abi.borrow(self), id });
    }

    /// Gets the effective permission level for a player UUID (returns zero if not op).
    pub fn getPermissionLevel(self: OpManager, id: Uuid) PermissionLevel {
        return abi.call(raw.@"[method]op-manager.get-permission-level", PermissionLevel, .{ abi.borrow(self), id });
    }

    /// Grants operator status to a player (online or offline) with the specified level and bypass setting.
    pub fn opPlayer(self: OpManager, name: []const u8, id: Uuid, level: PermissionLevel, bypasses_player_limit: bool) void {
        return abi.call(raw.@"[method]op-manager.op-player", void, .{ abi.borrow(self), name, id, level, bypasses_player_limit });
    }

    /// Revokes operator status from a player (online or offline). Returns true if the player was previously op.
    pub fn deopPlayer(self: OpManager, id: Uuid) bool {
        return abi.call(raw.@"[method]op-manager.deop-player", bool, .{ abi.borrow(self), id });
    }

    /// Returns a list of all operator entries on the server.
    pub fn listOps(self: OpManager) []const OpEntry {
        return abi.call(raw.@"[method]op-manager.list-ops", []const OpEntry, .{abi.borrow(self)});
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: OpManager) void {
        abi.keep(OpManager, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: OpManager) void {
        abi.drop(OpManager, self);
    }
};

/// Represents a banned player entry in the ban list.
pub const BannedPlayerEntry = struct {
    uuid: Uuid,
    name: []const u8,
    created: []const u8,
    source: []const u8,
    expires: ?[]const u8,
    reason: []const u8,
};

/// Represents a banned IP entry in the IP ban list.
pub const BannedIpEntry = struct {
    ip: []const u8,
    created: []const u8,
    source: []const u8,
    expires: ?[]const u8,
    reason: []const u8,
};

/// Global manager for player and IP bans.
pub const BanManager = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]ban-manager";

    /// Checks if a player UUID is currently banned.
    pub fn isPlayerBanned(self: BanManager, id: Uuid) bool {
        return abi.call(raw.@"[method]ban-manager.is-player-banned", bool, .{ abi.borrow(self), id });
    }

    /// Retrieves the ban entry for a player UUID, if banned.
    pub fn getPlayerBan(self: BanManager, id: Uuid) ?BannedPlayerEntry {
        return abi.call(raw.@"[method]ban-manager.get-player-ban", ?BannedPlayerEntry, .{ abi.borrow(self), id });
    }

    /// Bans a player by name and UUID with the specified options (works for online and offline players).
    pub fn banPlayer(self: BanManager, name: []const u8, id: Uuid, options: BanPlayerOptions) void {
        return abi.call(raw.@"[method]ban-manager.ban-player", void, .{ abi.borrow(self), name, id, options });
    }

    /// Removes a player ban by UUID. Returns true if the player was banned.
    pub fn unbanPlayer(self: BanManager, id: Uuid) bool {
        return abi.call(raw.@"[method]ban-manager.unban-player", bool, .{ abi.borrow(self), id });
    }

    /// Returns all currently active player bans.
    pub fn listPlayerBans(self: BanManager) []const BannedPlayerEntry {
        return abi.call(raw.@"[method]ban-manager.list-player-bans", []const BannedPlayerEntry, .{abi.borrow(self)});
    }

    /// Checks if an IP address is currently banned.
    pub fn isIpBanned(self: BanManager, ip: []const u8) bool {
        return abi.call(raw.@"[method]ban-manager.is-ip-banned", bool, .{ abi.borrow(self), ip });
    }

    /// Retrieves the ban entry for an IP address, if banned.
    pub fn getIpBan(self: BanManager, ip: []const u8) ?BannedIpEntry {
        return abi.call(raw.@"[method]ban-manager.get-ip-ban", ?BannedIpEntry, .{ abi.borrow(self), ip });
    }

    /// Bans an IP address with the specified options.
    pub fn banIp(self: BanManager, ip: []const u8, options: BanIpOptions) void {
        return abi.call(raw.@"[method]ban-manager.ban-ip", void, .{ abi.borrow(self), ip, options });
    }

    /// Removes an IP ban. Returns true if the IP was banned.
    pub fn unbanIp(self: BanManager, ip: []const u8) bool {
        return abi.call(raw.@"[method]ban-manager.unban-ip", bool, .{ abi.borrow(self), ip });
    }

    /// Returns all currently active IP bans.
    pub fn listIpBans(self: BanManager) []const BannedIpEntry {
        return abi.call(raw.@"[method]ban-manager.list-ip-bans", []const BannedIpEntry, .{abi.borrow(self)});
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: BanManager) void {
        abi.keep(BanManager, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: BanManager) void {
        abi.drop(BanManager, self);
    }
};

/// Represents a player entry in the server whitelist.
pub const WhitelistEntry = struct {
    uuid: Uuid,
    name: []const u8,
};

/// Global manager for the server whitelist.
pub const WhitelistManager = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]whitelist-manager";

    /// Returns whether the whitelist is currently enabled.
    pub fn isEnabled(self: WhitelistManager) bool {
        return abi.call(raw.@"[method]whitelist-manager.is-enabled", bool, .{abi.borrow(self)});
    }

    /// Enables or disables the server whitelist. If enabled and enforce-whitelist is set, kicks non-whitelisted players.
    pub fn setEnabled(self: WhitelistManager, enabled: bool) void {
        return abi.call(raw.@"[method]whitelist-manager.set-enabled", void, .{ abi.borrow(self), enabled });
    }

    /// Checks if a player UUID is on the whitelist.
    pub fn isWhitelisted(self: WhitelistManager, id: Uuid) bool {
        return abi.call(raw.@"[method]whitelist-manager.is-whitelisted", bool, .{ abi.borrow(self), id });
    }

    /// Adds a player to the whitelist (online or offline). Returns true if newly added.
    pub fn addPlayer(self: WhitelistManager, name: []const u8, id: Uuid) bool {
        return abi.call(raw.@"[method]whitelist-manager.add-player", bool, .{ abi.borrow(self), name, id });
    }

    /// Removes a player from the whitelist. Returns true if the player was on the whitelist.
    pub fn removePlayer(self: WhitelistManager, id: Uuid) bool {
        return abi.call(raw.@"[method]whitelist-manager.remove-player", bool, .{ abi.borrow(self), id });
    }

    /// Returns all whitelisted player entries.
    pub fn listEntries(self: WhitelistManager) []const WhitelistEntry {
        return abi.call(raw.@"[method]whitelist-manager.list-entries", []const WhitelistEntry, .{abi.borrow(self)});
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: WhitelistManager) void {
        abi.keep(WhitelistManager, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: WhitelistManager) void {
        abi.drop(WhitelistManager, self);
    }
};

/// Represents the difficulty setting of a Minecraft server.
pub const Difficulty = enum(u8) {
    /// Hostile mobs do not spawn. Players regain health automatically.
    peaceful,
    /// Hostile mobs deal less damage.
    easy,
    /// Standard Minecraft difficulty.
    normal,
    /// Hostile mobs deal more damage.
    hard,
};

/// Represents the three main Minecraft dimensions.
pub const Dimension = enum(u8) {
    overworld,
    nether,
    end,
};

pub const SysInfo = struct {
    cpu_count: ?u32,
    total_memory: ?u64,
    used_memory: ?u64,
    os_name: ?[]const u8,
    os_version: ?[]const u8,
    pumpkin_version: []const u8,
};

pub const CommandSender = union(enum) {
    console,
    player: Player,
};

/// Represents the global server instance.
pub const Server = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]server";

    /// Returns system information (CPU, Memory, OS).
    /// Fields are returned only if the plugin has the corresponding permissions.
    pub fn getSysInfo(self: Server) SysInfo {
        return abi.call(raw.@"[method]server.get-sys-info", SysInfo, .{abi.borrow(self)});
    }

    /// Returns the current difficulty level of the server.
    pub fn getDifficulty(self: Server) Difficulty {
        return abi.call(raw.@"[method]server.get-difficulty", Difficulty, .{abi.borrow(self)});
    }

    /// Returns the total number of players currently connected to the server.
    pub fn getPlayerCount(self: Server) u32 {
        return abi.call(raw.@"[method]server.get-player-count", u32, .{abi.borrow(self)});
    }

    /// Returns the rolling average Milliseconds Per Tick (MSPT).
    /// A value below 50.0 is required for a stable 20 TPS.
    pub fn getMspt(self: Server) f64 {
        return abi.call(raw.@"[method]server.get-mspt", f64, .{abi.borrow(self)});
    }

    /// Returns the effective Ticks Per Second (TPS).
    /// Ideal value is 20.0.
    pub fn getTps(self: Server) f64 {
        return abi.call(raw.@"[method]server.get-tps", f64, .{abi.borrow(self)});
    }

    /// Returns a list of all online players across all worlds.
    pub fn getAllPlayers(self: Server) []const Player {
        return abi.call(raw.@"[method]server.get-all-players", []const Player, .{abi.borrow(self)});
    }

    /// Searches for a player by their exact name.
    pub fn getPlayerByName(self: Server, name: []const u8) ?Player {
        return abi.call(raw.@"[method]server.get-player-by-name", ?Player, .{ abi.borrow(self), name });
    }

    /// Searches for a player by their UUID string.
    pub fn getPlayerByUuid(self: Server, id: Uuid) ?Player {
        return abi.call(raw.@"[method]server.get-player-by-uuid", ?Player, .{ abi.borrow(self), id });
    }

    /// Returns a list of all worlds on this server.
    pub fn getAllWorlds(self: Server) []const World {
        return abi.call(raw.@"[method]server.get-all-worlds", []const World, .{abi.borrow(self)});
    }

    /// Gets a world by its dimension name (e.g., "minecraft:overworld") or custom world name (e.g., "world", "arena_1").
    pub fn getWorldByName(self: Server, name: []const u8) ?World {
        return abi.call(raw.@"[method]server.get-world-by-name", ?World, .{ abi.borrow(self), name });
    }

    /// Checks if a world exists by name or dimension.
    pub fn hasWorld(self: Server, name: []const u8) bool {
        return abi.call(raw.@"[method]server.has-world", bool, .{ abi.borrow(self), name });
    }

    pub fn executeCommand(self: Server, command: []const u8, sender: CommandSender) void {
        return abi.call(raw.@"[method]server.execute-command", void, .{ abi.borrow(self), command, sender });
    }

    /// Creates or loads a world by its name and dimension.
    /// If a world with the given name already exists, it will be returned.
    pub fn createWorld(self: Server, name: []const u8, dimension: Dimension) World {
        return abi.call(raw.@"[method]server.create-world", World, .{ abi.borrow(self), name, dimension });
    }

    /// Unloads and saves a world by its name or dimension.
    /// Returns an error if the world cannot be found, is the primary/default world, or still has players inside.
    pub fn unloadWorld(self: Server, name: []const u8) abi.Result(void, []const u8) {
        return abi.call(raw.@"[method]server.unload-world", abi.Result(void, []const u8), .{ abi.borrow(self), name });
    }

    /// Saves all players, player advancements, and loaded worlds to disk.
    pub fn saveAll(self: Server) abi.Result(void, []const u8) {
        return abi.call(raw.@"[method]server.save-all", abi.Result(void, []const u8), .{abi.borrow(self)});
    }

    /// Returns a list of all online players in a specific world.
    ///
    /// Consumes `world_ref`.
    pub fn getPlayersInWorld(self: Server, world_ref: World) []const Player {
        return abi.call(raw.@"[method]server.get-players-in-world", []const Player, .{ abi.borrow(self), world_ref });
    }

    /// Returns the number of online players in a specific world.
    ///
    /// Consumes `world_ref`.
    pub fn getPlayerCountInWorld(self: Server, world_ref: World) u32 {
        return abi.call(raw.@"[method]server.get-player-count-in-world", u32, .{ abi.borrow(self), world_ref });
    }

    /// Broadcasts a system chat message to all players.
    pub fn broadcast(self: Server, message: []const u8) void {
        return abi.call(raw.@"[method]server.broadcast", void, .{ abi.borrow(self), message });
    }

    /// Deletes a signed chat message from all players' chat windows using its 256-byte signature.
    pub fn deleteMessageBySignature(self: Server, signature: []const u8) void {
        return abi.call(raw.@"[method]server.delete-message-by-signature", void, .{ abi.borrow(self), signature });
    }

    /// Deletes a signed chat message from all players' chat windows using its signature cache ID.
    pub fn deleteMessageById(self: Server, signature_id: i32) void {
        return abi.call(raw.@"[method]server.delete-message-by-id", void, .{ abi.borrow(self), signature_id });
    }

    /// Broadcasts a tab list header and footer to all players.
    ///
    /// Consumes `header`.
    /// Consumes `footer`.
    pub fn broadcastTabListHeaderFooter(self: Server, header: TextComponent, footer: TextComponent) void {
        return abi.call(raw.@"[method]server.broadcast-tab-list-header-footer", void, .{ abi.borrow(self), header, footer });
    }

    /// Returns the maximum number of players allowed on the server.
    pub fn getMaxPlayers(self: Server) u32 {
        return abi.call(raw.@"[method]server.get-max-players", u32, .{abi.borrow(self)});
    }

    /// Returns whether the server is in hardcore mode.
    pub fn isHardcore(self: Server) bool {
        return abi.call(raw.@"[method]server.is-hardcore", bool, .{abi.borrow(self)});
    }

    /// Returns whether the server is in online mode (authenticates with Mojang).
    pub fn isOnlineMode(self: Server) bool {
        return abi.call(raw.@"[method]server.is-online-mode", bool, .{abi.borrow(self)});
    }

    /// Returns the server's Message of the Day (MOTD).
    pub fn getMotd(self: Server) []const u8 {
        return abi.call(raw.@"[method]server.get-motd", []const u8, .{abi.borrow(self)});
    }

    /// Returns whether the server has a whitelist enabled.
    pub fn hasWhitelist(self: Server) bool {
        return abi.call(raw.@"[method]server.has-whitelist", bool, .{abi.borrow(self)});
    }

    /// Returns whether the server allows the Nether dimension.
    pub fn getAllowNether(self: Server) bool {
        return abi.call(raw.@"[method]server.get-allow-nether", bool, .{abi.borrow(self)});
    }

    /// Returns whether the server allows the End dimension.
    pub fn getAllowEnd(self: Server) bool {
        return abi.call(raw.@"[method]server.get-allow-end", bool, .{abi.borrow(self)});
    }

    /// Returns the server's maximum view distance.
    pub fn getViewDistance(self: Server) u8 {
        return abi.call(raw.@"[method]server.get-view-distance", u8, .{abi.borrow(self)});
    }

    /// Returns the server's maximum simulation distance.
    pub fn getSimulationDistance(self: Server) u8 {
        return abi.call(raw.@"[method]server.get-simulation-distance", u8, .{abi.borrow(self)});
    }

    /// Returns the server's default gamemode.
    pub fn getDefaultGamemode(self: Server) GameMode {
        return abi.call(raw.@"[method]server.get-default-gamemode", GameMode, .{abi.borrow(self)});
    }

    /// Returns the recipe manager to register custom recipes.
    pub fn getRecipeManager(self: Server) RecipeManager {
        return abi.call(raw.@"[method]server.get-recipe-manager", RecipeManager, .{abi.borrow(self)});
    }

    /// Returns the operator manager to query or modify server operators.
    pub fn getOpManager(self: Server) OpManager {
        return abi.call(raw.@"[method]server.get-op-manager", OpManager, .{abi.borrow(self)});
    }

    /// Returns the global ban manager for querying and modifying player and IP bans.
    pub fn getBanManager(self: Server) BanManager {
        return abi.call(raw.@"[method]server.get-ban-manager", BanManager, .{abi.borrow(self)});
    }

    /// Returns the global whitelist manager for querying and modifying the server whitelist.
    pub fn getWhitelistManager(self: Server) WhitelistManager {
        return abi.call(raw.@"[method]server.get-whitelist-manager", WhitelistManager, .{abi.borrow(self)});
    }

    /// Returns detailed information about an advancement by its ID (e.g., "minecraft:story/mine_stone" or "story/mine_stone").
    pub fn getAdvancement(self: Server, id: []const u8) ?AdvancementInfo {
        return abi.call(raw.@"[method]server.get-advancement", ?AdvancementInfo, .{ abi.borrow(self), id });
    }

    /// Returns a list of all registered advancement IDs on the server.
    pub fn getAllAdvancementIds(self: Server) []const []const u8 {
        return abi.call(raw.@"[method]server.get-all-advancement-ids", []const []const u8, .{abi.borrow(self)});
    }

    /// Returns the global enchantment manager for registering and querying custom enchantments.
    pub fn getEnchantmentManager(self: Server) EnchantmentManager {
        return abi.call(raw.@"[method]server.get-enchantment-manager", EnchantmentManager, .{abi.borrow(self)});
    }

    /// Returns information about an enchantment by its ID (vanilla or custom).
    pub fn getEnchantment(self: Server, id: []const u8) ?CustomEnchantment {
        return abi.call(raw.@"[method]server.get-enchantment", ?CustomEnchantment, .{ abi.borrow(self), id });
    }

    /// Returns a list of all registered enchantment IDs (custom and vanilla) on the server.
    pub fn getAllEnchantmentIds(self: Server) []const []const u8 {
        return abi.call(raw.@"[method]server.get-all-enchantment-ids", []const []const u8, .{abi.borrow(self)});
    }

    /// Returns the global datapack manager for inspecting, enabling, disabling, and reloading datapacks.
    pub fn getDatapackManager(self: Server) DatapackManager {
        return abi.call(raw.@"[method]server.get-datapack-manager", DatapackManager, .{abi.borrow(self)});
    }

    /// Broadcasts custom server links to all connected players (displayed in the client Esc pause menu in 1.21+).
    pub fn setServerLinks(self: Server, links: []const ServerLink) void {
        return abi.call(raw.@"[method]server.set-server-links", void, .{ abi.borrow(self), links });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: Server) void {
        abi.keep(Server, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: Server) void {
        abi.drop(Server, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]op-manager.is-op"(i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]op-manager.get-op"(i32, i64, i64, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]op-manager.get-permission-level"(i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]op-manager.op-player"(i32, i32, i32, i64, i64, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]op-manager.deop-player"(i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]op-manager.list-ops"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.is-player-banned"(i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.get-player-ban"(i32, i64, i64, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.ban-player"(i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.unban-player"(i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.list-player-bans"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.is-ip-banned"(i32, i32, i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.get-ip-ban"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.ban-ip"(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i64, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.unban-ip"(i32, i32, i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]ban-manager.list-ip-bans"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]whitelist-manager.is-enabled"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]whitelist-manager.set-enabled"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]whitelist-manager.is-whitelisted"(i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]whitelist-manager.add-player"(i32, i32, i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]whitelist-manager.remove-player"(i32, i64, i64) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]whitelist-manager.list-entries"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-sys-info"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-difficulty"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-player-count"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-mspt"(i32) f64;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-tps"(i32) f64;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-all-players"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-player-by-name"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-player-by-uuid"(i32, i64, i64, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-all-worlds"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-world-by-name"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.has-world"(i32, i32, i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.execute-command"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.create-world"(i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.unload-world"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.save-all"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-players-in-world"(i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-player-count-in-world"(i32, i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.broadcast"(i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.delete-message-by-signature"(i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.delete-message-by-id"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.broadcast-tab-list-header-footer"(i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-max-players"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.is-hardcore"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.is-online-mode"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-motd"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.has-whitelist"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-allow-nether"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-allow-end"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-view-distance"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-simulation-distance"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-default-gamemode"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-recipe-manager"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-op-manager"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-ban-manager"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-whitelist-manager"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-advancement"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-all-advancement-ids"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-enchantment-manager"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-enchantment"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-all-enchantment-ids"(i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.get-datapack-manager"(i32) i32;
    extern "pumpkin:plugin/server@0.1.0" fn @"[method]server.set-server-links"(i32, i32, i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[resource-drop]op-manager"(i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[resource-drop]ban-manager"(i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[resource-drop]whitelist-manager"(i32) void;
    extern "pumpkin:plugin/server@0.1.0" fn @"[resource-drop]server"(i32) void;
};
