// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");
const common = @import("common.zig");

pub const NamedColor = common.NamedColor;
pub const RgbColor = common.RgbColor;
pub const ArgbColor = common.ArgbColor;

pub const TextComponent = enum(u32) {
    _,

    pub const resource_drop = &raw.@"[resource-drop]text-component";

    /// Creates a plain text component.
    pub fn text(plain: []const u8) TextComponent {
        return abi.call(raw.@"[static]text-component.text", TextComponent, .{plain});
    }

    /// Creates a translation component.
    pub fn translate(key: []const u8, with: []const TextComponent) TextComponent {
        return abi.call(raw.@"[static]text-component.translate", TextComponent, .{ key, with });
    }

    /// Creates a translation component with a Bedrock-specific fallback key.
    pub fn translateCross(java_key: []const u8, bedrock_key: []const u8, with: []const TextComponent) TextComponent {
        return abi.call(raw.@"[static]text-component.translate-cross", TextComponent, .{ java_key, bedrock_key, with });
    }

    /// Creates an entity names / selector text component.
    pub fn entityNames(selector: []const u8, separator: ?[]const u8) TextComponent {
        return abi.call(raw.@"[static]text-component.entity-names", TextComponent, .{ selector, separator });
    }

    /// Creates a keybind text component (e.g., "key.jump").
    pub fn keybind(keybind_: []const u8) TextComponent {
        return abi.call(raw.@"[static]text-component.keybind", TextComponent, .{keybind_});
    }

    /// Creates a custom translation component.
    pub fn custom(namespace: []const u8, key: []const u8, locale: []const u8, with: []const TextComponent) TextComponent {
        return abi.call(raw.@"[static]text-component.custom", TextComponent, .{ namespace, key, locale, with });
    }

    /// Parses a legacy Minecraft formatted string (using section signs '§' by default) into a text component.
    pub fn fromLegacyString(input: []const u8) TextComponent {
        return abi.call(raw.@"[static]text-component.from-legacy-string", TextComponent, .{input});
    }

    /// Parses a legacy formatted string using a custom color code symbol (e.g. '&' or '§').
    pub fn fromLegacyStringWithCode(input: []const u8, code_symbol: u21) TextComponent {
        return abi.call(raw.@"[static]text-component.from-legacy-string-with-code", TextComponent, .{ input, code_symbol });
    }

    /// Parses a standard Minecraft JSON text component.
    pub fn fromJson(json: []const u8) abi.Result(TextComponent, []const u8) {
        return abi.call(raw.@"[static]text-component.from-json", abi.Result(TextComponent, []const u8), .{json});
    }

    /// Serializes the text component to JSON format.
    pub fn toJson(self: TextComponent) []const u8 {
        return abi.call(raw.@"[method]text-component.to-json", []const u8, .{abi.borrow(self)});
    }

    /// Consumes `child`.
    pub fn addChild(self: TextComponent, child: TextComponent) void {
        return abi.call(raw.@"[method]text-component.add-child", void, .{ abi.borrow(self), child });
    }

    pub fn addText(self: TextComponent, text_: []const u8) void {
        return abi.call(raw.@"[method]text-component.add-text", void, .{ abi.borrow(self), text_ });
    }

    pub fn getText(self: TextComponent) []const u8 {
        return abi.call(raw.@"[method]text-component.get-text", []const u8, .{abi.borrow(self)});
    }

    pub fn encode(self: TextComponent) []const u8 {
        return abi.call(raw.@"[method]text-component.encode", []const u8, .{abi.borrow(self)});
    }

    pub fn toPrettyConsole(self: TextComponent) []const u8 {
        return abi.call(raw.@"[method]text-component.to-pretty-console", []const u8, .{abi.borrow(self)});
    }

    /// Style
    pub fn colorNamed(self: TextComponent, color: NamedColor) void {
        return abi.call(raw.@"[method]text-component.color-named", void, .{ abi.borrow(self), color });
    }

    pub fn colorRgb(self: TextComponent, color: RgbColor) void {
        return abi.call(raw.@"[method]text-component.color-rgb", void, .{ abi.borrow(self), color });
    }

    pub fn gradientNamed(self: TextComponent, colors: []const NamedColor) void {
        return abi.call(raw.@"[method]text-component.gradient-named", void, .{ abi.borrow(self), colors });
    }

    pub fn gradient(self: TextComponent, colors: []const RgbColor) void {
        return abi.call(raw.@"[method]text-component.gradient", void, .{ abi.borrow(self), colors });
    }

    pub fn rainbow(self: TextComponent) void {
        return abi.call(raw.@"[method]text-component.rainbow", void, .{abi.borrow(self)});
    }

    pub fn bold(self: TextComponent, value: bool) void {
        return abi.call(raw.@"[method]text-component.bold", void, .{ abi.borrow(self), value });
    }

    pub fn italic(self: TextComponent, value: bool) void {
        return abi.call(raw.@"[method]text-component.italic", void, .{ abi.borrow(self), value });
    }

    pub fn underlined(self: TextComponent, value: bool) void {
        return abi.call(raw.@"[method]text-component.underlined", void, .{ abi.borrow(self), value });
    }

    pub fn strikethrough(self: TextComponent, value: bool) void {
        return abi.call(raw.@"[method]text-component.strikethrough", void, .{ abi.borrow(self), value });
    }

    pub fn obfuscated(self: TextComponent, value: bool) void {
        return abi.call(raw.@"[method]text-component.obfuscated", void, .{ abi.borrow(self), value });
    }

    /// Text inserted into chat when shift-clicked
    pub fn insertion(self: TextComponent, text_: []const u8) void {
        return abi.call(raw.@"[method]text-component.insertion", void, .{ abi.borrow(self), text_ });
    }

    pub fn font(self: TextComponent, font_: []const u8) void {
        return abi.call(raw.@"[method]text-component.font", void, .{ abi.borrow(self), font_ });
    }

    pub fn shadowColor(self: TextComponent, color: ArgbColor) void {
        return abi.call(raw.@"[method]text-component.shadow-color", void, .{ abi.borrow(self), color });
    }

    /// Click events
    pub fn clickOpenUrl(self: TextComponent, url: []const u8) void {
        return abi.call(raw.@"[method]text-component.click-open-url", void, .{ abi.borrow(self), url });
    }

    pub fn clickOpenFile(self: TextComponent, path: []const u8) void {
        return abi.call(raw.@"[method]text-component.click-open-file", void, .{ abi.borrow(self), path });
    }

    pub fn clickRunCommand(self: TextComponent, command: []const u8) void {
        return abi.call(raw.@"[method]text-component.click-run-command", void, .{ abi.borrow(self), command });
    }

    pub fn clickSuggestCommand(self: TextComponent, command: []const u8) void {
        return abi.call(raw.@"[method]text-component.click-suggest-command", void, .{ abi.borrow(self), command });
    }

    pub fn clickChangePage(self: TextComponent, page: u32) void {
        return abi.call(raw.@"[method]text-component.click-change-page", void, .{ abi.borrow(self), page });
    }

    pub fn clickCopyToClipboard(self: TextComponent, text_: []const u8) void {
        return abi.call(raw.@"[method]text-component.click-copy-to-clipboard", void, .{ abi.borrow(self), text_ });
    }

    /// Hover events
    ///
    /// Consumes `text_`.
    pub fn hoverShowText(self: TextComponent, text_: TextComponent) void {
        return abi.call(raw.@"[method]text-component.hover-show-text", void, .{ abi.borrow(self), text_ });
    }

    /// Item data as SNBT string
    pub fn hoverShowItem(self: TextComponent, item: []const u8) void {
        return abi.call(raw.@"[method]text-component.hover-show-item", void, .{ abi.borrow(self), item });
    }

    pub fn hoverShowEntity(self: TextComponent, entity_type: []const u8, id: []const u8, name: ?TextComponent) void {
        return abi.call(raw.@"[method]text-component.hover-show-entity", void, .{ abi.borrow(self), entity_type, id, name });
    }

    /// Keeps the handle alive past the current callback. Release it with `deinit`.
    pub fn keep(self: TextComponent) void {
        abi.keep(TextComponent, self);
    }

    /// Releases the handle now instead of when the callback returns.
    pub fn deinit(self: TextComponent) void {
        abi.drop(TextComponent, self);
    }
};

const raw = struct {
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.text"(i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.translate"(i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.translate-cross"(i32, i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.entity-names"(i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.keybind"(i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.custom"(i32, i32, i32, i32, i32, i32, i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.from-legacy-string"(i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.from-legacy-string-with-code"(i32, i32, i32) i32;
    extern "pumpkin:plugin/text@0.1.0" fn @"[static]text-component.from-json"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.to-json"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.add-child"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.add-text"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.get-text"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.encode"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.to-pretty-console"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.color-named"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.color-rgb"(i32, i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.gradient-named"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.gradient"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.rainbow"(i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.bold"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.italic"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.underlined"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.strikethrough"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.obfuscated"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.insertion"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.font"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.shadow-color"(i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.click-open-url"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.click-open-file"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.click-run-command"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.click-suggest-command"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.click-change-page"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.click-copy-to-clipboard"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.hover-show-text"(i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.hover-show-item"(i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[method]text-component.hover-show-entity"(i32, i32, i32, i32, i32, i32, i32) void;
    extern "pumpkin:plugin/text@0.1.0" fn @"[resource-drop]text-component"(i32) void;
};
