// Generated by tools/gen.zig, do not edit.

const abi = @import("../abi.zig");

/// A 128-bit UUID represented as two 64-bit integers.
pub const Uuid = struct {
    high: u64,
    low: u64,
};

/// Generates a new random v4 UUID.
pub fn generate() Uuid {
    return abi.call(raw.generate, Uuid, .{});
}

/// Parses a UUID from a string. Returns none if the string is not a valid UUID.
pub fn parse(s: []const u8) ?Uuid {
    return abi.call(raw.parse, ?Uuid, .{s});
}

/// Converts a UUID to its standard string representation.
pub fn toString(id: Uuid) []const u8 {
    return abi.call(raw.@"to-string", []const u8, .{id});
}

const raw = struct {
    extern "pumpkin:plugin/uuid@0.1.0" fn generate(i32) void;
    extern "pumpkin:plugin/uuid@0.1.0" fn parse(i32, i32, i32) void;
    extern "pumpkin:plugin/uuid@0.1.0" fn @"to-string"(i64, i64, i32) void;
};
