// Generated by tools/gen.zig, do not edit.

/// Where something is.
pub const Point = struct {
    x: i32,
    y: i32,
    /// Optional label.
    label: ?[]const u8,
};

pub const Color = enum(u8) {
    red,
    green,
    blue,
};

pub const Access = packed struct(u8) {
    read: bool = false,
    write: bool = false,
    exec: bool = false,
    _: u5 = 0,
};

pub const Shape = union(enum) {
    nothing,
    circle: f32,
    polygon: []const Point,
};

pub const Pair = struct { u8, f64 };

pub const Names = []const []const u8;
